import { createClient } from '@supabase/supabase-js';
import crypto from 'crypto';
const PROVIDER='THUMBTACK',DEFAULT_HEADER='x-dani-webhook-secret';
const first=(...v)=>v.find(x=>x!==undefined&&x!==null&&String(x).trim()!=='')??null;
const str=v=>v==null?null:String(v);
const obj=v=>v&&typeof v==='object'&&!Array.isArray(v)?v:{};
const dataOf=b=>obj(first(b.data,b.payload,b.object,b));
function kind(b,d){const t=String(first(b.event_type,b.eventType,b.type,b.topic,b.event?.type,'')).toLowerCase();if(t.includes('message'))return'MESSAGE';if(t.includes('review'))return'REVIEW';if(t.includes('lead')||t.includes('negotiation')||t.includes('job'))return'LEAD';if(first(d.message,d.message_text,d.text))return'MESSAGE';if(first(d.review,d.rating,d.stars))return'REVIEW';return'LEAD'}
function leadId(b,d){const l=obj(first(d.lead,d.negotiation,b.lead,b.negotiation));return str(first(d.lead_id,d.leadId,d.negotiation_id,d.negotiationId,l.id,l.lead_id,b.lead_id,b.negotiation_id))}
function externalId(b,d,k){const n=obj(k==='MESSAGE'?first(d.message,b.message):k==='REVIEW'?first(d.review,b.review):first(d.lead,d.negotiation,b.lead,b.negotiation));return str(first(b.event_id,b.eventId,d.event_id,d.eventId,n.id,d.id,leadId(b,d)))}
function eventKey(b,d,k){const id=externalId(b,d,k);return id?`${k}:${id}`:`BODY:${crypto.createHash('sha256').update(JSON.stringify(b)).digest('hex')}`}
function contact(d){const c=obj(first(d.customer,d.user,d.homeowner,d.contact)),l=obj(first(d.lead,d.negotiation)),s=Object.keys(c).length?c:obj(first(l.customer,l.user,l.homeowner));return{name:str(first(s.name,s.full_name,s.fullName,d.customer_name,d.customerName,l.customer_name))||'Thumbtack customer',email:str(first(s.email,d.email,l.email)),phone:str(first(s.phone,s.phone_number,s.phoneNumber,d.phone,l.phone))}}
function details(d){const p=obj(first(d.project,d.job,d.request));return str(first(d.details,d.description,d.job_details,d.jobDetails,p.description,p.details,p.title,d.category_name,d.categoryName))}
function occurred(b,d){const x=first(b.created_at,b.createdAt,b.timestamp,d.created_at,d.createdAt,d.timestamp);if(!x)return null;const dt=new Date(x);return Number.isNaN(dt.valueOf())?null:dt.toISOString()}
async function findLead(admin,id){if(!id)return null;const{data}=await admin.from('dd_sales_queue').select('id,sales_metadata').eq('source','THUMBTACK').contains('sales_metadata',{thumbtack_lead_id:id}).maybeSingle();return data||null}
async function saveLead(admin,b,d){const id=leadId(b,d)||externalId(b,d,'LEAD');if(!id)throw Error('THUMBTACK_LEAD_ID_MISSING');const c=contact(d),note=details(d),old=await findLead(admin,id),metadata={...(old?.sales_metadata||{}),thumbtack_lead_id:id,thumbtack_category:first(d.category_name,d.categoryName,d.category?.name)||null,thumbtack_status:first(d.status,d.lead_status,d.leadStatus)||null,last_thumbtack_event_at:new Date().toISOString()};const patch={contact_name:c.name,email:c.email,phone:c.phone,lane:'INBOUND',source:'THUMBTACK',source_confidence:'VERIFIED',source_direction:'INBOUND',next_action:'Respond to Thumbtack lead',preferred_contact_channel:'THUMBTACK',sales_metadata:metadata,notes:note?`Thumbtack inbound lead: ${note}`:'Thumbtack inbound lead.'};let saved;if(old){const{data,error}=await admin.from('dd_sales_queue').update({...patch,updated_at:new Date().toISOString()}).eq('id',old.id).select('id').single();if(error)throw error;saved=data}else{const{data,error}=await admin.from('dd_sales_queue').insert({...patch,disposition:'NOT_CONTACTED',intent_tier:'NEW_INBOUND',contact_pressure_state:'NORMAL'}).select('id').single();if(error)throw error;saved=data}await Promise.all([admin.from('dd_external_lead_messages').update({sales_queue_id:saved.id}).eq('provider',PROVIDER).eq('external_lead_id',id).is('sales_queue_id',null),admin.from('dd_external_reviews').update({sales_queue_id:saved.id}).eq('provider',PROVIDER).eq('external_lead_id',id).is('sales_queue_id',null)]);return saved}
async function saveMessage(admin,b,d){const m=obj(first(d.message,b.message,d)),mid=str(first(m.id,d.message_id,d.messageId,externalId(b,d,'MESSAGE')));if(!mid)throw Error('THUMBTACK_MESSAGE_ID_MISSING');const lid=leadId(b,d),sales=await findLead(admin,lid),sender=obj(first(m.sender,d.sender)),direction=String(first(m.direction,d.direction,'INBOUND')).toUpperCase();const{error}=await admin.from('dd_external_lead_messages').upsert({provider:PROVIDER,external_message_id:mid,external_lead_id:lid,sales_queue_id:sales?.id||null,direction,sender_name:str(first(sender.name,m.sender_name,d.sender_name)),message_text:str(first(m.text,m.body,m.message,d.message_text,d.text)),occurred_at:occurred(b,d),raw_payload:b,needs_response:direction!=='OUTBOUND'},{onConflict:'provider,external_message_id',ignoreDuplicates:true});if(error)throw error;if(sales?.id&&direction!=='OUTBOUND')await admin.from('dd_sales_queue').update({next_action:'Respond to Thumbtack message',preferred_contact_channel:'THUMBTACK',updated_at:new Date().toISOString()}).eq('id',sales.id);return sales}
async function saveReview(admin,b,d){const r=obj(first(d.review,b.review,d)),rid=str(first(r.id,d.review_id,d.reviewId,externalId(b,d,'REVIEW')));if(!rid)throw Error('THUMBTACK_REVIEW_ID_MISSING');const lid=leadId(b,d),sales=await findLead(admin,lid),reviewer=obj(first(r.reviewer,d.reviewer));const{error}=await admin.from('dd_external_reviews').upsert({provider:PROVIDER,external_review_id:rid,external_lead_id:lid,sales_queue_id:sales?.id||null,reviewer_name:str(first(reviewer.name,r.reviewer_name,d.reviewer_name)),rating:Number(first(r.rating,r.stars,d.rating))||null,review_text:str(first(r.text,r.body,r.review,d.review_text)),occurred_at:occurred(b,d),raw_payload:b},{onConflict:'provider,external_review_id',ignoreDuplicates:true});if(error)throw error;return sales}
export default async function handler(req,res){if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});const url=process.env.SUPABASE_URL||process.env.REACT_APP_SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)return res.status(500).json({error:'Integration storage unavailable'});const admin=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}}),{data:cred,error:ce}=await admin.from('dd_integration_webhook_credentials').select('secret_sha256,header_name,is_active').eq('provider',PROVIDER).maybeSingle();if(ce||!cred?.is_active)return res.status(503).json({error:'Thumbtack integration not configured'});const supplied=String(req.headers[String(cred.header_name||DEFAULT_HEADER).toLowerCase()]||''),actual=crypto.createHash('sha256').update(supplied).digest('hex'),expected=String(cred.secret_sha256||'');if(!supplied||actual.length!==expected.length||!crypto.timingSafeEqual(Buffer.from(actual),Buffer.from(expected)))return res.status(401).json({error:'Unauthorized'});const b=obj(req.body),d=dataOf(b),k=kind(b,d),ek=eventKey(b,d,k),eid=externalId(b,d,k),{data:event,error:ee}=await admin.from('dd_external_webhook_events').insert({provider:PROVIDER,event_key:ek,event_type:k,external_object_id:eid,payload:b}).select('id').maybeSingle();if(ee){if(String(ee.code)==='23505')return res.status(200).json({success:true,duplicate:true});return res.status(500).json({error:'Webhook event could not be recorded'})}try{let sales=null;if(k==='LEAD')sales=await saveLead(admin,b,d);else if(k==='MESSAGE')sales=await saveMessage(admin,b,d);else sales=await saveReview(admin,b,d);await admin.from('dd_external_webhook_events').update({processing_status:'PROCESSED',processed_at:new Date().toISOString()}).eq('id',event.id);return res.status(200).json({success:true,type:k,salesQueueId:sales?.id||null})}catch(e){await admin.from('dd_external_webhook_events').update({processing_status:'FAILED',processing_error:String(e?.message||e).slice(0,1000),processed_at:new Date().toISOString()}).eq('id',event.id);console.error('Thumbtack webhook processing failed',e);return res.status(500).json({error:'Webhook processing failed'})}}