import { authenticatePortalRequest, requireRole } from './_portalAuth.js';

const STAFF=['admin','owner','staff_admin','staff'];
const tables={
 procurementEvents:'dd_contract_procurement_events',questions:'dd_contract_solicitation_questions',amendments:'dd_contract_amendments',documents:'dd_contract_documents',lineItems:'dd_contract_line_items',taskOrders:'dd_contract_task_orders',closeouts:'dd_contract_closeouts',renewals:'dd_contract_renewals'
};
const fail=(res,error,status=400)=>res.status(status).json({success:false,error});
const ok=(res,data)=>res.status(200).json({success:true,...data});
function guard(ctx,res){const g=requireRole(ctx,STAFF);return g&&!ctx.isStaff?fail(res,g.error,g.status):null}
async function snapshot(sb){
 const names=Object.values(tables); const results=await Promise.all(names.map(t=>sb.from(t).select('*').order('updated_at',{ascending:false}).limit(500)));
 const err=results.find(r=>r.error); if(err) throw err.error;
 return Object.fromEntries(Object.keys(tables).map((k,i)=>[k,results[i].data||[]]));
}
const specs={
 create_procurement_event:['procurementEvents',{opportunity_id:'opportunityId',buyer_id:'buyerId',event_type:'eventType',event_status:'eventStatus',event_number:'eventNumber',event_title:'eventTitle',procurement_method:'procurementMethod',source_url:'sourceUrl',issue_date:'issueDate',response_deadline:'responseDeadline',award_date:'awardDate',notes:'notes'}],
 create_question:['questions',{solicitation_id:'solicitationId',question_number:'questionNumber',submitted_at:'submittedAt',submitted_by:'submittedBy',question_text:'questionText',buyer_response:'buyerResponse',response_at:'responseAt',status:'status',source_document_ref:'sourceDocumentRef'}],
 create_amendment:['amendments',{solicitation_id:'solicitationId',amendment_number:'amendmentNumber',issued_at:'issuedAt',effective_at:'effectiveAt',title:'title',summary:'summary',changes:'changes',document_ref:'documentRef',deadline_changed_to:'deadlineChangedTo',acknowledged_at:'acknowledgedAt',acknowledged_by:'acknowledgedBy'}],
 create_document:['documents',{opportunity_id:'opportunityId',solicitation_id:'solicitationId',proposal_id:'proposalId',contract_id:'contractId',document_type:'documentType',document_name:'documentName',version_number:'versionNumber',document_ref:'documentRef',source_url:'sourceUrl',is_current:'isCurrent',uploaded_by:'uploadedBy',notes:'notes'}],
 create_line_item:['lineItems',{contract_id:'contractId',line_type:'lineType',line_number:'lineNumber',description:'description',quantity:'quantity',unit:'unit',unit_price:'unitPrice',ceiling_amount:'ceilingAmount',funded_amount:'fundedAmount',period_start:'periodStart',period_end:'periodEnd',option_year:'optionYear',status:'status'}],
 create_task_order:['taskOrders',{contract_id:'contractId',task_order_number:'taskOrderNumber',title:'title',issuing_buyer:'issuingBuyer',issue_date:'issueDate',start_date:'startDate',end_date:'endDate',ceiling_value:'ceilingValue',funded_value:'fundedValue',status:'status',scope_summary:'scopeSummary',deliverables:'deliverables',document_refs:'documentRefs'}],
 create_closeout:['closeouts',{contract_id:'contractId',closeout_status:'closeoutStatus',target_closeout_date:'targetCloseoutDate',final_deliverables_verified:'finalDeliverablesVerified',final_compliance_verified:'finalComplianceVerified',final_invoice_verified:'finalInvoiceVerified',property_return_verified:'propertyReturnVerified',final_performance_recorded:'finalPerformanceRecorded',buyer_acceptance_verified:'buyerAcceptanceVerified',closeout_documents:'closeoutDocuments',closeout_notes:'closeoutNotes'}],
 create_renewal:['renewals',{contract_id:'contractId',renewal_type:'renewalType',target_date:'targetDate',decision_deadline:'decisionDeadline',status:'status',strategy:'strategy',expansion_opportunities:'expansionOpportunities',owner_user_id:'ownerUserId',notes:'notes'}]
};
async function create(sb,user,action,p){const spec=specs[action];if(!spec)throw new Error('UNKNOWN_ACTION');const [key,map]=spec;const row={};for(const [db,src] of Object.entries(map)){if(p[src]!==undefined)row[db]=p[src]}if(action==='create_question'&&!row.submitted_by)row.submitted_by=user.id;if(action==='create_document'&&!row.uploaded_by)row.uploaded_by=user.id;if(action==='create_closeout'&&!row.contract_id)throw new Error('CONTRACT_REQUIRED');const {data,error}=await sb.from(tables[key]).insert(row).select().single();if(error)throw error;return data}
async function updateContract(sb,user,p){if(!p.contractId)throw new Error('CONTRACT_REQUIRED');const allowed=['contract_status','contract_number','title','contract_type','start_date','end_date','option_years','next_option_date','recompete_date','awarded_value','obligated_value','funded_value','ceiling_value','payment_terms','scope_summary','performance_requirements','reporting_requirements','compliance_requirements','deliverables','key_contacts','contract_documents','performance_score','renewal_strategy','expansion_opportunities','owner_user_id','closeout_status','last_performance_review_date','owner_notes'];const row={};for(const k of allowed)if(p[k]!==undefined)row[k]=p[k];const {data,error}=await sb.from('dd_contracts').update(row).eq('id',p.contractId).select().single();if(error)throw error;return data}
export default async function handler(req,res){try{const ctx=await authenticatePortalRequest(req);if(ctx.error)return fail(res,ctx.error,ctx.status);const denied=guard(ctx,res);if(denied)return denied;if(req.method==='GET')return ok(res,await snapshot(ctx.supabase));if(req.method!=='POST')return fail(res,'Method not allowed',405);const {action,...p}=req.body||{};if(action==='update_contract')return ok(res,{contract:await updateContract(ctx.supabase,ctx.user,p)});if(specs[action])return ok(res,{record:await create(ctx.supabase,ctx.user,action,p)});return fail(res,'Unknown contracting-period action');}catch(e){return fail(res,e?.message||'Contracting-period operation failed.',500)}}
