import React,{useEffect,useMemo,useState} from 'react';
import RequireStaffAuth from '../../components/auth/RequireStaffAuth.jsx';
import {supabase} from '../../lib/supabaseClient.js';

const STAGES=['RESEARCH','QUALIFIED','PURSUIT','PROPOSAL','SUBMITTED','AWARDED','CONTRACT_ACTIVE','PERFORMANCE','RENEWAL_RECOMPETE','CLOSED'];
const PATHS=['Federal Prime','Federal Subcontract','State Prime','County/Municipal Prime','Public Authority','Education','Healthcare/Institutional','Teaming','Vendor/Supplier','Other'];
const input={width:'100%',padding:10,border:'1px solid #dfd1b5',borderRadius:9,background:'#fff'};
function Field({label,value,onChange,placeholder,type='text'}){return <label style={{display:'grid',gap:5,fontWeight:700,fontSize:13}}>{label}<input type={type} value={value||''} onChange={e=>onChange(e.target.value)} placeholder={placeholder} style={input}/></label>}
function ContractAcquisition(){
 const [data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState(''),[stage,setStage]=useState('ALL');
 const [form,setForm]=useState({title:'',buyerName:'',sourceUrl:'',solicitationNumber:'',naicsCode:'561720',pscCode:'S201',procurementPath:'State Prime',responseDeadline:'',estimatedValue:'',contractCeiling:'',setAside:'',sourceAuthority:'Georgia Procurement Registry / authoritative source',researchNotes:''});
 const [busy,setBusy]=useState(false);
 const load=async()=>{setLoading(true);setError('');const {data:a}=await supabase.auth.getSession();if(!a.session){setError('Staff session required.');setLoading(false);return}const r=await fetch('/api/contract-acquisition',{headers:{Authorization:`Bearer ${a.session.access_token}`}});const b=await r.json();if(!r.ok||!b.success)setError(b.error||'Acquisition data could not be loaded.');else setData(b);setLoading(false)};
 useEffect(()=>{load()},[]);
 const act=async(action,payload)=>{setBusy(true);setError('');setMessage('');const {data:a}=await supabase.auth.getSession();const r=await fetch('/api/contract-acquisition',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${a.session.access_token}`},body:JSON.stringify({action,...payload})});const b=await r.json();if(!r.ok||!b.success)setError(b.error||'Action failed.');else{setMessage('Acquisition record updated.');await load()}setBusy(false)};
 const set=(k,v)=>setForm(x=>({...x,[k]:v}));
 const opportunities=useMemo(()=>stage==='ALL'?(data?.opportunities||[]):(data?.opportunities||[]).filter(x=>x.stage===stage),[data,stage]);
 const counts=STAGES.reduce((a,s)=>({...a,[s]:(data?.opportunities||[]).filter(x=>x.stage===s).length}),{});
 const openPursuitIds=new Set((data?.pursuits||[]).map(x=>x.opportunity_id));
 return <main style={{minHeight:'100vh',background:'#fffaf1',color:'#302226',padding:'28px 18px 60px'}}><div style={{maxWidth:1250,margin:'0 auto'}}>
  <header style={{display:'flex',justifyContent:'space-between',gap:20,flexWrap:'wrap',marginBottom:22}}><div><div style={{fontSize:12,letterSpacing:2,fontWeight:900,color:'#8b6b1f'}}>DANI DECLARES CONTRACTING OPERATING SYSTEM</div><h1 style={{margin:'5px 0',fontSize:'clamp(32px,5vw,50px)',color:'#5a1624'}}>Contract Acquisition</h1><p style={{maxWidth:760,color:'#6d5b60',lineHeight:1.55}}>Research-qualified opportunities become controlled pursuits, proposals, awards and contracts. This layer does not replace Airtable research; it receives verified acquisition work and connects winning work to fulfillment.</p></div><a href="/portal/operations" style={{alignSelf:'start',padding:'11px 14px',borderRadius:10,background:'#5a1624',color:'#fff',textDecoration:'none',fontWeight:800}}>Operations Console →</a></header>
  {error&&<div style={{padding:12,marginBottom:15,borderRadius:10,background:'#fff0f0',color:'#8a1d2d'}}>{error}</div>}{message&&<div style={{padding:12,marginBottom:15,borderRadius:10,background:'#edf8ef',color:'#276b35'}}>{message}</div>}
  <section style={{display:'grid',gridTemplateColumns:'minmax(0,1.5fr) minmax(300px,.7fr)',gap:18}}>
   <div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(115px,1fr))',gap:8,marginBottom:16}}>{[['ALL',(data?.opportunities||[]).length],...STAGES.map(s=>[s,counts[s]])].map(([s,n])=><button key={s} onClick={()=>setStage(s)} style={{padding:10,borderRadius:9,border:stage===s?'2px solid #6b1f2b':'1px solid #dfd1b5',background:stage===s?'#f7edd4':'#fff',fontWeight:800}}><div style={{fontSize:11}}>{s.replaceAll('_',' ')}</div><div style={{fontSize:20,color:'#5a1624'}}>{n}</div></button>)}</div>
    <div style={{background:'#fff',border:'1px solid #e2d6bf',borderRadius:15,padding:16}}><h2 style={{marginTop:0,color:'#5a1624'}}>Opportunity pipeline</h2>{loading?<p>Loading acquisition ledger…</p>:opportunities.length?opportunities.map(o=><div key={o.id} style={{borderTop:'1px solid #eee3d0',padding:'14px 0',display:'grid',gap:8}}><div style={{display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap'}}><div><strong style={{fontSize:17}}>{o.title}</strong><div style={{fontSize:12,color:'#78666b'}}>{o.public_reference} · {o.buyer_name||'Buyer not yet identified'} · {o.naics_code||'NAICS n/a'} / {o.psc_code||'PSC n/a'}</div></div><span style={{fontSize:11,fontWeight:900,padding:'5px 8px',borderRadius:99,background:'#f3e9cf'}}>{o.stage.replaceAll('_',' ')}</span></div><div style={{fontSize:13,color:'#5e4d52'}}>Deadline: {o.response_deadline?new Date(o.response_deadline).toLocaleString():'Not set'} · Fit: {o.fit_status} · Evidence: {o.evidence_status} · Path: {o.procurement_path}</div><div style={{display:'flex',gap:7,flexWrap:'wrap'}}>{o.stage==='RESEARCH'&&<button disabled={busy} onClick={()=>act('update_opportunity_stage',{opportunityId:o.id,stage:'QUALIFIED',fitStatus:'STRONG',qualificationNotes:'Qualified for controlled pursuit review; verify solicitation and readiness before submission.'})}>Mark Qualified</button>}{['QUALIFIED','RESEARCH'].includes(o.stage)&&!openPursuitIds.has(o.id)&&<button disabled={busy} onClick={()=>act('open_pursuit',{opportunityId:o.id})}>Open Pursuit</button>}{o.stage==='PURSUIT'&&<button disabled={busy} onClick={()=>act('create_proposal',{pursuitId:(data?.pursuits||[]).find(p=>p.opportunity_id===o.id)?.id,title:o.title,submissionDeadline:o.response_deadline})}>Create Proposal Draft</button>}{o.stage==='PROPOSAL'&&<button disabled={busy} onClick={()=>act('update_opportunity_stage',{opportunityId:o.id,stage:'SUBMITTED'})}>Mark Submitted</button>}</div></div>):<p>No opportunities in this stage.</p>}</div>
    <div style={{marginTop:18,background:'#fff',border:'1px solid #e2d6bf',borderRadius:15,padding:16}}><h2 style={{marginTop:0,color:'#5a1624'}}>Pursuits & proposals</h2>{(data?.pursuits||[]).slice(0,12).map(p=><div key={p.id} style={{borderTop:'1px solid #eee3d0',padding:'12px 0'}}><strong>{p.public_reference}</strong><div style={{fontSize:13}}>{p.dd_contract_opportunities?.title||'Opportunity'} · {p.pursuit_stage} · {p.bid_no_bid}</div><small>{p.next_action||'No next action recorded.'}</small></div>)}{!(data?.pursuits||[]).length&&<p>No active pursuits yet.</p>}</div>
   </div>
   <aside style={{alignSelf:'start',display:'grid',gap:15}}><div style={{background:'#5a1624',color:'#fff',borderRadius:15,padding:18}}><h2 style={{marginTop:0}}>Add verified opportunity</h2><p style={{fontSize:13,lineHeight:1.5,color:'#f1e3e5'}}>Use this only after research has been verified. Airtable remains the research layer; this is the controlled runtime pursuit ledger.</p><div style={{display:'grid',gap:10}}><Field label="Opportunity title" value={form.title} onChange={v=>set('title',v)} placeholder="Solicitation / contract title"/><Field label="Buyer" value={form.buyerName} onChange={v=>set('buyerName',v)} placeholder="Agency / organization"/><Field label="Solicitation number" value={form.solicitationNumber} onChange={v=>set('solicitationNumber',v)} /><Field label="Source URL" value={form.sourceUrl} onChange={v=>set('sourceUrl',v)} placeholder="Authoritative procurement source"/><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8}}><Field label="NAICS" value={form.naicsCode} onChange={v=>set('naicsCode',v)}/><Field label="PSC" value={form.pscCode} onChange={v=>set('pscCode',v)}/></div><label style={{display:'grid',gap:5,fontSize:13,fontWeight:700}}>Procurement path<select value={form.procurementPath} onChange={e=>set('procurementPath',e.target.value)} style={input}>{PATHS.map(x=><option key={x}>{x}</option>)}</select></label><Field label="Response deadline" value={form.responseDeadline} onChange={v=>set('responseDeadline',v)} type="datetime-local"/><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8}}><Field label="Estimated value" value={form.estimatedValue} onChange={v=>set('estimatedValue',v)} type="number"/><Field label="Ceiling" value={form.contractCeiling} onChange={v=>set('contractCeiling',v)} type="number"/></div><Field label="Set-aside" value={form.setAside} onChange={v=>set('setAside',v)}/><label style={{display:'grid',gap:5,fontSize:13,fontWeight:700}}>Research notes<textarea value={form.researchNotes} onChange={e=>set('researchNotes',e.target.value)} rows={4} style={{...input,resize:'vertical'}}/></label><button disabled={busy||!form.title} onClick={()=>act('create_opportunity',form)} style={{padding:12,border:0,borderRadius:10,background:'#efce72',color:'#35161d',fontWeight:900}}>Create controlled opportunity</button></div></div>
   <div style={{background:'#fff',border:'1px solid #e2d6bf',borderRadius:15,padding:16}}><h3 style={{marginTop:0,color:'#5a1624'}}>Control gates</h3><ul style={{paddingLeft:18,lineHeight:1.6,fontSize:13}}><li>Research is not authorization to bid.</li><li>Qualification precedes pursuit.</li><li>Proposal drafts are versioned.</li><li>Award creates the contract record.</li><li>Contracts can attach to jobs, work orders and invoices.</li><li>Pricing authority remains upstream.</li></ul></div></aside>
  </section></div></main>
}
export default function ContractAcquisitionPage(){return <RequireStaffAuth><ContractAcquisition/></RequireStaffAuth>}
