import React,{useEffect,useMemo,useState} from 'react';
import RequireStaffAuth from '../../components/auth/RequireStaffAuth.jsx';
import {supabase} from '../../lib/supabaseClient.js';
const STAGES=['RESEARCH','QUALIFIED','PURSUIT','PROPOSAL','SUBMITTED','AWARDED','CONTRACT_ACTIVE','PERFORMANCE','RENEWAL_RECOMPETE','CLOSED'];
const PATHS=['Federal Prime','Federal Subcontract','State Prime','County/Municipal Prime','Public Authority','Education','Healthcare/Institutional','Teaming','Vendor/Supplier','Other'];
const GATE_FIELDS=[['solicitation_verified','Solicitation verified'],['deadline_verified','Deadline verified'],['pricing_approved','Pricing approved'],['proposal_sections_complete','Proposal sections complete'],['compliance_complete','Compliance complete'],['required_attachments_complete','Required attachments complete'],['submission_method_verified','Submission method verified'],['final_qa_complete','Final QA complete'],['authorized_to_submit','Authorized to submit']];
const input={width:'100%',padding:10,border:'1px solid #dfd1b5',borderRadius:9,background:'#fff',boxSizing:'border-box'};
function Field({label,value,onChange,placeholder,type='text'}){return <label style={{display:'grid',gap:5,fontWeight:700,fontSize:13}}>{label}<input type={type} value={value??''} onChange={e=>onChange(e.target.value)} placeholder={placeholder} style={input}/></label>}
function TextArea({label,value,onChange,rows=5}){return <label style={{display:'grid',gap:5,fontWeight:700,fontSize:13}}>{label}<textarea value={value??''} onChange={e=>onChange(e.target.value)} rows={rows} style={{...input,resize:'vertical'}}/></label>}
function Acquisition(){
 const [data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState(''),[stage,setStage]=useState('ALL'),[selected,setSelected]=useState(null),[busy,setBusy]=useState(false),[workspace,setWorkspace]=useState('PIPELINE');
 const [form,setForm]=useState({title:'',buyerName:'',sourceUrl:'',solicitationNumber:'',naicsCode:'561720',pscCode:'S201',procurementPath:'State Prime',responseDeadline:'',estimatedValue:'',contractCeiling:'',setAside:'',sourceAuthority:'',researchNotes:''});
 const [proposal,setProposal]=useState({title:'',technicalApproach:'',managementApproach:'',qualityControlPlan:'',staffingPlan:'',equipmentPlan:'',pastPerformance:'',referencesText:''});
 const load=async()=>{setLoading(true);setError('');try{const {data:a}=await supabase.auth.getSession();if(!a.session)throw new Error('Staff session required.');const r=await fetch('/api/contract-acquisition',{headers:{Authorization:`Bearer ${a.session.access_token}`}});const b=await r.json();if(!r.ok||!b.success)throw new Error(b.error||'Acquisition data could not be loaded.');setData(b)}catch(e){setError(e.message)}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const act=async(action,payload)=>{setBusy(true);setError('');setMessage('');try{const {data:a}=await supabase.auth.getSession();const r=await fetch('/api/contract-acquisition',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${a.session.access_token}`},body:JSON.stringify({action,...payload})});const b=await r.json();if(!r.ok||!b.success)throw new Error(b.error||'Action failed.');setMessage('Acquisition record updated.');await load();return b}catch(e){setError(e.message);return null}finally{setBusy(false)}};
 const opportunities=useMemo(()=>stage==='ALL'?(data?.opportunities||[]):(data?.opportunities||[]).filter(x=>x.stage===stage),[data,stage]);
 const counts=STAGES.reduce((a,s)=>({...a,[s]:(data?.opportunities||[]).filter(x=>x.stage===s).length}),{});
 const pursuits=data?.pursuits||[],proposals=data?.proposals||[],gates=data?.submissionGates||[],quals=data?.qualifications||[],contracts=data?.contracts||[];
 const selectedOpp=selected?.type==='opp'?(data?.opportunities||[]).find(x=>x.id===selected.id):null;
 const selectedPursuit=selected?.pursuitId?pursuits.find(x=>x.id===selected.pursuitId):null;
 const selectedProposal=selected?.proposalId?proposals.find(x=>x.id===selected.proposalId):null;
 const selectedGate=selectedProposal?gates.find(x=>x.proposal_id===selectedProposal.id):null;
 const selectedQuals=selectedPursuit?quals.filter(x=>x.pursuit_id===selectedPursuit.id):[];
 const openPursuitIds=new Set(pursuits.map(x=>x.opportunity_id));
 const card={background:'#fff',border:'1px solid #e2d6bf',borderRadius:15,padding:16};
 const openPursuit=o=>{const p=pursuits.find(x=>x.opportunity_id===o.id);if(p){setSelected({pursuitId:p.id});setWorkspace('QUALIFICATION')}else{setSelected({type:'opp',id:o.id});setWorkspace('DETAIL')}};
 return <main style={{minHeight:'100vh',background:'#fffaf1',color:'#302226',padding:'28px 18px 60px'}}><div style={{maxWidth:1350,margin:'0 auto'}}>
 <header style={{display:'flex',justifyContent:'space-between',gap:20,flexWrap:'wrap',marginBottom:18}}><div><div style={{fontSize:12,letterSpacing:2,fontWeight:900,color:'#8b6b1f'}}>DANI DECLARES CONTRACTING OPERATING SYSTEM</div><h1 style={{margin:'5px 0',fontSize:'clamp(32px,5vw,50px)',color:'#5a1624'}}>Contract Acquisition</h1><p style={{maxWidth:850,color:'#6d5b60',lineHeight:1.55}}>Controlled path from verified market intelligence to pursuit, proposal, submission, award, contract performance and recompete. Airtable remains research; this portal is execution.</p></div><a href="/portal/operations" style={{alignSelf:'start',padding:'11px 14px',borderRadius:10,background:'#5a1624',color:'#fff',textDecoration:'none',fontWeight:800}}>Operations Console →</a></header>
 {error&&<div style={{padding:12,marginBottom:12,borderRadius:10,background:'#fff0f0',color:'#8a1d2d'}}>{error}</div>}{message&&<div style={{padding:12,marginBottom:12,borderRadius:10,background:'#edf8ef',color:'#276b35'}}>{message}</div>}
 <nav style={{display:'flex',gap:7,flexWrap:'wrap',marginBottom:15}}>{[['PIPELINE','Pipeline'],['QUALIFICATION','Qualification'],['PROPOSAL','Proposal'],['SUBMISSION','Submission Gate'],['CONTRACTS','Contracts']].map(([k,v])=><button key={k} onClick={()=>setWorkspace(k)} style={{padding:'10px 13px',borderRadius:9,border:workspace===k?'2px solid #6b1f2b':'1px solid #dfd1b5',background:workspace===k?'#f7edd4':'#fff',fontWeight:800}}>{v}</button>)}</nav>
 {workspace==='PIPELINE'&&<section style={{display:'grid',gridTemplateColumns:'minmax(0,1.6fr) minmax(310px,.7fr)',gap:18}}><div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(105px,1fr))',gap:7,marginBottom:14}}>{[['ALL',(data?.opportunities||[]).length],...STAGES.map(s=>[s,counts[s]])].map(([s,n])=><button key={s} onClick={()=>setStage(s)} style={{padding:9,borderRadius:9,border:stage===s?'2px solid #6b1f2b':'1px solid #dfd1b5',background:stage===s?'#f7edd4':'#fff',fontWeight:800}}><div style={{fontSize:10}}>{s.replaceAll('_',' ')}</div><div style={{fontSize:19,color:'#5a1624'}}>{n}</div></button>)}</div><div style={card}><h2 style={{marginTop:0,color:'#5a1624'}}>Opportunity pipeline</h2>{loading?<p>Loading acquisition ledger…</p>:opportunities.length?opportunities.map(o=><div key={o.id} style={{borderTop:'1px solid #eee3d0',padding:'14px 0',display:'grid',gap:8}}><div style={{display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap'}}><div><button onClick={()=>{setSelected({type:'opp',id:o.id});setWorkspace('DETAIL')}} style={{border:0,background:'none',padding:0,textAlign:'left',fontSize:17,fontWeight:800,color:'#302226',cursor:'pointer'}}>{o.title}</button><div style={{fontSize:12,color:'#78666b'}}>{o.public_reference} · {o.buyer_name||'Buyer not identified'} · {o.naics_code||'NAICS n/a'} / {o.psc_code||'PSC n/a'}</div></div><span style={{fontSize:11,fontWeight:900,padding:'5px 8px',borderRadius:99,background:'#f3e9cf'}}>{o.stage.replaceAll('_',' ')}</span></div><div style={{fontSize:13,color:'#5e4d52'}}>Deadline: {o.response_deadline?new Date(o.response_deadline).toLocaleString():'Not set'} · Fit: {o.fit_status} · Evidence: {o.evidence_status} · Path: {o.procurement_path}</div><div style={{display:'flex',gap:7,flexWrap:'wrap'}}>{o.stage==='RESEARCH'&&<button disabled={busy} onClick={()=>act('update_opportunity_stage',{opportunityId:o.id,stage:'QUALIFIED',fitStatus:'STRONG',qualificationNotes:'Qualified for controlled pursuit review.'})}>Mark Qualified</button>}{o.stage==='QUALIFIED'&&!openPursuitIds.has(o.id)&&<button disabled={busy} onClick={()=>act('open_pursuit',{opportunityId:o.id})}>Open Pursuit</button>}{o.stage==='PURSUIT'&&<button disabled={busy} onClick={()=>{const p=pursuits.find(x=>x.opportunity_id===o.id);setSelected({pursuitId:p?.id});setWorkspace('QUALIFICATION')}}>Open Qualification</button>}{o.stage==='PROPOSAL'&&<button disabled={busy} onClick={()=>{const p=pursuits.find(x=>x.opportunity_id===o.id),pr=proposals.filter(x=>x.pursuit_id===p?.id).sort((a,b)=>b.version_number-a.version_number)[0];setSelected({pursuitId:p?.id,proposalId:pr?.id});setWorkspace('PROPOSAL')}}>Open Proposal</button>}{o.stage==='SUBMITTED'&&<button onClick={()=>setWorkspace('SUBMISSION')}>Submission Tracker</button>}</div></div>):<p>No opportunities in this stage.</p>}</div></div>
 <aside style={{display:'grid',gap:15,alignSelf:'start'}}><div style={{...card,background:'#5a1624',color:'#fff'}}><h2 style={{marginTop:0}}>Add verified opportunity</h2><p style={{fontSize:13,lineHeight:1.5,color:'#f1e3e5'}}>Only enter opportunities after research has been verified. The source becomes evidence; this runtime record becomes the controlled acquisition object.</p><div style={{display:'grid',gap:10}}><Field label="Opportunity title" value={form.title} onChange={v=>setForm(x=>({...x,title:v}))}/><Field label="Buyer" value={form.buyerName} onChange={v=>setForm(x=>({...x,buyerName:v}))}/><Field label="Solicitation number" value={form.solicitationNumber} onChange={v=>setForm(x=>({...x,solicitationNumber:v}))}/><Field label="Source URL" value={form.sourceUrl} onChange={v=>setForm(x=>({...x,sourceUrl:v}))}/><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8}}><Field label="NAICS" value={form.naicsCode} onChange={v=>setForm(x=>({...x,naicsCode:v}))}/><Field label="PSC" value={form.pscCode} onChange={v=>setForm(x=>({...x,pscCode:v}))}/></div><label style={{display:'grid',gap:5,fontSize:13,fontWeight:700}}>Procurement path<select value={form.procurementPath} onChange={e=>setForm(x=>({...x,procurementPath:e.target.value}))} style={input}>{PATHS.map(x=><option key={x}>{x}</option>)}</select></label><Field label="Response deadline" value={form.responseDeadline} onChange={v=>setForm(x=>({...x,responseDeadline:v}))} type="datetime-local"/><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8}}><Field label="Estimated value" value={form.estimatedValue} onChange={v=>setForm(x=>({...x,estimatedValue:v}))} type="number"/><Field label="Ceiling" value={form.contractCeiling} onChange={v=>setForm(x=>({...x,contractCeiling:v}))} type="number"/></div><Field label="Set-aside" value={form.setAside} onChange={v=>setForm(x=>({...x,setAside:v}))}/><TextArea label="Research notes" value={form.researchNotes} onChange={v=>setForm(x=>({...x,researchNotes:v}))} rows={4}/><button disabled={busy||!form.title} onClick={async()=>{const r=await act('create_opportunity',form);if(r)setForm({...form,title:'',buyerName:'',sourceUrl:'',solicitationNumber:'',responseDeadline:'',estimatedValue:'',contractCeiling:'',setAside:'',researchNotes:''})}} style={{padding:12,border:0,borderRadius:10,background:'#efce72',color:'#35161d',fontWeight:900}}>Create controlled opportunity</button></div></div></aside></section>}
 {workspace==='DETAIL'&&selectedOpp&&<section style={card}><button onClick={()=>setWorkspace('PIPELINE')}>← Pipeline</button><h2 style={{color:'#5a1624'}}>{selectedOpp.title}</h2><p><b>{selectedOpp.public_reference}</b> · {selectedOpp.buyer_name||'Buyer not identified'} · {selectedOpp.procurement_path}</p><p>Evidence: <b>{selectedOpp.evidence_status}</b> · Fit: <b>{selectedOpp.fit_status}</b> · Deadline: {selectedOpp.response_deadline?new Date(selectedOpp.response_deadline).toLocaleString():'Not set'}</p><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:10}}><div><b>Solicitation</b><p>{selectedOpp.solicitation_number||'Not recorded'}</p></div><div><b>NAICS / PSC</b><p>{selectedOpp.naics_code||'—'} / {selectedOpp.psc_code||'—'}</p></div><div><b>Value / ceiling</b><p>{selectedOpp.estimated_value??'—'} / {selectedOpp.contract_ceiling??'—'}</p></div><div><b>Set-aside</b><p>{selectedOpp.set_aside||'Not recorded'}</p></div></div><TextArea label="Research notes" value={selectedOpp.research_notes} onChange={()=>{}} rows={5}/><div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:12}}>{selectedOpp.source_url&&<a href={selectedOpp.source_url} target="_blank" rel="noreferrer">Open source ↗</a>}{selectedOpp.stage==='RESEARCH'&&<button disabled={busy} onClick={()=>act('update_opportunity_stage',{opportunityId:selectedOpp.id,stage:'QUALIFIED',fitStatus:'STRONG'})}>Mark Qualified</button>}{selectedOpp.stage==='QUALIFIED'&&<button disabled={busy} onClick={()=>act('open_pursuit',{opportunityId:selectedOpp.id})}>Open Pursuit</button>}</div></section>}
 {workspace==='QUALIFICATION'&&<section style={card}><button onClick={()=>setWorkspace('PIPELINE')}>← Pipeline</button><h2 style={{color:'#5a1624'}}>Qualification workspace</h2>{!selectedPursuit?<p>Select a qualified opportunity and open its pursuit.</p>:<><p><b>{selectedPursuit.public_reference}</b> · {selectedPursuit.dd_contract_opportunities?.title||'Opportunity'}</p><div style={{display:'grid',gap:9}}>{selectedQuals.map(q=><div key={q.id} style={{border:'1px solid #e2d6bf',borderRadius:10,padding:12,display:'grid',gridTemplateColumns:'1fr auto',gap:8,alignItems:'center'}}><div><b>{q.requirement_name}</b><div style={{fontSize:12,color:'#78666b'}}>{q.category} · {q.status}</div></div><select value={q.status} disabled={busy} onChange={e=>act('update_qualification',{itemId:q.id,status:e.target.value})} style={{...input,width:170}}><option>OPEN</option><option>IN_PROGRESS</option><option>COMPLETE</option><option>NOT_APPLICABLE</option></select></div>)}</div><div style={{marginTop:15,padding:12,borderRadius:10,background:selectedQuals.filter(x=>x.required&&x.status!=='COMPLETE').length?'#fff4e5':'#edf8ef'}}><b>{selectedQuals.filter(x=>x.required&&x.status!=='COMPLETE').length?`${selectedQuals.filter(x=>x.required&&x.status!=='COMPLETE').length} required checks remain.`:'Qualification checklist complete.'}</b></div>{selectedQuals.length&&selectedQuals.every(x=>!x.required||x.status==='COMPLETE')&&<button disabled={busy} style={{marginTop:12}} onClick={()=>{setProposal({title:selectedPursuit.dd_contract_opportunities?.title||'',technicalApproach:'',managementApproach:'',qualityControlPlan:'',staffingPlan:'',equipmentPlan:'',pastPerformance:'',referencesText:''});setWorkspace('PROPOSAL')}}>Open Proposal Workspace</button>}</>}</section>}
 {workspace==='PROPOSAL'&&<section style={{display:'grid',gridTemplateColumns:'minmax(0,1.3fr) minmax(300px,.7fr)',gap:18}}><div style={card}><button onClick={()=>setWorkspace('QUALIFICATION')}>← Qualification</button><h2 style={{color:'#5a1624'}}>Proposal workspace</h2>{!selectedPursuit?<p>Select a pursuit first.</p>:<div style={{display:'grid',gap:11}}><Field label="Proposal title" value={proposal.title||selectedProposal?.proposal_title} onChange={v=>setProposal(x=>({...x,title:v}))}/><TextArea label="Technical approach" value={proposal.technicalApproach||selectedProposal?.technical_approach} onChange={v=>setProposal(x=>({...x,technicalApproach:v}))}/><TextArea label="Management approach" value={proposal.managementApproach||selectedProposal?.management_approach} onChange={v=>setProposal(x=>({...x,managementApproach:v}))}/><TextArea label="Quality control plan" value={proposal.qualityControlPlan||selectedProposal?.quality_control_plan} onChange={v=>setProposal(x=>({...x,qualityControlPlan:v}))}/><TextArea label="Staffing plan" value={proposal.staffingPlan||selectedProposal?.staffing_plan} onChange={v=>setProposal(x=>({...x,staffingPlan:v}))}/><TextArea label="Equipment plan" value={proposal.equipmentPlan||selectedProposal?.equipment_plan} onChange={v=>setProposal(x=>({...x,equipmentPlan:v}))}/><TextArea label="Past performance" value={proposal.pastPerformance||selectedProposal?.past_performance} onChange={v=>setProposal(x=>({...x,pastPerformance:v}))}/><TextArea label="References" value={proposal.referencesText||selectedProposal?.references_text} onChange={v=>setProposal(x=>({...x,referencesText:v}))}/>{!selectedProposal&&<button disabled={busy} onClick={async()=>{const r=await act('create_proposal',{pursuitId:selectedPursuit.id,title:proposal.title,submissionDeadline:selectedPursuit.target_submission_at,...proposal});if(r)setSelected(x=>({...x,proposalId:r.proposal.id}))}}>Create proposal draft</button>}{selectedProposal&&<button onClick={()=>setWorkspace('SUBMISSION')}>Open Submission Gate →</button>}</div>}</div><aside style={{...card,alignSelf:'start'}}><h3 style={{marginTop:0,color:'#5a1624'}}>Proposal control</h3><p style={{fontSize:13,lineHeight:1.6}}>Drafting does not bypass pricing authority, compliance requirements, or the submission gate.</p></aside></section>}
 {workspace==='SUBMISSION'&&<section style={card}><button onClick={()=>setWorkspace('PROPOSAL')}>← Proposal</button><h2 style={{color:'#5a1624'}}>Submission gate</h2>{!selectedProposal?<p>Select a proposal first.</p>:<><p><b>{selectedProposal.public_reference}</b> · Version {selectedProposal.version_number} · {selectedProposal.proposal_status}</p><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(250px,1fr))',gap:9}}>{GATE_FIELDS.map(([key,label])=><label key={key} style={{border:'1px solid #e2d6bf',borderRadius:10,padding:12,display:'flex',gap:10,alignItems:'center',fontWeight:700}}><input type="checkbox" checked={!!selectedGate?.[key]} disabled={busy} onChange={e=>{const next={};GATE_FIELDS.forEach(([k])=>next[k]=k===key?e.target.checked:!!selectedGate?.[k]);act('update_submission_gate',{proposalId:selectedProposal.id,...next})}}/>{label}</label>)}</div><div style={{marginTop:15,padding:13,borderRadius:10,background:selectedGate?.status==='READY'?'#edf8ef':'#fff4e5'}}><b>{selectedGate?.status==='READY'?'READY TO SUBMIT':'BLOCKED'}</b>{selectedGate?.blocking_notes&&<div>{selectedGate.blocking_notes}</div>}</div>{selectedGate?.status==='READY'&&<button disabled={busy} style={{marginTop:12}} onClick={()=>act('submit_proposal',{proposalId:selectedProposal.id})}>Submit Proposal</button>}</>}</section>}
 {workspace==='CONTRACTS'&&<section style={card}><h2 style={{color:'#5a1624'}}>Award & contract performance</h2>{contracts.length?<div style={{display:'grid',gap:10}}>{contracts.map(c=><div key={c.id} style={{border:'1px solid #e2d6bf',borderRadius:10,padding:14}}><b>{c.public_reference}</b> · {c.title}<div style={{fontSize:13,color:'#6d5b60'}}>Status: {c.contract_status} · Contract #: {c.contract_number||'Not recorded'} · End: {c.end_date||'Not recorded'} · Recompete: {c.recompete_date||'Not recorded'}</div></div>)}</div>:<p>No active contracts yet. Awards become contracts through controlled activation.</p>}</section>}
 </div></main>
}
export default function ContractAcquisitionPage(){return <RequireStaffAuth><Acquisition/></RequireStaffAuth>}
