import React, { useEffect, useMemo, useState } from 'react';
import RequireStaffAuth from '../../components/auth/RequireStaffAuth.jsx';
import { supabase } from '../../lib/supabaseClient.js';
import { statusLabel } from './providerWorkspaceShared.jsx';
import './OperationsConsolePage.css';

const QUEUES=[{key:'sales',label:'Sales Queue',description:'Work the acquisition board: inbound, warm, revisit and partner lanes toward the weekly collection target.'},{key:'requests',label:'Intake & CRM',description:'Route new B2C, B2B and B2G requests.'},{key:'jobs',label:'Jobs & Dispatch',description:'Run priced work through dispatch and field execution.'},{key:'schedule',label:'Schedule',description:'Appointments, owner booking requests and provider availability.'},{key:'providers',label:'Provider Network',description:'Capabilities, coverage and assignment readiness.'},{key:'changes',label:'Change Orders',description:'Approve isolated commercial deltas without touching the base estimate.'},{key:'evidence',label:'Evidence & QA',description:'Review field evidence and completion gates.'},{key:'payments',label:'Payments & Accounting',description:'Reconcile payment events against frozen commercial records.'}];
const SALES_LANE_ORDER=['INBOUND','WARM','REVISIT_CALLABLE','REVISIT_ROUTING','PARTNER','EMAIL_ONLY','REVISIT_NOT_CALLABLE','SCREEN_ONLY'];
const SALES_LANE_LABELS={INBOUND:'🔥 Inbound',WARM:'🟠 Warm',REVISIT_CALLABLE:'🟡 Revisit — Callable',REVISIT_ROUTING:'🟡 Revisit — Company Routing',PARTNER:'🟢 Partner',EMAIL_ONLY:'📧 Email Only',REVISIT_NOT_CALLABLE:'⚪ Revisit — Not Yet Callable',SCREEN_ONLY:'⚪ Screen Only'};
const SALES_DISPOSITIONS=['NOT_CONTACTED','NO_ANSWER','VOICEMAIL','RECEPTIONIST','WRONG_PERSON','DECISION_MAKER_REACHED','INTERESTED','NEEDS_INFO','QUOTE_REQUESTED','READY_TO_BUY','PAYMENT_SENT','PAYMENT_SUCCEEDED','CALL_BACK_LATER','NOT_INTERESTED','EXISTING_VENDOR_REVISIT','DO_NOT_CONTACT'];
const WEEKLY_TARGET=1200;
const CHANNELS=['B2C','B2B-APT','B2B-RE','B2B','B2B2C','B2G'];
function Stat({label,value,detail}){return <div className="ops-stat"><span>{label}</span><strong>{value}</strong><small>{detail}</small></div>}
function SalesRow({row,onSave}){
 const [disposition,setDisposition]=useState(row.disposition);
 const [nextAction,setNextAction]=useState(row.next_action||'');
 const [nextActionDate,setNextActionDate]=useState(row.next_action_date||'');
 const [quotedAmount,setQuotedAmount]=useState(row.quoted_amount==null?'':row.quoted_amount);
 const [amountCollected,setAmountCollected]=useState(row.amount_collected||0);
 const dirty=disposition!==row.disposition||nextAction!==(row.next_action||'')||nextActionDate!==(row.next_action_date||'')||String(quotedAmount)!==String(row.quoted_amount==null?'':row.quoted_amount)||String(amountCollected)!==String(row.amount_collected||0);
 return <div className="ops-row" style={{flexDirection:'column',alignItems:'stretch',gap:8}}>
  <div><strong>{row.contact_name}</strong>{row.company_name&&<small> · {row.company_name}</small>}{row.role_title&&<small> · {row.role_title}</small>}<br/><small>{row.phone||''}{row.phone&&row.email?' · ':''}{row.email||''}</small>{row.notes&&<div style={{fontSize:12,color:'#666',marginTop:4}}>{row.notes}</div>}</div>
  <div className="ops-actions" style={{flexWrap:'wrap',gap:8}}>
   <select value={disposition} onChange={e=>setDisposition(e.target.value)}>{SALES_DISPOSITIONS.map(d=><option key={d} value={d}>{d.replaceAll('_',' ')}</option>)}</select>
   <input type="text" placeholder="Next action" value={nextAction} onChange={e=>setNextAction(e.target.value)} style={{minWidth:160}}/>
   <input type="date" value={nextActionDate||''} onChange={e=>setNextActionDate(e.target.value)}/>
   <input type="number" placeholder="Quoted $" value={quotedAmount} onChange={e=>setQuotedAmount(e.target.value)} style={{width:90}}/>
   <input type="number" placeholder="Collected $" value={amountCollected} onChange={e=>setAmountCollected(e.target.value)} style={{width:100}}/>
   {dirty&&<button onClick={()=>onSave(row.id,{disposition,next_action:nextAction||null,next_action_date:nextActionDate||null,quoted_amount:quotedAmount===''?null:Number(quotedAmount),amount_collected:Number(amountCollected||0)})}>Save</button>}
  </div>
 </div>;
}
function OperationsConsole(){
 const [active,setActive]=useState('requests'),[data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState(''),[revealedTins,setRevealedTins]=useState({});
 const load=async()=>{setLoading(true);setError('');const {data:auth}=await supabase.auth.getSession();if(!auth.session){setError('Staff session required.');setLoading(false);return}const response=await fetch('/api/portal-operations',{headers:{Authorization:`Bearer ${auth.session.access_token}`}});const body=await response.json();if(!response.ok||!body.success){setError(body.error||'Operations data could not be loaded.');setLoading(false);return}const {data:bookingRequests,error:bookingError}=await supabase.from('dd_owner_booking_requests').select('*').order('starts_at',{ascending:true}).limit(100);if(bookingError){setError(bookingError.message);setLoading(false);return}const {data:salesQueue,error:salesError}=await supabase.from('dd_sales_queue').select('*').order('lane',{ascending:true}).order('company_name',{ascending:true});if(salesError){setError(salesError.message);setLoading(false);return}setData({...body,bookingRequests:bookingRequests||[],salesQueue:salesQueue||[]});setLoading(false)};
 useEffect(()=>{load()},[]);
 const act=async(action,payload)=>{setMessage('');setError('');const {data:auth}=await supabase.auth.getSession();if(!auth.session)return setError('Staff session required.');const response=await fetch('/api/portal-operations',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${auth.session.access_token}`},body:JSON.stringify({action,...payload})});const body=await response.json();if(!response.ok||!body.success)setError(body.error||'Operation failed.');else{setMessage('Operation completed.');await load()}};
 const updateBooking=async(id,status)=>{setMessage('');setError('');const {error:e}=await supabase.from('dd_owner_booking_requests').update({status,updated_at:new Date().toISOString()}).eq('id',id);if(e)setError(e.message);else{setMessage(`Booking request ${status.toLowerCase()}.`);await load()}};
 const revealTin=async(submissionId)=>{setError('');const reason=window.prompt('Why do you need the full TIN? (logged with this reveal)');if(reason===null)return;const {data:auth}=await supabase.auth.getSession();if(!auth.session)return setError('Staff session required.');const response=await fetch('/api/portal-operations',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${auth.session.access_token}`},body:JSON.stringify({action:'decrypt_provider_w9_tin',submissionId,reason})});const body=await response.json();if(!response.ok||!body.success)return setError(body.error||'Could not decrypt TIN.');setRevealedTins(prev=>({...prev,[submissionId]:body.tin}))};
 const updateSalesRow=async(id,patch)=>{setMessage('');setError('');const {error:e}=await supabase.from('dd_sales_queue').update({...patch,updated_at:new Date().toISOString()}).eq('id',id);if(e)setError(e.message);else{setMessage('Sales queue updated.');await load()}};
 const instantiateFulfillment=async(requestId)=>{setMessage('');setError('');const {data:auth}=await supabase.auth.getSession();if(!auth.session)return setError('Staff session required.');const response=await fetch('/api/portal-fulfillment',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${auth.session.access_token}`},body:JSON.stringify({requestId})});const body=await response.json();if(!response.ok||!body.success)setError(body.error||'Fulfillment could not be instantiated.');else{setMessage(`Fulfillment instantiated: ${body.fulfillment.work_order_id} → ${body.fulfillment.job_id}`);await load()}};
 const routeDispatch=async(jobId)=>{setMessage('');setError('');const {data:auth}=await supabase.auth.getSession();if(!auth.session)return setError('Staff session required.');const response=await fetch('/api/portal-dispatch',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${auth.session.access_token}`},body:JSON.stringify({jobId})});const body=await response.json();if(!response.ok||!body.success)setError(body.error||'Dispatch routing failed.');else{setMessage(body.routing?.offer_status==='OFFERED'?'Provider offer created through the canonical dispatch resolver.':`Dispatch held: ${body.routing?.routing_reason||body.routing?.offer_status||'No eligible provider.'}`);await load()}};
 const counts={sales:data?.salesQueue?.length||0,requests:data?.requests?.length||0,jobs:data?.jobs?.length||0,schedule:(data?.appointments?.length||0)+(data?.bookingRequests?.length||0),providers:data?.providers?.length||0,changes:data?.changes?.length||0,evidence:data?.evidence?.length||0,payments:data?.payments?.length||0};
 const salesCollected=(data?.salesQueue||[]).reduce((sum,row)=>sum+Number(row.amount_collected||0),0);
 const salesByLane=useMemo(()=>{const groups={};for(const row of (data?.salesQueue||[])){(groups[row.lane]=groups[row.lane]||[]).push(row)}return groups},[data]);
 const channelCounts=CHANNELS.reduce((acc,channel)=>({...acc,[channel]:(data?.requests||[]).filter(row=>row.channel_type===channel||row.property_details?.operationsRouting?.channelType===channel).length}),{});
 const activeQueue=useMemo(()=>QUEUES.find(item=>item.key===active)||QUEUES[0],[active]);
 return <main className="ops-shell"><header className="ops-hero"><div><p className="ops-eyebrow">DANI DECLARES OPERATING SYSTEM</p><h1>Operations Control Center</h1><p>One command layer for intake, quotes, booking requests, dispatch, scheduling, field execution, evidence and accounting.</p></div><div className="ops-boundary"><strong>COMMERCIAL AUTHORITY</strong><span>Canonical pricing → frozen estimate → operations</span><small>Operational modules never recalculate catalog pricing.</small></div></header>
 {error&&<div className="ops-alert">{error}</div>}{message&&<div className="ops-alert" style={{background:'#edf8ef',color:'#276b35'}}>✓ {message}</div>}
 <section className="ops-stats"><Stat label="Collected" value={loading?'…':`$${salesCollected.toFixed(0)} / $${WEEKLY_TARGET}`} detail="Weekly target"/><Stat label="Requests" value={loading?'…':counts.requests} detail="Intake / CRM"/><Stat label="Jobs" value={loading?'…':counts.jobs} detail="Execution ledger"/><Stat label="Schedule" value={loading?'…':counts.schedule} detail="Appointments + owner requests"/><Stat label="Providers" value={loading?'…':counts.providers} detail="Field network"/><Stat label="Change Orders" value={loading?'…':counts.changes} detail="Commercial deltas"/><Stat label="Evidence" value={loading?'…':counts.evidence} detail="Field proof"/><Stat label="Payments" value={loading?'…':counts.payments} detail="Accounting events"/></section>
 <section className="ops-grid"><aside className="ops-nav"><div className="ops-nav-title">WORKFLOWS</div>{QUEUES.map(item=><button key={item.key} className={active===item.key?'active':''} onClick={()=>setActive(item.key)}><span>{item.label}</span><small>{counts[item.key]}</small></button>)}</aside><section className="ops-workspace"><div className="ops-section-head"><div><p className="ops-eyebrow">LIVE OPERATIONAL LAYER</p><h2>{activeQueue.label}</h2><p>{activeQueue.description}</p></div><span className="ops-live">● STAFF ACCESS</span></div>
 {active==='sales'&&<>{SALES_LANE_ORDER.filter(lane=>salesByLane[lane]?.length).map(lane=><div className="ops-card" key={lane}><h3>{SALES_LANE_LABELS[lane]} ({salesByLane[lane].length})</h3>{salesByLane[lane].map(row=><SalesRow key={row.id} row={row} onSave={updateSalesRow}/>)}</div>)}{!data?.salesQueue?.length&&<p className="ops-note">No sales queue rows.</p>}</>}
 {active==='requests'&&<><div className="ops-card"><h3>Channel routing</h3><div className="channel-grid">{CHANNELS.map(channel=><div key={channel}><strong>{channel}</strong><span>{channelCounts[channel]}</span></div>)}</div></div><div className="ops-card"><h3>Recent intake</h3>{(data?.requests||[]).slice(0,10).map(row=><div className="ops-row" key={row.id}><div><strong>{row.service_needed||row.service_category||'Service request'}</strong><small>{row.status} · {row.location_address||'Location on file'}{row.property_details?.requestedStartAt?` · Requested ${new Date(row.property_details.requestedStartAt).toLocaleString()}`:''}</small></div><div className="ops-actions">{row.status!=='completed'&&<button onClick={()=>window.location.assign(`/portal/quotes?requestId=${encodeURIComponent(row.id)}`)}>Process quote</button>}{row.service_id&&row.division_id&&row.status!=='completed'&&!(data?.jobs||[]).some(job=>job.service_request_id===row.id)&&<button onClick={()=>instantiateFulfillment(row.id)}>Instantiate fulfillment</button>}</div></div>)}{!data?.requests?.length&&<p className="ops-note">No recent requests.</p>}</div></>}
 {active==='jobs'&&<div className="ops-card"><h3>Dispatch queue</h3>{(data?.jobs||[]).slice(0,12).map(job=><div className="ops-row" key={job.id}><div><strong>{job.job_title}</strong><small>{job.job_status} · {job.location_address||'Location on file'}</small></div><div className="ops-actions">{job.job_status==='new'&&<button onClick={()=>routeDispatch(job.id)}>Run dispatch resolver</button>}</div></div>)}</div>}
 {active==='schedule'&&<><div className="ops-card"><h3>Owner booking requests</h3>{(data?.bookingRequests||[]).map(item=><div className="ops-row" key={item.id}><div><strong>{item.service_name||'DANI SPECIALS request'}</strong><small>{item.status} · {new Date(item.requested_start_at||item.starts_at).toLocaleString('en-US',{timeZone:'America/New_York'})} · {item.customer_name}</small><small>{item.location_address||'Location on file'} · {item.duration_minutes} min + 30 min buffers</small></div><div className="ops-actions"><button onClick={()=>window.location.assign(`/portal/quotes?requestId=${encodeURIComponent(item.service_request_id||'')}&service=${encodeURIComponent(item.service_id||'')}`)}>Open quote</button>{item.status==='HOLD'&&<><button onClick={()=>updateBooking(item.id,'CONFIRMED')}>Confirm</button><button className="secondary" onClick={()=>updateBooking(item.id,'DECLINED')}>Decline</button></>}{item.status==='CONFIRMED'&&<button className="secondary" onClick={()=>updateBooking(item.id,'CANCELLED')}>Cancel</button>}</div></div>)}{!data?.bookingRequests?.length&&<p className="ops-note">No owner booking requests.</p>}</div><div className="ops-card"><h3>Existing appointment ledger</h3>{(data?.appointments||[]).slice(0,15).map(item=><div className="ops-row" key={item.id}><div><strong>{new Date(item.starts_at).toLocaleString()}</strong><small>{item.appointment_status} · Provider {item.provider_id}</small></div></div>)}</div></>}
 {active==='providers'&&<><div className="ops-card"><h3>Provider network</h3>{(data?.providers||[]).map(provider=><div className="ops-row" key={provider.id}><div><strong>{provider.first_name} {provider.last_name}</strong><small>{provider.dd_provider_organizations?.name||'Provider organization'} · {provider.is_active?'ACTIVE':'INACTIVE'}</small></div></div>)}</div><div className="ops-card"><h3>Self-requested services awaiting review</h3><p className="ops-note">Providers can add services from their own "My Services" page. Nothing here is authorized for dispatch until approved below.</p>{(data?.pendingCapabilities||[]).map(item=><div className="ops-row" key={item.id}><div><strong>{item.services?.name||item.service_line}</strong><small>{item.services?.sku?`${item.services.sku} · `:''}{item.dd_providers?.first_name} {item.dd_providers?.last_name} · {item.dd_providers?.dd_provider_organizations?.name||'Provider organization'}</small></div><div className="ops-actions"><button onClick={()=>act('authorize_provider_capability',{capabilityId:item.id})}>Authorize</button><button className="secondary" onClick={()=>act('reject_provider_capability',{capabilityId:item.id})}>Reject</button></div></div>)}{!data?.pendingCapabilities?.length&&<p className="ops-note">No self-requested services waiting on review.</p>}</div><div className="ops-card"><h3>W-9 submissions awaiting review</h3><p className="ops-note">Full TIN is encrypted and not shown here -- only the last four digits. Use "Reveal full TIN" only when a real need (e.g. preparing a 1099) requires it; every reveal is logged.</p>{(data?.pendingW9Submissions||[]).map(item=><div className="ops-row" key={item.id}><div><strong>{item.line1_name}</strong><small>{item.dd_provider_organizations?.name||'Provider organization'} · {item.tin_type} ending in {revealedTins[item.id]?revealedTins[item.id]:item.tin_last_four} · {statusLabel(item.classification)}</small></div><div className="ops-actions">{!revealedTins[item.id]&&<button className="secondary" onClick={()=>revealTin(item.id)}>Reveal full TIN</button>}<button onClick={()=>act('verify_provider_w9',{submissionId:item.id})}>Verify</button><button className="secondary" onClick={()=>act('reject_provider_w9',{submissionId:item.id})}>Reject</button></div></div>)}{!data?.pendingW9Submissions?.length&&<p className="ops-note">No W-9 submissions waiting on review.</p>}</div></>}
 {active==='changes'&&<div className="ops-card"><h3>Change-order approval queue</h3>{(data?.changes||[]).filter(item=>item.status==='PENDING_APPROVAL').map(item=><div className="ops-row" key={item.id}><div><strong>{item.reason}</strong><small>{item.resolved_channel||'Channel-controlled'} · Delta snapshot ready</small></div><div className="ops-actions"><button onClick={()=>act('change_order_decision',{changeOrderId:item.id,decision:'APPROVED'})}>Approve</button><button className="secondary" onClick={()=>act('change_order_decision',{changeOrderId:item.id,decision:'REJECTED',reason:'Rejected by staff review.'})}>Reject</button></div></div>)}{!(data?.changes||[]).some(item=>item.status==='PENDING_APPROVAL')&&<p className="ops-note">No pending change orders.</p>}</div>}
 {active==='evidence'&&<div className="ops-card"><h3>Evidence & QA</h3>{(data?.evidence||[]).slice(0,15).map(item=>{const isImage=item.signed_url&&(item.file_metadata?.type||'').startsWith('image/');return <div className="ops-row" key={item.id} style={{alignItems:'flex-start',gap:14}}>{isImage&&<img src={item.signed_url} alt={item.evidence_type} style={{width:96,height:96,objectFit:'cover',borderRadius:8,flexShrink:0}}/>}<div><strong>{item.evidence_type}</strong><small>{item.verification_status} · Job {item.job_id}</small>{item.signed_url&&!isImage&&<div><a href={item.signed_url} target="_blank" rel="noreferrer">View file</a></div>}</div><div className="ops-actions">{item.verification_status==='PENDING'&&<><button onClick={()=>act('evidence_verify',{evidenceId:item.id,decision:'VERIFIED'})}>Verify</button><button className="secondary" onClick={()=>act('evidence_verify',{evidenceId:item.id,decision:'REJECTED'})}>Reject</button></>}</div></div>;})}{!data?.evidence?.length&&<p className="ops-note">No evidence waiting for review.</p>}</div>}
 {active==='payments'&&<div className="ops-card"><h3>Payment reconciliation ledger</h3><p className="ops-note">Stripe webhooks reconcile payment reality against frozen commercial records. This console displays the ledger; it does not calculate prices.</p>{(data?.payments||[]).slice(0,15).map(item=><div className="ops-row" key={item.id}><div><strong>{item.event_type}</strong><small>{item.payment_status} · ${Number(item.amount_received||0).toFixed(2)} {item.currency}</small></div></div>)}</div>}
 </section></section><footer className="ops-footer"><strong>Built for DANI DECLARES.</strong> Jobber-style CRM + Housecall Pro-style field operations + Thumbtack-style intake + Jibble-style workforce accountability, all governed by the DANI DECLARES commercial authority.</footer></main>;
}
export default function OperationsConsolePage(){return <RequireStaffAuth><OperationsConsole/></RequireStaffAuth>}
