import React, { useEffect, useMemo, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import RequireStaffAuth from '../../components/auth/RequireStaffAuth.jsx';
import { supabase } from '../../lib/supabaseClient.js';
import { calculate, isHourlyBilled } from '../../lib/operations/quoteBuilder2026.js';

const ESTIMATE_CLIENT_TYPES={regular_resident:'other',apartment_resident:'renter',property_manager:'property_manager',realtor:'realtor',business:'business',government:'other'};
const CLIENT_TYPES=[['regular_resident','Regular Resident'],['apartment_resident','Apartment Resident'],['property_manager','Property Management / Apartment'],['realtor','Real Estate Office / Brokerage'],['business','Business / Commercial'],['government','Government / Institutional']];
const REVIEW_FLAG_LABELS={FULFILLMENT_OR_COMMERCIAL_GATE:'Service not fully authorized for checkout yet',SCOPE_REVIEW:'Custom/variable scope — confirm details before sending',LAYOUT_REVIEW:'Select the unit bedroom count before sending this move-out turn quote',SPECIALTY_CARPET_SCOPE:'Specialized carpet extraction is a separate scope item — review before sending',DEBRIS_FURNITURE_SCOPE:'Abandoned property / furniture removal is a separate scope item — review before sending',MATERIALS_CONFIRMATION:'Confirm materials cost before sending',PASS_THROUGH_CONFIRMATION:'Confirm pass-through cost before sending',TAX_REVIEW:'Tax rate is 0% — set it if this customer owes tax',MANUAL_BASE_IGNORED_GOVERNED_PRICING:'Manual price ignored — governed catalog pricing used instead',TRAVEL_CONFIRMATION:'Confirm mileage / travel cost before sending'};
const inputStyle={width:'100%',padding:'11px 12px',borderRadius:10,border:'1px solid #decfae',background:'#fff'};
const baseAnswers={quantity:1,hours:1,miles_one_way:0,materials_cost:0,pass_through_cost:0,tax_rate_percent:0,deposit_percent:0,apply_standard_travel:false,rush:false};
const uid=()=>`line-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;
const freshLine=(sku,answers={})=>({id:uid(),serviceSku:sku,answers:{...baseAnswers,...answers}});
function Field({label,value,onChange,type='text',placeholder=''}){return <label style={{display:'grid',gap:6,fontWeight:700,color:'#3d2b30'}}><span style={{fontSize:13}}>{label}</span><input type={type} value={value??''} onChange={e=>onChange(e.target.value)} placeholder={placeholder} style={inputStyle}/></label>}
function SelectField({label,value,onChange,options}){return <label style={{display:'grid',gap:6,fontWeight:700,color:'#3d2b30'}}><span style={{fontSize:13}}>{label}</span><select value={value??''} onChange={e=>onChange(e.target.value)} style={inputStyle}><option value="">Select…</option>{options.map(o=><option key={String(o.value??o)} value={String(o.value??o)}>{String(o.label??o).replace(/_/g,' ')}</option>)}</select></label>}
function DynamicQuestion({q,value,onChange}){if(q.type==='boolean')return <label style={{display:'flex',alignItems:'center',gap:8,fontWeight:700,color:'#3d2b30'}}><input type="checkbox" checked={Boolean(value)} onChange={e=>onChange(e.target.checked)}/>{q.label}</label>;if(q.options?.length){const options=q.options.map(o=>typeof o==='object'?o:{value:o,label:o});return <SelectField label={q.label} value={value} onChange={onChange} options={options}/>;}return <Field label={q.label} value={value??''} onChange={onChange} type={q.type==='number'?'number':'text'}/>}

function QuoteBuilder(){
 const params=useMemo(()=>new URLSearchParams(window.location.search),[]);
 const requestId=params.get('requestId')||'', estimateId=params.get('estimateId')||'', initialServiceSku=params.get('service')||'';
 const navigate=useNavigate();
 const [services,setServices]=useState([]),[search,setSearch]=useState('');
 const [lineItems,setLineItems]=useState(initialServiceSku?[freshLine(initialServiceSku)]:[]);
 const [clientType,setClientType]=useState('business');
 const [clientName,setClientName]=useState(''),[clientPhone,setClientPhone]=useState(''),[clientEmail,setClientEmail]=useState(''),[organizationName,setOrganizationName]=useState(''),[locationAddress,setLocationAddress]=useState(''),[city,setCity]=useState(''),[zipCode,setZipCode]=useState(''),[timeline,setTimeline]=useState(''),[requestedDate,setRequestedDate]=useState(''),[clientNotes,setClientNotes]=useState(''),[internalNotes,setInternalNotes]=useState('');
 const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[result,setResult]=useState(null),[requestLoaded,setRequestLoaded]=useState(false),[editingEstimate,setEditingEstimate]=useState(false),[sourceRequestId,setSourceRequestId]=useState(requestId);

 useEffect(()=>{(async()=>{const {data:s}=await supabase.auth.getSession();if(!s.session){setError('Staff session required.');setLoading(false);return}try{
   const r=await fetch('/api/portal-operations?quoteCatalog=1',{headers:{Authorization:`Bearer ${s.session.access_token}`}});const d=await r.json();if(!r.ok||!d.success)throw new Error(d.error||'Could not load the governed catalog.');setServices(d.services||[]);
   if(estimateId){
     const {data:est,error:estError}=await supabase.from('dd_estimates').select('*').eq('id',estimateId).single();if(estError)throw estError;if(est){
       setEditingEstimate(true);setResult({estimate:{public_reference:est.public_reference,estimate_status:est.estimate_status,estimated_total:est.estimated_total},calculation:est.intake_answers?.pricingSnapshot||null});
       const ia=est.intake_answers||{}, a=ia.answers||{};
       const savedLines=Array.isArray(ia.lineItems)&&ia.lineItems.length?ia.lineItems.map(li=>freshLine(li.serviceSku,li.answers||{})):freshLine(ia.serviceSku||initialServiceSku||'',a);
       setLineItems(savedLines.filter(li=>li.serviceSku));
       setClientName(est.client_name||'');setClientPhone(est.client_phone||'');setClientEmail(est.client_email||'');setClientType(Object.entries(ESTIMATE_CLIENT_TYPES).find(([,v])=>v===est.client_type)?.[0]||ia.originalClientType||'business');setOrganizationName(est.organization_name||'');setLocationAddress(est.location_address||'');setCity(est.city||'');setZipCode(est.zip_code||'');setTimeline(est.timeline||'');setRequestedDate(est.requested_date||'');setClientNotes(est.client_notes||'');setInternalNotes(est.internal_notes||'');setSourceRequestId(est.service_request_id||'');setRequestLoaded(Boolean(est.service_request_id));
     }
   } else if(requestId){
     const {data:req,error:reqError}=await supabase.from('service_requests').select('*').eq('id',requestId).single();if(reqError)throw reqError;if(req){if(req.lead_id){const {data:lead}=await supabase.from('leads').select('full_name,phone,email,organization_name').eq('id',req.lead_id).single();if(lead){setClientName(lead.full_name||'');setClientPhone(lead.phone||'');setClientEmail(lead.email||'');setOrganizationName(lead.organization_name||'');}}setLocationAddress(req.location_address||'');setTimeline(req.timeline||'');setClientNotes(req.request_details||'');const sku=req.property_details?.pricingServiceId||req.service_id||initialServiceSku||'';if(sku)setLineItems([freshLine(sku)]);const t=req.property_details?.requestedStartAt||'';if(t){const dt=new Date(t);if(!Number.isNaN(dt.valueOf()))setRequestedDate(dt.toISOString().slice(0,10));}const route=req.property_details?.operationsRouting?.channelType||'';setClientType(route==='B2C'?'regular_resident':route==='B2B_APT'?'property_manager':route==='B2B_RE'?'realtor':route==='B2G'?'government':'business');setInternalNotes(`Website request ${requestId}. Review scope and scheduling hold before sending quote.`);setRequestLoaded(true);}}
 }catch(e){setError(e.message||'Could not load quote data.')}finally{setLoading(false)}})()},[requestId,initialServiceSku,estimateId]);

 const offerRows=useMemo(()=>services.flatMap(s=>[s,...(s.offerVariants||[])]),[services]);
 const serviceBySku=useMemo(()=>new Map(offerRows.map(s=>[s.sku,s])),[offerRows]);
 const primary=lineItems[0]||null;
 const packagePreviews=useMemo(()=>lineItems.map(li=>{const s=serviceBySku.get(li.serviceSku);return s?{line:li,service:s,calculation:calculate(s,null,{...li.answers,apply_resident_discount:false})}:null}).filter(Boolean),[lineItems,serviceBySku]);
 const packageCalculation=useMemo(()=>packagePreviews.reduce((acc,row)=>{for(const k of ['baseSubtotal','residentDiscount','travelFee','rushFee','materials','sourcingFee','passThrough','tax','estimatedTotal','depositDue'])acc[k]+=Number(row.calculation[k]||0);acc.reviewFlags.push(...(row.calculation.reviewFlags||[]).map(f=>row.service.sku+':'+f));if(row.calculation.needsReview)acc.needsReview=true;return acc},{baseSubtotal:0,residentDiscount:0,travelFee:0,rushFee:0,materials:0,sourcingFee:0,passThrough:0,tax:0,estimatedTotal:0,depositDue:0,reviewFlags:[],needsReview:false}),[packagePreviews]);
 const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return q?services.filter(s=>`${s.name} ${s.sku} ${s.service_family||''} ${(s.offerVariants||[]).map(v=>`${v.name} ${v.sku} ${v.displayLabel||''}`).join(' ')}`.toLowerCase().includes(q)):services},[services,search]);
 const setLineAnswer=(id,key,value)=>setLineItems(items=>items.map(li=>li.id===id?{...li,answers:{...li.answers,[key]:value}}:li));
 const addService=(sku,meta={})=>{if(!sku)return;setLineItems(items=>[...items,{...freshLine(sku,meta.answers||{}),parentLineId:meta.parentLineId||null,parentServiceSku:meta.parentServiceSku||null,componentRole:meta.componentRole||'PRIMARY'}]);setResult(null)};
 const addCompanion=(parentLine,companion)=>{
   const exists=lineItems.some(li=>li.parentLineId===parentLine.id&&li.serviceSku===companion.sku);
   if(exists)return;
   addService(companion.sku,{parentLineId:parentLine.id,parentServiceSku:parentLine.serviceSku,componentRole:companion.component_role||'COMPANION'});
 };
 const removeService=id=>setLineItems(items=>items.length<=1?items:items.filter(li=>li.id!==id));
 const buildQuote=async()=>{if(!lineItems.length){setError('Add at least one service to the package.');return}setSaving(true);setError('');const {data:s}=await supabase.auth.getSession();if(!s.session){setError('Staff session required.');setSaving(false);return}const r=await fetch('/api/portal-operations',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${s.session.access_token}`},body:JSON.stringify({action:editingEstimate?'update_estimate':'create_estimate',estimateId:editingEstimate?estimateId:null,requestId:sourceRequestId||null,lineItems:lineItems.map(li=>({serviceSku:li.serviceSku,answers:li.answers,parentLineId:li.parentLineId||null,parentServiceSku:li.parentServiceSku||null,componentRole:li.componentRole||'PRIMARY'})),serviceSku:primary?.serviceSku||'',clientType,clientName,clientPhone,clientEmail,organizationName,locationAddress,city,zipCode,timeline,requestedDate:requestedDate||null,clientNotes,internalNotes})});const d=await r.json();if(!r.ok||!d.success)setError(d.error||'Estimate could not be saved.');else{setResult(d);navigate(`/portal/estimates/${d.estimate.id}/review`)}setSaving(false)};

 return <RequireStaffAuth><main style={{minHeight:'100vh',background:'#fffaf1',color:'#302226',padding:'28px 18px 60px'}}><div style={{maxWidth:1280,margin:'0 auto'}}>
 <header style={{display:'flex',justifyContent:'space-between',gap:18,alignItems:'flex-start',flexWrap:'wrap',marginBottom:24}}><div style={{display:'flex',gap:8,flexWrap:'wrap',order:2}}><Link to="/portal" style={btnStyle('#fff','#5a1624')}>← My Portal</Link><Link to="/portal/saved-quotes" style={btnStyle('#f7edd4','#5a1624')}>Saved Quotes</Link></div><div><div style={eyebrow}>DANI DECLARES OPERATING SYSTEM</div><h1 style={h1}>Quote Builder</h1><p style={sub}>Build one customer estimate from one or many governed services. Each service keeps its own quote inputs and pricing contract; the package rolls them into one reviewable commercial total.</p>{requestLoaded&&<div style={badge}>Loaded website request {sourceRequestId}</div>}{editingEstimate&&<div style={{...badge,background:'#edf8ef',color:'#245b34',marginLeft:8}}>Editing saved estimate</div>}</div></header>
 {error&&<div style={alert('#fff0f0','#8a1d2d')}>{error}</div>}
 <section style={layout}>
  <div style={{display:'grid',gap:18}}>
   <section style={card}><h2 style={sectionTitle}>1. Customer & channel</h2><div style={formGrid}><SelectField label="Customer relationship" value={clientType} onChange={setClientType} options={CLIENT_TYPES.map(([value,label])=>({value,label}))}/><Field label="Customer name" value={clientName} onChange={setClientName} placeholder="Full name"/><Field label="Phone" value={clientPhone} onChange={setClientPhone}/><Field label="Email" value={clientEmail} onChange={setClientEmail}/><Field label="Organization / property" value={organizationName} onChange={setOrganizationName}/><Field label="City" value={city} onChange={setCity}/><Field label="ZIP" value={zipCode} onChange={setZipCode}/><Field label="Requested date" value={requestedDate} onChange={setRequestedDate} type="date"/></div><div style={{marginTop:12}}><Field label="Service location" value={locationAddress} onChange={setLocationAddress}/></div></section>

   <section style={card}><h2 style={sectionTitle}>2. Build the package</h2><Field label="Search the complete catalog" value={search} onChange={setSearch} placeholder="cleaning, holiday, events, admin, DANI SPECIALS…"/><div style={{marginTop:12,padding:12,borderRadius:12,background:'#fffaf0',border:'1px solid #eadfc9',color:'#6d5b60',fontSize:13}}>Click <strong>Add to package</strong> for every service you want on this estimate. You can add the same service more than once when the scope is legitimately separate.</div><div style={{marginTop:12,display:'grid',gap:9,maxHeight:360,overflowY:'auto'}}>{loading?<div>Loading catalog…</div>:filtered.map(s=><div key={s.sku} style={{display:'flex',gap:8,alignItems:'stretch'}}><div style={{flex:1,borderRadius:12,padding:12,border:'1px solid #e3d6bd',background:'#fff'}}><div style={{display:'flex',justifyContent:'space-between',gap:8,alignItems:'center'}}><strong style={{color:'#5a1624'}}>{s.name}</strong>{s.hasCommercialConflict&&<span style={smallBadge}>SPECIAL VARIANT</span>}</div><div style={{fontSize:12,color:'#7b686d',marginTop:3}}>{s.sku} · {s.service_family||'Service'} · {s.publicPrice}</div></div><button type="button" onClick={()=>addService(s.sku)} style={btnStyle('#5a1624','#fff')}>+ Add</button>{(s.offerVariants||[]).length>0&&<div style={{display:'none'}}/>}</div>)}</div></section>

   <section style={card}><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',flexWrap:'wrap'}}><div><h2 style={sectionTitle}>3. Package components & quote inputs</h2><p style={muted}>Each component gets the fields its service contract requires. Cleaning, holiday, events, admin, and other service families can therefore use different quote questions without changing the core builder.</p></div><span style={countBadge}>{lineItems.length} component{lineItems.length===1?'':'s'}</span></div>
    {lineItems.length===0?<div style={empty}>Add a service above to start building the estimate.</div>:<div style={{display:'grid',gap:14}}>{lineItems.map((li,index)=>{const s=serviceBySku.get(li.serviceSku);if(!s)return null;const schema=s.quote_input_schema||{};const questions=s.quoteQuestions||schema.fields||[];const hourly=isHourlyBilled(s,null);const calc=packagePreviews.find(x=>x.line.id===li.id)?.calculation;return <div key={li.id} style={componentCard}>
      <div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'flex-start'}}><div><div style={eyebrow}>{li.componentRole==='COMPANION'?'COMPANION':'COMPONENT'} {index+1}</div><h3 style={{margin:'4px 0',color:'#5a1624'}}>{s.name}</h3><div style={muted}>{s.sku} · {s.publicPrice||'Quote required'}</div></div>{lineItems.length>1&&<button type="button" onClick={()=>removeService(li.id)} style={btnStyle('#fff','#8a1d2d')}>Remove</button>}</div>
      {questions.length>0&&<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))',gap:12,marginTop:14}}>{questions.map(q=><DynamicQuestion key={q.key} q={q} value={li.answers[q.key]} onChange={v=>setLineAnswer(li.id,q.key,v)}/>)}</div>}
      {schema.ui_mode==='SPECIALIZED_CLEANING'&&<div style={{marginTop:14,padding:13,borderRadius:12,background:'#fff',border:'1px solid #eadfc9'}}><div style={{fontWeight:900,color:'#5a1624',marginBottom:8}}>Cleaning companion lines</div><div style={{display:'grid',gap:8}}>{(schema.companion_lines||[]).map(companion=>{const checked=lineItems.some(x=>x.parentLineId===li.id&&x.serviceSku===companion.sku);const target=serviceBySku.get(companion.sku);return <label key={companion.sku} style={{display:'flex',gap:9,alignItems:'center',padding:9,borderRadius:9,border:'1px solid #e3d6bd',background:checked?'#f7edd4':'#fff',cursor:'pointer'}}><input type="checkbox" checked={checked} disabled={!target} onChange={e=>e.target.checked?addCompanion(li,companion):setLineItems(items=>items.filter(x=>!(x.parentLineId===li.id&&x.serviceSku===companion.sku)))} /> <span><strong>{companion.label}</strong>{target&&<span style={{display:'block',fontSize:11,color:'#6d5b60'}}>{target.sku} · {target.publicPrice||'quote required'}</span>}</span></label>})}</div></div>}
      {schema.ui_mode!=='SPECIALIZED_CLEANING'&&<><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(170px,1fr))',gap:12,marginTop:14}}><Field label="Quantity / units" value={li.answers.quantity} onChange={v=>setLineAnswer(li.id,'quantity',v)} type="number"/><Field label={hourly?'Hours (drives price)':'Hours / labor estimate'} value={li.answers.hours} onChange={v=>setLineAnswer(li.id,'hours',v)} type="number"/><Field label="Miles one way" value={li.answers.miles_one_way} onChange={v=>setLineAnswer(li.id,'miles_one_way',v)} type="number"/><Field label="Materials cost" value={li.answers.materials_cost} onChange={v=>setLineAnswer(li.id,'materials_cost',v)} type="number"/><Field label="Pass-through cost" value={li.answers.pass_through_cost} onChange={v=>setLineAnswer(li.id,'pass_through_cost',v)} type="number"/><Field label="Tax rate %" value={li.answers.tax_rate_percent} onChange={v=>setLineAnswer(li.id,'tax_rate_percent',v)} type="number"/><Field label="Deposit %" value={li.answers.deposit_percent} onChange={v=>setLineAnswer(li.id,'deposit_percent',v)} type="number"/></div>
      <div style={{display:'flex',gap:16,flexWrap:'wrap',marginTop:12}}><label style={check}><input type="checkbox" checked={Boolean(li.answers.apply_standard_travel)} onChange={e=>setLineAnswer(li.id,'apply_standard_travel',e.target.checked)}/> Standard travel rule</label><label style={check}><input type="checkbox" checked={Boolean(li.answers.rush)} onChange={e=>setLineAnswer(li.id,'rush',e.target.checked)}/> 24-hour / rush (+25%)</label></div></>}
      {calc&&<div style={{marginTop:12,padding:12,borderRadius:10,background:'#fffaf0',border:'1px solid #eadfc9',display:'flex',justifyContent:'space-between',gap:10,flexWrap:'wrap'}}><span><strong>Live component estimate</strong>{calc.reviewFlags?.length>0&&<span style={{display:'block',fontSize:12,color:'#8a1d2d',marginTop:3}}>{calc.reviewFlags.map(f=>REVIEW_FLAG_LABELS[f]||f).join(' · ')}</span>}</span><strong style={{fontSize:18,color:'#5a1624'}}>${Number(calc.estimatedTotal||0).toFixed(2)}</strong></div>}
    </div>})}</div>}
   </section>

   <section style={card}><h2 style={sectionTitle}>4. Timeline & notes</h2><div style={{display:'grid',gap:12}}><Field label="Timeline / urgency" value={timeline} onChange={setTimeline}/><label style={labelStyle}>Customer notes<textarea value={clientNotes} onChange={e=>setClientNotes(e.target.value)} rows={3} style={textarea}/></label><label style={labelStyle}>Internal notes<textarea value={internalNotes} onChange={e=>setInternalNotes(e.target.value)} rows={3} style={textarea}/></label></div></section>
  </div>

  <aside style={{alignSelf:'start',position:'sticky',top:18}}><section style={{background:'#5a1624',color:'#fff',borderRadius:18,padding:20}}><div style={eyebrow}>PACKAGE ESTIMATE PREVIEW</div><h2 style={{margin:'7px 0 14px'}}>{lineItems.length?lineItems.length+' service component'+(lineItems.length===1?'':'s'):'Choose services'}</h2>{packagePreviews.length===0?<p style={mutedLight}>Add services to see their governed quote inputs and live package total.</p>:<><div style={{display:'grid',gap:8}}>{packagePreviews.map(row=><div key={row.line.id} style={{display:'flex',justifyContent:'space-between',gap:8,fontSize:13}}><span>{row.service.name}</span><strong>${Number(row.calculation.estimatedTotal||0).toFixed(2)}</strong></div>)}</div><hr style={{border:0,borderTop:'1px solid rgba(255,255,255,.2)',margin:'14px 0'}}/><div style={{display:'grid',gap:7,fontSize:14}}>{[['Base',packageCalculation.baseSubtotal],['Resident discount',-packageCalculation.residentDiscount],['Travel',packageCalculation.travelFee],['Rush',packageCalculation.rushFee],['Materials + sourcing',packageCalculation.materials+packageCalculation.sourcingFee],['Pass-through',packageCalculation.passThrough],['Tax',packageCalculation.tax]].map(([l,v])=><div key={l} style={{display:'flex',justifyContent:'space-between'}}><span>{l}</span><strong>${Number(v).toFixed(2)}</strong></div>)}</div><hr style={{border:0,borderTop:'1px solid rgba(255,255,255,.2)'}}/><div style={{display:'flex',justifyContent:'space-between',fontSize:23}}><span>Total</span><strong>${Number(packageCalculation.estimatedTotal).toFixed(2)}</strong></div><div style={{marginTop:14,padding:12,borderRadius:10,background:packageCalculation.needsReview?'#6f4d18':'#234c31'}}><strong>{packageCalculation.needsReview?'Review before sending':'Ready estimate'}</strong><div style={{fontSize:12,marginTop:3}}>{packageCalculation.reviewFlags.map(f=>REVIEW_FLAG_LABELS[f.split(':').pop()]||f).join(' · ')||'No additional review flags.'}</div></div></>}</section><button disabled={saving||!lineItems.length} onClick={buildQuote} style={{...btnStyle('#8b6b1f','#fff'),width:'100%',marginTop:12,fontSize:16}}>{saving?'Saving package…':editingEstimate?'Save Package & Review':'Build Package & Review'}</button>{result&&<div style={{marginTop:10,padding:12,borderRadius:10,background:'#fff',border:'1px solid #decfae',color:'#5a1624',fontSize:13}}>Saved as <strong>{result.estimate.public_reference}</strong>.</div>}</aside>
 </section>
 </div></main></RequireStaffAuth>;
}

const eyebrow={fontSize:12,letterSpacing:2,fontWeight:900,color:'#8b6b1f'};
const h1={margin:'5px 0',fontSize:'clamp(30px,5vw,48px)',color:'#5a1624'};
const sub={margin:0,maxWidth:760,color:'#6d5b60'};
const layout={display:'grid',gridTemplateColumns:'minmax(0,1.15fr) minmax(320px,.85fr)',gap:18};
const card={background:'#fff',border:'1px solid #e2d6bf',borderRadius:16,padding:18};
const sectionTitle={margin:'0 0 14px',color:'#5a1624'};
const formGrid={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))',gap:12};
const componentCard={background:'#fffaf1',border:'1px solid #e2d6bf',borderRadius:14,padding:16};
const labelStyle={display:'grid',gap:6,fontWeight:700,color:'#3d2b30'};
const textarea={width:'100%',borderRadius:10,border:'1px solid #decfae',padding:12,boxSizing:'border-box'};
const check={display:'flex',alignItems:'center',gap:8,fontWeight:700,color:'#3d2b30'};
const muted={color:'#6d5b60',fontSize:13,lineHeight:1.5};
const mutedLight={color:'#f1e3e5',fontSize:13,lineHeight:1.5};
const badge={marginTop:10,display:'inline-block',padding:'7px 10px',borderRadius:9,background:'#f7edd4',fontSize:12,fontWeight:800,color:'#6b1f2b'};
const smallBadge={fontSize:10,fontWeight:900,padding:'4px 6px',borderRadius:999,background:'#f7edd4',color:'#6b1f2b'};
const countBadge={padding:'6px 9px',borderRadius:999,background:'#f7edd4',color:'#6b1f2b',fontWeight:900,fontSize:12};
const empty={padding:16,borderRadius:12,background:'#fffaf0',color:'#6d5b60'};
const btnStyle=(background,color)=>({display:'inline-flex',alignItems:'center',justifyContent:'center',padding:'10px 12px',borderRadius:9,border:'1px solid #decfae',background,color,textDecoration:'none',fontWeight:900,cursor:'pointer'});
const alert=(background,color)=>({marginBottom:18,padding:14,borderRadius:12,background,border:'1px solid #e2b8b8',color});
export default QuoteBuilder;
