import React, { useEffect, useMemo, useState } from 'react';
import RequireStaffAuth from '../../components/auth/RequireStaffAuth.jsx';
import { supabase } from '../../lib/supabaseClient.js';

const CLIENT_TYPES=[['regular_resident','Regular Resident'],['apartment_resident','Apartment Resident'],['property_manager','Property Management / Apartment'],['realtor','Real Estate Office / Brokerage'],['business','Business / Commercial'],['government','Government / Institutional']];
const inputStyle={width:'100%',padding:'11px 12px',borderRadius:10,border:'1px solid #decfae',background:'#fff'};
function Field({label,value,onChange,type='text',placeholder=''}){return <label style={{display:'grid',gap:6,fontWeight:700,color:'#3d2b30'}}><span style={{fontSize:13}}>{label}</span><input type={type} value={value??''} onChange={e=>onChange(e.target.value)} placeholder={placeholder} style={inputStyle}/></label>}
function SelectField({label,value,onChange,options}){return <label style={{display:'grid',gap:6,fontWeight:700,color:'#3d2b30'}}><span style={{fontSize:13}}>{label}</span><select value={value??''} onChange={e=>onChange(e.target.value)} style={inputStyle}>{options.map(o=><option key={String(o)} value={String(o)}>{String(o).replace(/_/g,' ')}</option>)}</select></label>}
function DynamicQuestion({q,value,onChange}){if(q.type==='boolean')return <label style={{display:'flex',alignItems:'center',gap:8,fontWeight:700}}><input type="checkbox" checked={Boolean(value)} onChange={e=>onChange(e.target.checked)}/>{q.label}</label>;if(q.options?.length)return <SelectField label={q.label} value={value??q.options[0]} onChange={onChange} options={q.options}/>;return <Field label={q.label} value={value??''} onChange={onChange} type={q.type==='number'?'number':'text'}/>}

function QuoteBuilder(){
 const [services,setServices]=useState([]),[serviceSku,setServiceSku]=useState(''),[clientType,setClientType]=useState('business'),[search,setSearch]=useState('');
 const [clientName,setClientName]=useState(''),[clientPhone,setClientPhone]=useState(''),[clientEmail,setClientEmail]=useState(''),[organizationName,setOrganizationName]=useState(''),[locationAddress,setLocationAddress]=useState(''),[city,setCity]=useState(''),[zipCode,setZipCode]=useState(''),[timeline,setTimeline]=useState(''),[requestedDate,setRequestedDate]=useState(''),[clientNotes,setClientNotes]=useState(''),[internalNotes,setInternalNotes]=useState('');
 const [answers,setAnswers]=useState({quantity:1,hours:1,miles_one_way:0,manual_base_price:0,materials_cost:0,pass_through_cost:0,tax_rate_percent:0,deposit_percent:0,apply_standard_travel:false,rush:false});
 const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[result,setResult]=useState(null);
 useEffect(()=>{(async()=>{const {data:s}=await supabase.auth.getSession();if(!s.session){setError('Staff session required.');setLoading(false);return}const r=await fetch('/api/portal-operations?quoteCatalog=1',{headers:{Authorization:`Bearer ${s.session.access_token}`}});const d=await r.json();if(!r.ok||!d.success)setError(d.error||'Could not load the governed catalog.');else{setServices(d.services||[]);if(d.services?.[0])setServiceSku(d.services[0].sku)}setLoading(false)})()},[]);
 const service=services.find(s=>s.sku===serviceSku)||null;
 const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return q?services.filter(s=>`${s.name} ${s.sku} ${s.service_family||''}`.toLowerCase().includes(q)):services},[services,search]);
 const setAnswer=(k,v)=>setAnswers(a=>({...a,[k]:v}));
 const buildQuote=async()=>{setSaving(true);setError('');setResult(null);const {data:s}=await supabase.auth.getSession();if(!s.session){setError('Staff session required.');setSaving(false);return}const r=await fetch('/api/portal-operations',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${s.session.access_token}`},body:JSON.stringify({action:'create_estimate',serviceSku,clientType,clientName,clientPhone,clientEmail,organizationName,locationAddress,city,zipCode,timeline,requestedDate:requestedDate||null,clientNotes,internalNotes,answers})});const d=await r.json();if(!r.ok||!d.success)setError(d.error||'Estimate could not be created.');else setResult(d);setSaving(false)};
 return <main style={{minHeight:'100vh',background:'#fffaf1',color:'#302226',padding:'28px 18px 60px'}}><div style={{maxWidth:1220,margin:'0 auto'}}>
  <header style={{display:'flex',justifyContent:'space-between',gap:18,alignItems:'flex-start',flexWrap:'wrap',marginBottom:24}}><div><div style={{fontSize:12,letterSpacing:2,fontWeight:900,color:'#8b6b1f'}}>DANI DECLARES OPERATING SYSTEM</div><h1 style={{margin:'5px 0',fontSize:'clamp(30px,5vw,48px)',color:'#5a1624'}}>Quote Builder</h1><p style={{margin:0,maxWidth:760,color:'#6d5b60'}}>Search the complete governed service catalog, enter the customer's information once, and save the estimate to the existing estimate ledger.</p></div><div style={{padding:14,borderRadius:14,border:'1px solid #dfcfaa',background:'#f7edd4',maxWidth:340}}><strong>Pricing boundary</strong><div style={{marginTop:5,fontSize:13,lineHeight:1.5}}>Customer pricing comes from the commercial catalog/rules. Provider payouts are never used as retail price. Final scope, tax, pass-throughs and fulfillment gates remain reviewable.</div></div></header>
  {error&&<div style={{marginBottom:18,padding:14,borderRadius:12,background:'#fff0f0',border:'1px solid #e2b8b8',color:'#8a1d2d'}}>{error}</div>}
  <section style={{display:'grid',gridTemplateColumns:'minmax(0,1.1fr) minmax(320px,.9fr)',gap:18}}><div style={{display:'grid',gap:18}}>
   <div style={{background:'#fff',border:'1px solid #e2d6bf',borderRadius:16,padding:18}}><h2 style={{marginTop:0,color:'#5a1624'}}>1. Customer & channel</h2><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))',gap:12}}><SelectField label="Customer relationship" value={clientType} onChange={setClientType} options={CLIENT_TYPES.map(x=>x[0])}/><Field label="Customer name" value={clientName} onChange={setClientName} placeholder="Full name"/><Field label="Phone" value={clientPhone} onChange={setClientPhone}/><Field label="Email" value={clientEmail} onChange={setClientEmail}/><Field label="Organization / property" value={organizationName} onChange={setOrganizationName}/><Field label="City" value={city} onChange={setCity}/><Field label="ZIP" value={zipCode} onChange={setZipCode}/><Field label="Requested date" value={requestedDate} onChange={setRequestedDate} type="date"/></div><div style={{marginTop:12}}><Field label="Service location" value={locationAddress} onChange={setLocationAddress}/></div></div>
   <div style={{background:'#fff',border:'1px solid #e2d6bf',borderRadius:16,padding:18}}><h2 style={{marginTop:0,color:'#5a1624'}}>2. Service</h2><Field label="Search the governed catalog" value={search} onChange={setSearch} placeholder="cleaning, car detailing, notary, events, branding…"/><div style={{marginTop:12,display:'grid',gap:9,maxHeight:330,overflowY:'auto'}}>{loading?<div>Loading catalog…</div>:filtered.map(s=><button type="button" key={s.sku} onClick={()=>{setServiceSku(s.sku);setResult(null)}} style={{textAlign:'left',borderRadius:12,padding:12,border:s.sku===serviceSku?'2px solid #6b1f2b':'1px solid #e3d6bd',background:s.sku===serviceSku?'#fbf0d7':'#fff'}}><strong style={{color:'#5a1624'}}>{s.name}</strong><div style={{fontSize:12,color:'#7b686d',marginTop:3}}>{s.sku} · {s.service_family||'Service'} · {s.publicPrice}</div></button>)}</div></div>
   <div style={{background:'#fff',border:'1px solid #e2d6bf',borderRadius:16,padding:18}}><h2 style={{marginTop:0,color:'#5a1624'}}>3. Quote inputs</h2>{service?.quoteQuestions?.length&&<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))',gap:12,marginBottom:16}}>{service.quoteQuestions.map(q=><DynamicQuestion key={q.key} q={q} value={answers[q.key]} onChange={v=>setAnswer(q.key,v)}/>)}</div>}<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(170px,1fr))',gap:12}}><Field label="Working base price" value={answers.manual_base_price} onChange={v=>setAnswer('manual_base_price',v)} type="number" placeholder="Use starting price or set scoped price"/><Field label="Quantity / units" value={answers.quantity} onChange={v=>setAnswer('quantity',v)} type="number"/><Field label="Hours" value={answers.hours} onChange={v=>setAnswer('hours',v)} type="number"/><Field label="Miles one way" value={answers.miles_one_way} onChange={v=>setAnswer('miles_one_way',v)} type="number"/><Field label="Materials cost" value={answers.materials_cost} onChange={v=>setAnswer('materials_cost',v)} type="number"/><Field label="Pass-through cost" value={answers.pass_through_cost} onChange={v=>setAnswer('pass_through_cost',v)} type="number"/><Field label="Tax rate %" value={answers.tax_rate_percent} onChange={v=>setAnswer('tax_rate_percent',v)} type="number"/><Field label="Deposit %" value={answers.deposit_percent} onChange={v=>setAnswer('deposit_percent',v)} type="number"/><label style={{display:'flex',alignItems:'center',gap:8,fontWeight:700}}><input type="checkbox" checked={Boolean(answers.apply_standard_travel)} onChange={e=>setAnswer('apply_standard_travel',e.target.checked)}/> Standard travel rule</label><label style={{display:'flex',alignItems:'center',gap:8,fontWeight:700}}><input type="checkbox" checked={Boolean(answers.rush)} onChange={e=>setAnswer('rush',e.target.checked)}/> 24-hour / rush (+25%)</label></div><div style={{marginTop:12,display:'grid',gap:12}}><Field label="Timeline / urgency" value={timeline} onChange={setTimeline}/><label style={{display:'grid',gap:6,fontWeight:700}}>Customer notes<textarea value={clientNotes} onChange={e=>setClientNotes(e.target.value)} rows={3} style={{borderRadius:10,border:'1px solid #decfae',padding:12}}/></label><label style={{display:'grid',gap:6,fontWeight:700}}>Internal notes<textarea value={internalNotes} onChange={e=>setInternalNotes(e.target.value)} rows={3} style={{borderRadius:10,border:'1px solid #decfae',padding:12}}/></label></div></div>
  </div>
  <aside style={{alignSelf:'start',position:'sticky',top:18}}><div style={{background:'#5a1624',color:'#fff',borderRadius:18,padding:20}}><div style={{fontSize:12,letterSpacing:1.5,fontWeight:900,color:'#efce72'}}>ESTIMATE PREVIEW</div><h2 style={{margin:'7px 0 14px'}}>{service?.name||'Choose a service'}</h2><div style={{padding:14,borderRadius:12,background:'rgba(255,255,255,.08)'}}><div style={{fontSize:13,opacity:.8}}>Customer-facing guidance</div><strong style={{fontSize:21}}>{service?.publicPrice||'—'}</strong></div>{result?<><div style={{display:'grid',gap:7,fontSize:14,marginTop:14}}>{[['Base',result.calculation.baseSubtotal],['Resident discount',-result.calculation.residentDiscount],['Travel',result.calculation.travelFee],['Rush',result.calculation.rushFee],['Materials + sourcing',result.calculation.materials+result.calculation.sourcingFee],['Pass-through',result.calculation.passThrough],['Tax',result.calculation.tax]].map(([l,v])=><div key={l} style={{display:'flex',justifyContent:'space-between'}}><span>{l}</span><strong>${Number(v).toFixed(2)}</strong></div>)}<hr style={{width:'100%',border:0,borderTop:'1px solid rgba(255,255,255,.2)'}}/><div style={{display:'flex',justifyContent:'space-between',fontSize:20}}><span>Total</span><strong>${Number(result.calculation.estimatedTotal).toFixed(2)}</strong></div></div><div style={{marginTop:14,padding:12,borderRadius:10,background:result.calculation.needsReview?'#6f4d18':'#234c31'}}><strong>{result.calculation.needsReview?'Review before sending':'Ready estimate'}</strong><div style={{fontSize:12,marginTop:3}}>{result.calculation.reviewFlags.join(' · ')||'No additional review flags.'}</div></div><div style={{marginTop:12,fontSize:13}}>Saved as <strong>{result.estimate.public_reference}</strong>.</div></>:<p style={{fontSize:13,lineHeight:1.55,color:'#f1e3e5'}}>Use the starting/range price as the customer anchor. Set the working base when the scope is known, then add travel, rush, materials, pass-throughs, tax and deposit as applicable.</p>}<button type="button" disabled={saving||!serviceSku} onClick={buildQuote} style={{width:'100%',marginTop:18,padding:13,borderRadius:11,border:0,background:'#efce72',color:'#35161d',fontWeight:900}}>{saving?'Building estimate…':'Build & Save Estimate'}</button></div></aside></section></div></main>;
}
export default function QuoteBuilderPage(){return <RequireStaffAuth><QuoteBuilder/></RequireStaffAuth>}
