import React,{useEffect,useMemo,useState} from 'react';
import {ArrowRight,ChevronDown,Search,X} from 'lucide-react';
import {getFamilyVisuals} from '../data/serviceVisuals2026.js';
const FAMILY_ALIASES={'01A Home & Cleaning':'Home & Cleaning','HOME':'Home & Cleaning','01B Pet Care & Household Pet Support':'Pet Care','PET':'Pet Care','Pet Care':'Pet Care','01D Household Concierge':'Household Concierge','CONCIERGE':'Household Concierge','01E Move & Household Transition':'Move & Household Transition','MOVE':'Move & Household Transition','AUTOMOTIVE':'Mobile Automotive & Vehicle Care','Mobile Automotive & Vehicle Care':'Mobile Automotive & Vehicle Care','Administrative & Business Operations':'Administrative & Business Operations','BUSINESS ADMIN':'Administrative & Business Operations','Creative Design & Production':'Creative Design & Production','CREATIVE PRODUCTION':'Creative Design & Production','EVENT':'Events & Experiences','Experiences & Resident Programming':'Events & Experiences','REAL ESTATE':'Real Estate & Closing Support','Real Estate & Closing Support':'Real Estate & Closing Support','SEASONAL':'Seasonal & Holiday Home Services','Seasonal & Holiday Home Services':'Seasonal & Holiday Home Services','ADD-ONS':'Add-Ons','PACKAGES':'Packages & Bundles','RECURRING':'Recurring Services'};
const familyLabel=(family='')=>FAMILY_ALIASES[family]||family.replace(/^\d+[A-Z]?\s+/,'').replace(/^\d+[A-Z]\s+/,'');
const baseServiceName=(name='')=>name.replace(/\s+(1BR|2BR|3BR|4BR)$/i,'').replace(/\s+—\s+(30|60)\s*min$/i,'').replace(/\s+—\s+(7|14|30)\s*Days$/i,'');
const priceValue=s=>Number(s?.price||0);
export default function CommercialCatalogPage(){
 const [services,setServices]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[q,setQ]=useState(''),[openFamily,setOpenFamily]=useState('');
 useEffect(()=>{fetch('/api/verify-commercial-intent?catalog=1').then(async r=>{const d=await r.json();if(!r.ok||!d.success)throw new Error(d.error||'We could not load services right now.');setServices(d.services||[])}).catch(e=>setError(e.message)).finally(()=>setLoading(false));},[]);
 const families=useMemo(()=>{const map=new Map();services.forEach(s=>{const key=familyLabel(s.family||'Services');if(!map.has(key))map.set(key,[]);map.get(key).push(s);});return Array.from(map.entries()).sort((a,b)=>a[0].localeCompare(b[0]));},[services]);
 const visibleFamilies=useMemo(()=>{const needle=q.trim().toLowerCase();if(!needle)return families;return families.map(([family,items])=>[family,items.filter(s=>`${s.name} ${s.family}`.toLowerCase().includes(needle))]).filter(([,items])=>items.length);},[families,q]);
 const groupedServices=items=>{const map=new Map();items.forEach(s=>{const base=baseServiceName(s.name);if(!map.has(base))map.set(base,[]);map.get(base).push(s);});return Array.from(map.entries()).sort((a,b)=>a[0].localeCompare(b[0]));};
 const money=n=>`$${Number(n||0).toLocaleString('en-US',{maximumFractionDigits:2})}`;
 return <div className="min-h-screen bg-[#fffaf1] text-[#302226]">
  <section className="bg-[#5a1422] text-white"><div className="max-w-6xl mx-auto px-5 sm:px-8 py-16 md:py-24 text-center"><p className="text-[#efce72] font-black uppercase tracking-[.2em] text-xs">DANI DECLARES • SERVICES</p><h1 className="mt-4 text-4xl sm:text-5xl md:text-6xl font-black leading-[1.05]">Services designed to look as polished as the work itself.</h1><p className="max-w-3xl mx-auto mt-6 text-lg md:text-xl text-[#f0e2e4] leading-relaxed">Explore the service areas, open the one that fits your need, and choose the exact service or option you want to request. Georgia service area.</p></div></section>
  <main className="max-w-7xl mx-auto px-5 sm:px-8 py-10 md:py-14">
   {error&&<div className="p-4 mb-6 rounded-xl bg-red-50 border border-red-200 text-red-800">{error}</div>}
   <div className="max-w-3xl mx-auto mb-12"><div className="relative"><Search className="absolute left-4 top-3.5 w-5 h-5 text-[#8c777b]"/><input value={q} onChange={e=>{setQ(e.target.value);setOpenFamily('')}} placeholder="Search services…" aria-label="Search services" className="w-full pl-12 pr-12 py-4 rounded-2xl bg-white border border-[#e3d2a8] text-[#35272b] shadow-sm focus:outline-none focus:ring-2 focus:ring-[#d2a83f]"/>{q&&<button type="button" onClick={()=>setQ('')} aria-label="Clear search" className="absolute right-3 top-2.5 rounded-xl p-2 text-[#756469] hover:bg-[#f8ecd0]"><X className="w-5 h-5"/></button>}</div><p className="mt-3 text-center text-xs text-[#756469]">Browse by service area. Exact options appear inside each service.</p></div>
   {loading?<div className="py-20 text-center text-[#756469]">Loading services…</div>:<><div className="mb-6"><p className="text-xs font-black uppercase tracking-[.14em] text-[#a8791c]">Service areas</p><h2 className="mt-1 text-3xl md:text-4xl font-black text-[#5a1624]">What do you need handled?</h2></div>
    {visibleFamilies.length===0?<div className="rounded-2xl bg-white border border-[#ead9b3] p-10 text-center"><h2 className="text-xl font-black text-[#5a1624]">No matching services</h2><p className="mt-2 text-[#756469]">Try a broader search or clear the search.</p></div>:<div className="grid md:grid-cols-2 xl:grid-cols-3 gap-6">{visibleFamilies.map(([family,items])=>{const isOpen=openFamily===family;const groups=groupedServices(items);const visual=getFamilyVisuals(family)[0];return <section key={family} className={`group rounded-3xl bg-white border overflow-hidden transition-all ${isOpen?'border-[#caa24a] shadow-xl':'border-[#ead9b3] shadow-sm hover:-translate-y-0.5 hover:shadow-lg'}`}><button type="button" onClick={()=>setOpenFamily(isOpen?'':family)} className="w-full text-left"><div className="relative h-56 overflow-hidden bg-[#eadfce]"><img src={visual?.imageUrl||'/dd-monogram.svg'} alt={visual?.altText||`${family} services`} className="w-full h-full object-cover transition-transform duration-700 group-hover:scale-105" loading="lazy"/><div className="absolute inset-0 bg-gradient-to-t from-black/75 via-black/10 to-transparent"/><div className="absolute inset-x-5 bottom-5 flex items-end justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-[#f0cf78]">Service area</p><h3 className="mt-1 text-2xl font-black text-white drop-shadow">{family}</h3></div><span className="rounded-full bg-white/15 backdrop-blur-sm p-2"><ChevronDown className={`w-5 h-5 text-white transition-transform ${isOpen?'rotate-180':''}`}/></span></div></div><div className="px-5 py-4 flex items-center justify-between"><span className="text-sm font-semibold text-[#756469]">{groups.length} service{groups.length===1?'':'s'}</span><span className="text-xs font-black uppercase tracking-wider text-[#855d15]">{isOpen?'Close':'Explore'}</span></div></button>{isOpen&&<div className="border-t border-[#ead9b3] bg-[#fffdf8] p-4 space-y-3">{groups.map(([base,variants])=>{const sorted=[...variants].sort((a,b)=>priceValue(a)-priceValue(b));const hasVariants=sorted.length>1;const lowest=sorted[0];return <div key={base} className="rounded-2xl border border-[#ead9b3] bg-white p-4 hover:border-[#caa24a] transition"><div className="flex items-start justify-between gap-4"><div><h4 className="font-black text-[#5a1624] leading-tight">{base}</h4><p className="mt-1 text-xs text-[#806d72]">{hasVariants?`${sorted.length} options available`:lowest.unit||'Service'}</p></div><span className="shrink-0 font-black text-[#6b1f2b] text-sm">{hasVariants?`From ${money(lowest.price)}`:lowest.pricingLabel}</span></div><a href={`/request-service?service=${encodeURIComponent(lowest.serviceId)}`} className="mt-3 inline-flex items-center gap-1 text-xs font-black uppercase tracking-wide text-[#855d15] hover:text-[#5a1624]">{hasVariants?'Choose options':'Request service'}<ArrowRight className="w-4 h-4"/></a></div>;})}</div>}</section>;})}</div>}
    <div className="max-w-3xl mx-auto mt-10 rounded-2xl bg-[#f8ecd0] border border-[#dfc78e] p-6"><p className="font-black text-[#5a1624]">One service area. One clear next step.</p><p className="mt-2 text-sm leading-6 text-[#6e5b60]">Variants such as bedroom count, duration, quantity, or project size stay inside the request flow instead of creating a separate public button for every variation.</p></div>
   </>}
  </main>
 </div>;
}
