import React,{useEffect,useMemo,useState} from 'react';
import {useLocation,Link} from 'react-router-dom';
import {ArrowRight,Search,X} from 'lucide-react';
import {getFamilyVisuals} from '../data/serviceVisuals2026.js';
import {AUDIENCE_LABELS,AUDIENCE_BUCKETS,groupServicesByBucket,groupedServices} from '../data/serviceCatalogFamilies.js';

export default function CommercialCatalogPage(){
 const location=useLocation();
 const audience=useMemo(()=>new URLSearchParams(location.search).get('audience'),[location.search]);
 const audienceBuckets=audience&&AUDIENCE_BUCKETS[audience];
 const [services,setServices]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[q,setQ]=useState('');
 useEffect(()=>{fetch('/api/verify-commercial-intent?catalog=1').then(async r=>{const d=await r.json();if(!r.ok||!d.success)throw new Error(d.error||'We could not load services right now.');setServices(d.services||[])}).catch(e=>setError(e.message)).finally(()=>setLoading(false));},[]);
 const bucketGroups=useMemo(()=>groupServicesByBucket(services),[services]);
 const audienceFilteredGroups=useMemo(()=>{if(!audienceBuckets)return bucketGroups;return bucketGroups.filter(({bucket})=>audienceBuckets.includes(bucket.key));},[bucketGroups,audienceBuckets]);
 const visibleGroups=useMemo(()=>{const needle=q.trim().toLowerCase();if(!needle)return audienceFilteredGroups;return audienceFilteredGroups.map(({bucket,items})=>({bucket,items:items.filter(s=>`${s.name} ${s.family}`.toLowerCase().includes(needle))})).filter(({items})=>items.length);},[audienceFilteredGroups,q]);
 return <div className="min-h-screen bg-[#fffaf1] text-[#302226]">
  <section className="bg-[#5a1422] text-white"><div className="max-w-6xl mx-auto px-5 sm:px-8 py-16 md:py-24 text-center"><p className="text-[#efce72] font-black uppercase tracking-[.2em] text-xs">DANI DECLARES • SERVICES</p><h1 className="mt-4 text-4xl sm:text-5xl md:text-6xl font-black leading-[1.05] text-white">What can we handle for you?</h1><p className="max-w-3xl mx-auto mt-6 text-lg md:text-xl text-[#f0e2e4] leading-relaxed">Choose the type of work you need handled. You'll see the available services, pricing, and request options inside each area. Georgia service area.</p></div></section>
  <main className="max-w-7xl mx-auto px-5 sm:px-8 py-10 md:py-14">
   {error&&<div className="p-4 mb-6 rounded-xl bg-red-50 border border-red-200 text-red-800">{error}</div>}
   {audienceBuckets&&<div className="max-w-3xl mx-auto mb-6 flex flex-wrap items-center justify-center gap-3 rounded-2xl bg-[#f8ecd0] border border-[#dfc78e] px-5 py-3 text-sm"><span className="text-[#5a1624]">Showing services for <strong>{AUDIENCE_LABELS[audience]||audience}</strong></span><Link to="/catalog" className="font-black uppercase tracking-wide text-xs text-[#855d15] hover:text-[#5a1624]">View all services</Link></div>}
   <div className="max-w-3xl mx-auto mb-12"><div className="relative"><Search className="absolute left-4 top-3.5 w-5 h-5 text-[#8c777b]"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search services…" aria-label="Search services" className="w-full pl-12 pr-12 py-4 rounded-2xl bg-white border border-[#e3d2a8] text-[#35272b] shadow-sm focus:outline-none focus:ring-2 focus:ring-[#d2a83f]"/>{q&&<button type="button" onClick={()=>setQ('')} aria-label="Clear search" className="absolute right-3 top-2.5 rounded-xl p-2 text-[#756469] hover:bg-[#f8ecd0]"><X className="w-5 h-5"/></button>}</div><p className="mt-3 text-center text-xs text-[#756469]">Browse by service area. Exact options appear inside each one.</p></div>
   {loading?<div className="py-20 text-center text-[#756469]">Loading services…</div>:<><div className="mb-6"><p className="text-xs font-black uppercase tracking-[.14em] text-[#a8791c]">Service areas</p><h2 className="mt-1 text-3xl md:text-4xl font-black text-[#5a1624]">What do you need handled?</h2></div>
    {visibleGroups.length===0?<div className="rounded-2xl bg-white border border-[#ead9b3] p-10 text-center"><h2 className="text-xl font-black text-[#5a1624]">No matching services</h2><p className="mt-2 text-[#756469]">Try a broader search{audienceBuckets?', or ':' or clear the search.'}{audienceBuckets&&<Link to="/catalog" className="font-black text-[#855d15] hover:text-[#5a1624]">view all services</Link>}{audienceBuckets?'.':''}</p></div>:<div className="grid md:grid-cols-2 xl:grid-cols-3 gap-6">{visibleGroups.map(({bucket,items})=>{const groups=groupedServices(items);const visual=getFamilyVisuals(bucket.visualFamily)[0];return <Link key={bucket.key} to={`/services/category/${bucket.key}`} className="group rounded-3xl bg-white border border-[#ead9b3] shadow-sm overflow-hidden transition-all hover:-translate-y-0.5 hover:shadow-lg hover:border-[#caa24a]"><div className="relative h-56 overflow-hidden bg-[#eadfce]"><img src={visual?.imageUrl||'/dd-monogram.svg'} alt={visual?.altText||`${bucket.label} services`} className="w-full h-full object-cover transition-transform duration-700 group-hover:scale-105" loading="lazy"/><div className="absolute inset-0 bg-gradient-to-t from-black/75 via-black/10 to-transparent"/><div className="absolute inset-x-5 bottom-5"><p className="text-[10px] font-black uppercase tracking-[.18em] text-[#f0cf78]">Service area</p><h3 className="mt-1 text-2xl font-black text-white drop-shadow">{bucket.label}</h3></div></div><div className="px-5 py-4"><p className="text-sm text-[#6e5b60] leading-snug">{bucket.tagline}</p><div className="mt-3 flex items-center justify-between"><span className="text-sm font-semibold text-[#756469]">{groups.length} service{groups.length===1?'':'s'}</span><span className="inline-flex items-center gap-1 text-xs font-black uppercase tracking-wider text-[#855d15] group-hover:text-[#5a1624]">Explore<ArrowRight className="w-4 h-4"/></span></div></div></Link>;})}</div>}
    <div className="max-w-3xl mx-auto mt-10 rounded-2xl bg-[#f8ecd0] border border-[#dfc78e] p-6"><p className="font-black text-[#5a1624]">One service area. One clear next step.</p><p className="mt-2 text-sm leading-6 text-[#6e5b60]">Open a service area to see its exact services, options, and pricing.</p></div>
   </>}
  </main>
 </div>;
}
