import React,{useEffect,useMemo,useState} from 'react';
import {ArrowRight,Search} from 'lucide-react';

const GROUPS={
 '01':'Home & Resident Support','02':'Property Operations','03':'Real Estate Support','04':'Business & Administrative Support','05':'Documents & Mobile Notary','06':'Digital & Business Setup','07':'Marketing & Media','08':'Business Development & Growth','09':'Classes & Training','10':'Events & Experiences','11':'Print, Branding & Merchandise','12':'Courier, Sourcing & Field Support','13':'Government & Institutional Support'
};

export default function CommercialCatalogPage(){
 const [services,setServices]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[q,setQ]=useState(''),[group,setGroup]=useState('ALL');
 useEffect(()=>{fetch('/api/verify-commercial-intent?catalog=1').then(async r=>{const d=await r.json();if(!r.ok||!d.success)throw new Error('We could not load services right now. Please try again or contact us.');setServices(d.services||[])}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
 const groups=useMemo(()=>['ALL',...Array.from(new Set(services.map(s=>s.division))).sort()],[services]);
 const filtered=useMemo(()=>services.filter(s=>{const text=`${s.name} ${s.family||''} ${GROUPS[s.division]||''}`.toLowerCase();return(group==='ALL'||group===s.division)&&(!q||text.includes(q.toLowerCase()))}),[services,q,group]);
 return <div className="bg-[#fffaf1] text-[#302226] min-h-screen"><section className="bg-[#5a1422] text-white"><div className="max-w-6xl mx-auto px-5 sm:px-8 py-14 md:py-20 text-center"><p className="text-[#efce72] font-black uppercase tracking-[.2em] text-xs">SERVICES</p><h1 className="mt-3 text-4xl sm:text-5xl font-black">Find the support you need.</h1><p className="max-w-3xl mx-auto mt-4 text-lg text-[#f0e2e4]">Search across home, property, business, events, documents, creative production, logistics and more. If pricing depends on scope, we’ll confirm it before you pay.</p></div></section><div className="max-w-7xl mx-auto px-5 sm:px-8 py-10">
 {error&&<div className="p-4 mb-6 rounded-xl bg-red-50 border border-red-200 text-red-800">{error}</div>}
 <div className="grid md:grid-cols-[1fr_260px] gap-4 mb-7"><div className="relative"><Search className="absolute left-4 top-3.5 w-5 h-5 text-[#8c777b]"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search services — cleaning, notary, branding, events…" className="w-full pl-12 pr-4 py-3.5 rounded-xl bg-white border border-[#e3d2a8] text-[#35272b] shadow-sm"/></div><select value={group} onChange={e=>setGroup(e.target.value)} className="px-4 py-3.5 rounded-xl bg-white border border-[#e3d2a8] text-[#4e1621] font-bold shadow-sm">{groups.map(d=><option key={d} value={d}>{d==='ALL'?'All service categories':GROUPS[d]||'Other services'}</option>)}</select></div>
 {loading?<div className="py-16 text-center text-[#756469]">Loading services…</div>:<><div className="mb-5 text-sm text-[#756469]">{filtered.length} services available to request</div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-5">{filtered.map(s=><article key={s.serviceId} className="rounded-2xl bg-white border border-[#ead9b3] p-6 shadow-sm hover:shadow-lg hover:-translate-y-0.5 transition"><div className="text-[#a8791c] text-xs font-extrabold uppercase tracking-[.1em]">{GROUPS[s.division]||'DANI DECLARES Service'}</div><h2 className="text-xl font-black text-[#5a1624] mt-2">{s.name}</h2>{s.family&&<p className="text-sm text-[#766369] mt-2">{s.family}</p>}<div className="mt-5 flex items-center justify-between gap-3"><span className="text-[#6b1f2b] font-black">{s.pricingLabel||'Request a quote'}</span><a href={`/request-service?service=${encodeURIComponent(s.serviceId)}`} className="inline-flex items-center gap-1 rounded-lg bg-[#6b1f2b] px-3.5 py-2 text-sm font-bold text-white">Select <ArrowRight className="w-4 h-4"/></a></div></article>)}</div></>}
 <div className="mt-12 rounded-2xl bg-[#f8ecd0] border border-[#dfc78e] p-7 text-center"><h2 className="text-2xl font-black text-[#5a1624]">Don’t see exactly what you need?</h2><p className="mt-2 text-[#6e5b60]">Tell us the outcome you’re trying to achieve. We may be able to coordinate it even if you don’t know the service name.</p><a href="/request-service" className="mt-5 inline-flex rounded-xl bg-[#6b1f2b] px-6 py-3 text-white font-black">Tell us what you need</a></div>
 </div></div>;
}
