import React from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, Building2, Home, Landmark, MapPin, Sparkles, Store, CheckCircle2 } from 'lucide-react';

const audiences=[
 {icon:Home,title:'Residents',desc:'Home care, errands, documents, events, organization and everyday support.',link:'/catalog?audience=residents'},
 {icon:Building2,title:'Property Management',desc:'Turns, inspections, make-ready support, field operations and resident programs.',link:'/services/property'},
 {icon:MapPin,title:'Real Estate',desc:'Listing readiness, open houses, transaction support, signage, media and closing logistics.',link:'/real-estate'},
 {icon:Store,title:'Businesses',desc:'Administrative support, digital setup, marketing, branding, print, merch and growth support.',link:'/services/business-solutions'},
 {icon:Landmark,title:'Government & Institutions',desc:'Facilities, administrative, document, field and procurement support.',link:'/industries/government'},
];

const popular=[
 ['Home & Household Support','Cleaning, organization, laundry, home watch, plant care and concierge help.'],
 ['Property Operations','Turns, inspections, photo documentation, punch-list coordination and readiness support.'],
 ['Business Support','Administrative help, research, systems setup, marketing, branding and growth support.'],
 ['Events & Experiences','Planning, coordination, setup, décor, logistics, merchandise and community programming.'],
 ['Print, Branding & Merch','Logos, flyers, business cards, signage, apparel, labels, gifts and event merchandise.'],
 ['Courier & Field Support','Documents, keys, supplies, pickups, deliveries, sourcing and field errands.'],
];

export default function HomePage(){return <div className="bg-[#fffaf1] text-[#302226]">
 <section className="relative overflow-hidden border-b border-[#e3d2a8] bg-gradient-to-br from-[#fffaf1] via-[#fbf0da] to-[#f5e3bd]">
  <div className="max-w-7xl mx-auto px-5 sm:px-8 py-16 md:py-24 grid lg:grid-cols-[1.08fr_.92fr] gap-12 items-center">
   <div><div className="inline-flex items-center gap-2 rounded-full bg-[#6b1f2b]/10 px-4 py-2 text-[#6b1f2b] text-sm font-bold"><Sparkles className="w-4 h-4"/>Operations • Execution • Support</div><h1 className="mt-6 text-4xl sm:text-6xl font-black leading-[1.02] text-[#551521]">One call. More gets handled.</h1><p className="mt-6 text-lg sm:text-xl leading-relaxed text-[#5e4b50] max-w-2xl">DANI DECLARES helps residents, property teams, real estate professionals, businesses and institutions get the work around life and operations done—from everyday support to projects, events, logistics and business execution.</p><div className="mt-8 flex flex-col sm:flex-row gap-3"><Link to="/catalog" className="inline-flex items-center justify-center rounded-xl bg-[#6b1f2b] px-7 py-4 text-white font-extrabold">Browse Services <ArrowRight className="w-5 h-5 ml-2"/></Link><Link to="/request-service" className="inline-flex items-center justify-center rounded-xl border-2 border-[#b68a2d] bg-white/70 px-7 py-4 text-[#6b1f2b] font-extrabold">Book / Request Service</Link></div><p className="mt-5 text-sm text-[#7d666c]">Serving Georgia and South Carolina. Availability varies by service and location.</p></div>
   <div className="rounded-3xl bg-white/75 border border-[#dfc98d] shadow-xl p-5 sm:p-8"><img src="/logo-script.png" alt="DANI DECLARES LLC" className="w-full max-w-md mx-auto rounded-2xl"/><div className="mt-6 grid grid-cols-2 gap-3 text-sm">{['Home','Property','Business','Events'].map(x=><div key={x} className="rounded-xl bg-[#fff6e5] border border-[#ead7a7] p-3 text-center font-bold text-[#6b1f2b]">{x}</div>)}</div></div>
  </div>
 </section>
 <section className="max-w-7xl mx-auto px-5 sm:px-8 py-16"><div className="text-center max-w-3xl mx-auto"><p className="text-[#a97a19] font-extrabold uppercase tracking-[.18em] text-xs">Who we serve</p><h2 className="mt-3 text-3xl sm:text-4xl font-black text-[#551521]">Start with what you need—not how our company is organized.</h2><p className="mt-4 text-[#6e5b60]">Choose the path that fits you. We handle the coordination behind the scenes.</p></div><div className="mt-10 grid sm:grid-cols-2 lg:grid-cols-5 gap-4">{audiences.map(a=><Link key={a.title} to={a.link} className="group rounded-2xl border border-[#ead9b3] bg-white p-6 shadow-sm hover:-translate-y-1 hover:shadow-lg transition"><a.icon className="w-8 h-8 text-[#b48628]"/><h3 className="mt-4 text-lg font-black text-[#601827]">{a.title}</h3><p className="mt-2 text-sm leading-relaxed text-[#6d5b60]">{a.desc}</p><span className="mt-5 inline-flex items-center text-sm font-bold text-[#8d6418]">Explore <ArrowRight className="w-4 h-4 ml-1"/></span></Link>)}</div></section>
 <section className="bg-[#5a1422] text-white"><div className="max-w-7xl mx-auto px-5 sm:px-8 py-16"><div className="max-w-3xl"><p className="text-[#f0cf78] font-extrabold uppercase tracking-[.18em] text-xs">Popular ways we help</p><h2 className="mt-3 text-3xl sm:text-4xl font-black">Services built around outcomes.</h2><p className="mt-4 text-[#f2e7e0]">Book straightforward services directly when pricing is set. For larger or variable-scope work, send the details and we’ll confirm a quote before you pay.</p></div><div className="mt-10 grid md:grid-cols-2 lg:grid-cols-3 gap-5">{popular.map(([title,desc])=><div key={title} className="rounded-2xl bg-white/10 border border-white/15 p-6"><CheckCircle2 className="w-6 h-6 text-[#e6bf58]"/><h3 className="mt-4 text-xl font-extrabold">{title}</h3><p className="mt-2 text-sm leading-relaxed text-[#eadede]">{desc}</p></div>)}</div><div className="mt-10"><Link to="/catalog" className="inline-flex items-center rounded-xl bg-[#d2a83f] px-7 py-4 text-[#45101b] font-black">View All Services <ArrowRight className="w-5 h-5 ml-2"/></Link></div></div></section>
 <section className="max-w-6xl mx-auto px-5 sm:px-8 py-16"><div className="grid md:grid-cols-3 gap-6">{[['1','Choose what you need','Browse services or tell us what outcome you’re trying to achieve.'],['2','Share the details','Tell us the location, timing and anything we need to price or schedule correctly.'],['3','Confirm & get it handled','Pay online when eligible, or approve your quote. We confirm next steps and coordinate delivery.']].map(([n,t,d])=><div key={n} className="rounded-2xl bg-white border border-[#ead9b3] p-7"><div className="text-3xl font-black text-[#c79a32]">{n}</div><h3 className="mt-3 text-xl font-black text-[#5c1725]">{t}</h3><p className="mt-2 text-[#6e5a60] leading-relaxed">{d}</p></div>)}</div><div className="mt-10 text-center"><h2 className="text-3xl font-black text-[#551521]">Need something handled today?</h2><p className="mt-3 text-[#6f5c61]">Tell us what you need. If it’s a fit, we’ll move quickly.</p><Link to="/request-service" className="mt-6 inline-flex items-center rounded-xl bg-[#6b1f2b] px-8 py-4 text-white font-black">Request Service <ArrowRight className="w-5 h-5 ml-2"/></Link></div></section>
 </div>}
