import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import { supabase } from '../lib/supabaseClient.js';
import './PortalAccessPage.css';

const OPTIONS = [
  { key:'resident', title:'Resident', desc:'I live here and want concierge services.', portal:'Resident Portal', relationship:'RESIDENT', channel:'CH01' },
  { key:'apartment_resident', title:'Apartment Resident', desc:'I am a resident of a property we serve.', portal:'Resident Portal', relationship:'APARTMENT_RESIDENT', channel:'CH01' },
  { key:'property_manager', title:'Property Manager / Apartment', desc:'I manage properties, units, turns or resident programs.', portal:'Property Operations Portal', relationship:'PROPERTY_MANAGER', channel:'CH02' },
  { key:'real_estate', title:'Real Estate Office / Brokerage', desc:'I need listing, transaction or agent support.', portal:'Real Estate Client Portal', relationship:'REAL_ESTATE', channel:'CH03' },
  { key:'business', title:'Business', desc:'I need business, workplace, print or operational support.', portal:'Business Client Portal', relationship:'BUSINESS', channel:'CH04' },
  { key:'government', title:'Government / Institution', desc:'I represent a procurement or institutional organization.', portal:'Procurement Portal', relationship:'GOVERNMENT_INSTITUTION', channel:'CH05' },
  { key:'provider', title:'Provider / Contractor', desc:'I want to qualify to fulfill DANI DECLARES work.', portal:'Provider Application', relationship:'PROVIDER', channel:null },
];

export default function PortalAccessPage() {
  const [mode,setMode]=useState('choose'); const [selected,setSelected]=useState(null); const [form,setForm]=useState({firstName:'',lastName:'',email:'',phone:'',organization:'',address:'',city:'',state:'GA',zip:'',services:'',password:'',confirm:''}); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [done,setDone]=useState('');
  const update=(e)=>setForm({...form,[e.target.name]:e.target.value});
  const choose=(option)=>{setSelected(option);setMode('form');setError('');};
  const submit=async(e)=>{e.preventDefault();setError('');setDone(''); if(form.password.length<8)return setError('Use a password with at least 8 characters.'); if(form.password!==form.confirm)return setError('Passwords do not match.'); setBusy(true);
    const {data,error:authError}=await supabase.auth.signUp({email:form.email.trim(),password:form.password,options:{data:{first_name:form.firstName,last_name:form.lastName,relationship_type:selected.relationship,channel_code:selected.channel}}});
    if(authError){setBusy(false);return setError(authError.message);} if(!data.user){setBusy(false);return setError('Account could not be created.');}
    const portalRole=selected.key==='provider'?'provider':selected.key==='property_manager'?'property_manager':selected.key==='government'?'procurement':selected.key==='resident'||selected.key==='apartment_resident'?'resident':'customer';
    const {error:identityError}=await supabase.from('dd_portal_identities').insert({auth_user_id:data.user.id,portal_role:portalRole,is_active:true});
    if(identityError){setBusy(false);return setError(`Account created, but portal setup needs attention: ${identityError.message}`);}
    if(selected.key==='provider'){
      const {error:providerError}=await supabase.from('dd_provider_applications').insert({applicant_user_id:data.user.id,application_status:'SUBMITTED',applicant_type:form.organization?'BUSINESS':'INDIVIDUAL',legal_name:form.organization||`${form.firstName} ${form.lastName}`,contact_first_name:form.firstName,contact_last_name:form.lastName,contact_email:form.email,contact_phone:form.phone,physical_address:form.address,service_area:form.city&&form.state?`${form.city}, ${form.state}`:form.state,service_notes:form.services,source:'PUBLIC_APPLICATION',referral_source:'WEBSITE_PORTAL',consent_at:new Date().toISOString(),submitted_at:new Date().toISOString()});
      if(providerError){setBusy(false);return setError(`Account created, but provider application needs attention: ${providerError.message}`);}
    } else {
      const {error:intakeError}=await supabase.from('dd_portal_onboarding_intakes').insert({auth_user_id:data.user.id,portal_role:portalRole,relationship_type:selected.relationship,channel_code:selected.channel,organization_name:form.organization||null,first_name:form.firstName,last_name:form.lastName,email:form.email,phone:form.phone,address:form.address,city:form.city,state_code:form.state,zip_code:form.zip,service_area:form.city&&form.state?`${form.city}, ${form.state}`:null,requested_services:form.services.split(',').map(s=>s.trim()).filter(Boolean),intake_data:{entry_type:selected.key,portal_label:selected.portal},status:'SUBMITTED'});
      if(intakeError){setBusy(false);return setError(`Account created, but onboarding data needs attention: ${intakeError.message}`);}
    }
    setBusy(false);setDone(data.session?'Your account is ready.':'Your account is created. Check your email to confirm it, then sign in.');setMode('done');
  };
  if(mode==='choose')return <main className="portal-access"><div className="portal-access-inner"><p className="portal-kicker">DANI DECLARES DIGITAL FRONT DOOR</p><h1>Choose your DANI DECLARES workspace</h1><p className="portal-lede">No phone call required. Create the account that matches your relationship with DANI DECLARES. We collect the information needed for that relationship and route it into the appropriate operating records.</p><div className="portal-option-grid">{OPTIONS.map(o=><button key={o.key} className="portal-option" onClick={()=>choose(o)}><span className="portal-option-title">{o.title}</span><span>{o.desc}</span><small>{o.portal}</small></button>)}</div><p className="portal-existing">Already have an account? <Link to="/portal/login">Sign in</Link></p></div></main>;
  if(mode==='done')return <main className="portal-access"><div className="portal-success-card"><p className="portal-kicker">WELCOME TO DANI DECLARES</p><h1>{selected.portal}</h1><p>{done}</p><div className="portal-success-actions"><Link className="portal-primary" to="/portal/login">Sign in</Link><Link className="portal-secondary" to="/">Return to website</Link></div></div></main>;
  return <main className="portal-access"><div className="portal-form-card"><button className="portal-back" onClick={()=>setMode('choose')}>← Choose a different relationship</button><p className="portal-kicker">ACCOUNT SETUP</p><h1>{selected.title}</h1><p>{selected.desc}</p><form onSubmit={submit}><div className="portal-form-grid"><label>First name<input name="firstName" required value={form.firstName} onChange={update}/></label><label>Last name<input name="lastName" required value={form.lastName} onChange={update}/></label><label>Email<input type="email" name="email" required value={form.email} onChange={update}/></label><label>Phone<input name="phone" value={form.phone} onChange={update}/></label><label className="portal-wide">Organization / Company<input name="organization" value={form.organization} onChange={update}/></label><label className="portal-wide">Address<input name="address" value={form.address} onChange={update}/></label><label>City<input name="city" value={form.city} onChange={update}/></label><label>State<input name="state" maxLength="2" value={form.state} onChange={update}/></label><label>ZIP<input name="zip" value={form.zip} onChange={update}/></label><label className="portal-wide">Services / capabilities / what you need<textarea name="services" rows="4" value={form.services} onChange={update} placeholder="Separate multiple items with commas."/></label><label>Password<input type="password" name="password" minLength="8" required value={form.password} onChange={update}/></label><label>Confirm password<input type="password" name="confirm" minLength="8" required value={form.confirm} onChange={update}/></label></div>{error&&<div className="portal-error">{error}</div>}<button className="portal-primary portal-submit" disabled={busy}>{busy?'Creating account…':'Create account'}</button></form><p className="portal-privacy">Your information is used to establish the correct customer/provider relationship and route your requests into the DANI DECLARES operating system. Access is permission-based.</p></div></main>;
}
