import React, { useMemo, useState } from 'react';
import { Sparkles, CheckCircle2, ArrowRight, ShieldCheck, CreditCard } from 'lucide-react';
import { OPERATIONS_CHANNELS } from '../lib/operations/intakeRouting2026';
import { getCommercialRecord, listCanonicalOffers } from '../config/commercialRegistry';

const CHANNEL_OPTIONS = [
  { value: OPERATIONS_CHANNELS.B2C, label: 'Resident Concierge — direct resident' },
  { value: OPERATIONS_CHANNELS.B2B_APT, label: 'Property Management & Apartments' },
  { value: OPERATIONS_CHANNELS.B2B_RE, label: 'Real Estate Offices & Brokerages' },
  { value: OPERATIONS_CHANNELS.B2B, label: 'Businesses' },
  { value: OPERATIONS_CHANNELS.B2G, label: 'Government & Institutional Procurement' },
];
const RESIDENT_SUBCHANNELS = [{ value:'CH01-A',label:'CH01-A Regular Resident' },{ value:'CH01-B',label:'CH01-B Apartment Resident' }];
const LAUNCH_OFFERS = listCanonicalOffers();

export default function RequestServicePage() {
  const requestedServiceId = useMemo(() => typeof window === 'undefined' ? '' : new URLSearchParams(window.location.search).get('service') || '', []);
  const paid = useMemo(() => typeof window !== 'undefined' && new URLSearchParams(window.location.search).get('paid') === '1', []);
  const selectedOffer = getCommercialRecord(requestedServiceId);
  const [formData,setFormData] = useState({name:'',email:'',phone:'',channelType:OPERATIONS_CHANNELS.B2C,subchannelCode:'CH01-A',category:'HOUSEHOLD_SUPPORT',organizationName:'',locationAddress:'',timeline:'',budgetRange:'',details:'',serviceId:requestedServiceId});
  const [loading,setLoading]=useState(false); const [submitted,setSubmitted]=useState(false); const [error,setError]=useState(''); const [routing,setRouting]=useState(null); const [commercial,setCommercial]=useState(null); const [requestId,setRequestId]=useState(''); const [checkoutLoading,setCheckoutLoading]=useState(false);
  const handleChange=e=>setFormData(c=>({...c,[e.target.name]:e.target.value}));
  const handleSubmit=async e=>{e.preventDefault();setLoading(true);setError('');try{
    let verifiedCommercial=null;
    if(formData.serviceId){const vr=await fetch('/api/verify-commercial-intent',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({serviceId:formData.serviceId,isResident:false})});verifiedCommercial=await vr.json();if(!vr.ok||!verifiedCommercial.success)throw new Error(verifiedCommercial.error||'Commercial validation failed.');setCommercial(verifiedCommercial);}
    const res=await fetch('/api/intake-webhook',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...formData,serviceType:selectedOffer?.name||formData.category,pricingServiceId:formData.serviceId||null,commercialIntent:verifiedCommercial?{serviceId:formData.serviceId,frozenPriceSnapshot:verifiedCommercial.frozenPriceSnapshot,executionMode:verifiedCommercial.executionMode,providerLane:verifiedCommercial.targetFulfillmentLane}:null})});
    const data=await res.json();if(!res.ok||!data.success)throw new Error(data.error||'Failed to submit intake request.');setRequestId(data.requestId||'');setRouting(data.routing||null);setSubmitted(true);
  }catch(err){setError(err.message||'Network error.')}finally{setLoading(false)}};
  const startCheckout=async()=>{if(!commercial?.frozenPriceSnapshot||!formData.email||!formData.serviceId||!requestId){setError('Complete the service request first so payment can be tied to the operational order.');return;}setCheckoutLoading(true);setError('');try{
    const checkout=await fetch('/api/create-checkout-session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({requestId,serviceId:formData.serviceId,email:formData.email})});const data=await checkout.json();if(!checkout.ok||!data.url)throw new Error(data.error||'Unable to create secure checkout.');window.location.assign(data.url);
  }catch(err){setError(err.message||'Checkout could not be started.')}finally{setCheckoutLoading(false)}};
  return <div className="bg-slate-950 text-slate-100 min-h-screen pt-24 pb-20"><div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
    <div className="text-center mb-10"><div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-amber-500/10 border border-amber-500/30 text-amber-400 text-xs sm:text-sm font-medium mb-4"><Sparkles className="w-4 h-4"/><span>Commercial Service Intake</span></div><h1 className="text-4xl font-extrabold text-white">Request Service &amp; Pay</h1><p className="text-slate-300 mt-2">Choose an approved offer, tell us where and how you are engaging DANI DECLARES, then continue to secure Stripe Checkout when the offer is directly purchasable.</p></div>
    {!requestedServiceId&&<div className="grid sm:grid-cols-2 gap-4 mb-8">{LAUNCH_OFFERS.map(o=><a key={o.serviceId} href={`/request-service?service=${encodeURIComponent(o.serviceId)}`} className="block p-5 rounded-2xl bg-slate-900 border border-slate-800 hover:border-amber-500/50 transition-all"><div className="text-amber-300 text-xs font-mono mb-2">D01 · {o.serviceId}</div><h2 className="text-lg font-bold text-white">{o.name}</h2><p className="text-sm text-slate-400 mt-2">{o.pricingLabel}</p><span className="inline-flex items-center text-amber-400 text-sm font-semibold mt-4">Start order <ArrowRight className="ml-1 w-4 h-4"/></span></a>)}</div>}
    {paid&&<div className="p-8 rounded-2xl bg-emerald-500/10 border border-emerald-500/30 text-center mb-8"><CheckCircle2 className="w-12 h-12 text-emerald-400 mx-auto mb-4"/><h2 className="text-2xl font-bold text-white">Payment received</h2><p className="text-slate-300 mt-2">Your DANI DECLARES request has returned from secure Stripe Checkout. Our operating workflow will continue from the paid request.</p></div>}
    {selectedOffer&&<div className="p-5 rounded-2xl bg-emerald-500/10 border border-emerald-500/30 mb-6"><div className="flex items-center gap-2 text-emerald-300 font-semibold"><ShieldCheck className="w-4 h-4"/>Canonical offer selected</div><div className="mt-2 text-white text-xl font-bold">{selectedOffer.name}</div><div className="text-sm text-slate-300 mt-1">{selectedOffer.pricingLabel}. Customer pricing is resolved server-side.</div></div>}
    {submitted?<div className="p-8 rounded-2xl bg-slate-900 border border-slate-800 text-center"><CheckCircle2 className="w-12 h-12 text-emerald-400 mx-auto mb-4"/><h2 className="text-2xl font-bold text-white">Service Request Logged</h2><p className="text-slate-300 mt-2">Your request is in the DANI DECLARES operating workflow.</p>{commercial?.frozenPriceSnapshot!=null&&<p className="text-sm text-amber-300 mt-4">Validated price: ${Number(commercial.frozenPriceSnapshot).toFixed(2)}</p>}{commercial?.frozenPriceSnapshot!=null&&<button type="button" onClick={startCheckout} disabled={checkoutLoading} className="mt-6 inline-flex items-center justify-center gap-2 px-7 py-3 rounded-xl bg-amber-500 hover:bg-amber-400 text-slate-950 font-bold disabled:opacity-50"><CreditCard className="w-5 h-5"/>{checkoutLoading?'Opening secure checkout…':'Continue to Secure Checkout'}</button>}</div>:<form onSubmit={handleSubmit} className="p-8 rounded-2xl bg-slate-900 border border-slate-800 space-y-6">
      {error&&<div className="p-4 rounded-xl bg-rose-500/10 border border-rose-500/30 text-rose-300 text-sm">{error}</div>}
      <div><label className="block text-xs font-semibold text-slate-300 uppercase mb-2">Commercial Relationship</label><select name="channelType" value={formData.channelType} onChange={handleChange} required className="w-full px-4 py-3 rounded-xl bg-slate-950 border border-slate-800 text-white">{CHANNEL_OPTIONS.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></div>
      {formData.channelType===OPERATIONS_CHANNELS.B2C&&<div><label className="block text-xs font-semibold text-slate-300 uppercase mb-2">Resident Subchannel</label><select name="subchannelCode" value={formData.subchannelCode} onChange={handleChange} className="w-full px-4 py-3 rounded-xl bg-slate-950 border border-slate-800 text-white">{RESIDENT_SUBCHANNELS.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></div>}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-6"><div><label className="block text-xs font-semibold text-slate-300 uppercase mb-2">Full Name</label><input type="text" name="name" required value={formData.name} onChange={handleChange} className="w-full px-4 py-3 rounded-xl bg-slate-950 border border-slate-800 text-white"/></div><div><label className="block text-xs font-semibold text-slate-300 uppercase mb-2">Email Address</label><input type="email" name="email" required value={formData.email} onChange={handleChange} className="w-full px-4 py-3 rounded-xl bg-slate-950 border border-slate-800 text-white"/></div></div>
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-6"><div><label className="block text-xs font-semibold text-slate-300 uppercase mb-2">Phone Number</label><input type="tel" name="phone" value={formData.phone} onChange={handleChange} className="w-full px-4 py-3 rounded-xl bg-slate-950 border border-slate-800 text-white"/></div><div><label className="block text-xs font-semibold text-slate-300 uppercase mb-2">Organization</label><input type="text" name="organizationName" value={formData.organizationName} onChange={handleChange} className="w-full px-4 py-3 rounded-xl bg-slate-950 border border-slate-800 text-white"/></div></div>
      <div><label className="block text-xs font-semibold text-slate-300 uppercase mb-2">Service Location</label><input type="text" name="locationAddress" required value={formData.locationAddress} onChange={handleChange} placeholder="Address or service location" className="w-full px-4 py-3 rounded-xl bg-slate-950 border border-slate-800 text-white"/></div>
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-6"><div><label className="block text-xs font-semibold text-slate-300 uppercase mb-2">Timeline</label><input type="text" name="timeline" value={formData.timeline} onChange={handleChange} placeholder="ASAP or preferred date" className="w-full px-4 py-3 rounded-xl bg-slate-950 border border-slate-800 text-white"/></div><div><label className="block text-xs font-semibold text-slate-300 uppercase mb-2">Budget / Contract Range</label><input type="text" name="budgetRange" value={formData.budgetRange} onChange={handleChange} className="w-full px-4 py-3 rounded-xl bg-slate-950 border border-slate-800 text-white"/></div></div>
      <div><label className="block text-xs font-semibold text-slate-300 uppercase mb-2">Scope &amp; Operational Details</label><textarea name="details" rows={5} required value={formData.details} onChange={handleChange} placeholder="Tell us what you need, the property/home details, quantities, timing, or special requirements." className="w-full px-4 py-3 rounded-xl bg-slate-950 border border-slate-800 text-white"/></div>
      <button type="submit" disabled={loading} className="w-full py-4 rounded-xl bg-amber-500 hover:bg-amber-400 text-slate-950 font-bold flex items-center justify-center gap-2 disabled:opacity-50">{loading?'Validating & Routing…':selectedOffer?'Validate & Create Service Request':'Submit Service Request'}<ArrowRight className="w-5 h-5"/></button>
    </form>}
  </div></div>;
}
