import React,{useEffect,useMemo,useState} from 'react';
import {ArrowRight,CheckCircle2,CreditCard,MapPin,Phone,ShieldCheck} from 'lucide-react';
import {OPERATIONS_CHANNELS} from '../lib/operations/intakeRouting2026';

const CHANNEL_OPTIONS=[
 {value:OPERATIONS_CHANNELS.B2C,label:'Resident / Household'},
 {value:OPERATIONS_CHANNELS.B2B_APT,label:'Property Management / Apartment Community'},
 {value:OPERATIONS_CHANNELS.B2B_RE,label:'Real Estate Professional / Brokerage'},
 {value:OPERATIONS_CHANNELS.B2B,label:'Business / Commercial'},
 {value:OPERATIONS_CHANNELS.B2G,label:'Government / Institution'}
];
const RESIDENT_OPTIONS=[{value:'CH01-A',label:'Regular resident / household'},{value:'CH01-B',label:'Resident of a participating apartment community'}];

export default function RequestServicePage(){
 const params=useMemo(()=>typeof window==='undefined'?new URLSearchParams():new URLSearchParams(window.location.search),[]);
 const requestedServiceId=params.get('service')||'';
 const paid=params.get('paid')==='1';
 const canceled=params.get('canceled')==='1';
 const [selectedService,setSelectedService]=useState(null);
 const [formData,setFormData]=useState({name:'',email:'',phone:'',channelType:OPERATIONS_CHANNELS.B2C,subchannelCode:'CH01-A',category:'GENERAL_SUPPORT',organizationName:'',locationAddress:'',timeline:'',budgetRange:'',details:'',serviceId:requestedServiceId});
 const [loading,setLoading]=useState(false),[submitted,setSubmitted]=useState(false),[error,setError]=useState(''),[commercial,setCommercial]=useState(null),[requestId,setRequestId]=useState(''),[checkoutLoading,setCheckoutLoading]=useState(false);
 useEffect(()=>{if(!requestedServiceId)return;fetch('/api/verify-commercial-intent?catalog=1').then(r=>r.json()).then(d=>{if(d.success)setSelectedService((d.services||[]).find(s=>s.serviceId===requestedServiceId)||null)}).catch(()=>{})},[requestedServiceId]);
 const handleChange=e=>setFormData(c=>({...c,[e.target.name]:e.target.value}));
 const handleSubmit=async e=>{e.preventDefault();setLoading(true);setError('');try{let verified=null;if(formData.serviceId){const isApartmentResident=formData.channelType===OPERATIONS_CHANNELS.B2C&&formData.subchannelCode==='CH01-B';const vr=await fetch('/api/verify-commercial-intent',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({serviceId:formData.serviceId,isResident:isApartmentResident,channelType:formData.channelType,subchannelCode:formData.subchannelCode})});verified=await vr.json();if(!vr.ok||!verified.success)throw new Error(verified.error||'This service is not available for the selected customer type.');setCommercial(verified)}const res=await fetch('/api/intake-webhook',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...formData,serviceType:selectedService?.name||'Service request',pricingServiceId:formData.serviceId||null,commercialIntent:verified?{serviceId:formData.serviceId,frozenPriceSnapshot:verified.frozenPriceSnapshot}:null})});const data=await res.json();if(!res.ok||!data.success)throw new Error(data.error||'We could not submit your request. Please try again.');setRequestId(data.requestId||'');setSubmitted(true)}catch(err){setError(err.message||'We could not submit your request.')}finally{setLoading(false)}};
 const startCheckout=async()=>{if(!commercial?.frozenPriceSnapshot||!formData.email||!formData.serviceId||!requestId){setError('We need a completed service request before payment.');return}setCheckoutLoading(true);setError('');try{const isApartmentResident=formData.channelType===OPERATIONS_CHANNELS.B2C&&formData.subchannelCode==='CH01-B';const checkout=await fetch('/api/create-checkout-session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({requestId,serviceId:formData.serviceId,email:formData.email,channelType:formData.channelType,subchannelCode:formData.subchannelCode,isResident:isApartmentResident})});const data=await checkout.json();if(!checkout.ok||!data.url)throw new Error(data.error||'Secure checkout could not be opened.');window.location.assign(data.url)}catch(err){setError(err.message||'Secure checkout could not be opened.')}finally{setCheckoutLoading(false)}};
 return <div className="min-h-screen bg-[#fffaf1] text-[#302226]"><section className="bg-[#5a1422] text-white"><div className="max-w-4xl mx-auto px-5 sm:px-8 py-12 md:py-16 text-center"><p className="text-[#efce72] font-black uppercase tracking-[.18em] text-xs">BOOK / REQUEST SERVICE</p><h1 className="mt-3 text-4xl sm:text-5xl font-black">Tell us what you need.</h1><p className="mt-4 text-[#f1e4e6] text-lg">We’ll confirm the service, price and timing. Set-price services can continue directly to secure checkout.</p></div></section><div className="max-w-4xl mx-auto px-5 sm:px-8 py-10">
 {paid&&<div className="mb-7 rounded-2xl bg-emerald-50 border border-emerald-200 p-7 text-center"><CheckCircle2 className="w-11 h-11 text-emerald-600 mx-auto"/><h2 className="mt-3 text-2xl font-black text-emerald-900">Payment received</h2><p className="mt-2 text-emerald-800">Thank you. Your request and payment are connected. We’ll follow up with scheduling or next steps.</p></div>}
 {canceled&&<div className="mb-7 rounded-2xl bg-amber-50 border border-amber-200 p-5 text-amber-900">Checkout was canceled. Your service request is still saved, and you can reopen checkout when you’re ready.</div>}
 {selectedService&&<div className="mb-7 rounded-2xl bg-white border border-[#e4d0a1] p-6 shadow-sm"><div className="text-xs font-black tracking-[.12em] uppercase text-[#a8791c]">Selected service</div><h2 className="mt-2 text-2xl font-black text-[#5b1624]">{selectedService.name}</h2><p className="mt-2 text-[#6d5b60]">{selectedService.pricingLabel||'Price confirmed after review'}</p></div>}
 {!requestedServiceId&&!submitted&&<div className="mb-7 rounded-2xl bg-[#f8ecd0] border border-[#dfc78e] p-6 flex flex-col sm:flex-row sm:items-center gap-4 justify-between"><div><h2 className="font-black text-[#5b1624] text-lg">Already know which service you want?</h2><p className="text-sm text-[#6d5b60]">Browse services first and select one to see its current pricing.</p></div><a href="/catalog" className="shrink-0 rounded-xl bg-[#6b1f2b] px-5 py-3 text-white font-black text-sm">Browse Services</a></div>}
 {error&&<div className="mb-6 rounded-xl bg-red-50 border border-red-200 p-4 text-red-800">{error}</div>}
 {submitted?<div className="rounded-3xl bg-white border border-[#e3d2a8] p-8 text-center shadow-sm"><CheckCircle2 className="w-12 h-12 text-emerald-600 mx-auto"/><h2 className="mt-4 text-2xl font-black text-[#5b1624]">We received your request.</h2>{commercial?.frozenPriceSnapshot!=null?<><p className="mt-3 text-[#6d5b60]">Your confirmed amount is <strong className="text-[#5b1624]">${Number(commercial.frozenPriceSnapshot).toFixed(2)}</strong>.</p><button type="button" onClick={startCheckout} disabled={checkoutLoading} className="mt-6 inline-flex items-center justify-center gap-2 rounded-xl bg-[#6b1f2b] px-7 py-4 text-white font-black disabled:opacity-50"><CreditCard className="w-5 h-5"/>{checkoutLoading?'Opening secure checkout…':'Continue to Secure Checkout'}</button></>:<p className="mt-3 text-[#6d5b60]">This service needs a quote or scope review. We’ll follow up with price and next steps before any payment is due.</p>}<p className="mt-5 text-sm text-[#88747a]">Request reference: {requestId}</p></div>:<form onSubmit={handleSubmit} className="rounded-3xl bg-white border border-[#e3d2a8] p-6 sm:p-8 shadow-sm space-y-6">
  <div><label className="block text-sm font-black text-[#5b1624] mb-2">I’m requesting service as</label><select name="channelType" value={formData.channelType} onChange={handleChange} className="w-full rounded-xl border border-[#dfcfaa] bg-[#fffdf8] px-4 py-3.5">{CHANNEL_OPTIONS.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></div>
  {formData.channelType===OPERATIONS_CHANNELS.B2C&&<div><label className="block text-sm font-black text-[#5b1624] mb-2">Resident type</label><select name="subchannelCode" value={formData.subchannelCode} onChange={handleChange} className="w-full rounded-xl border border-[#dfcfaa] bg-[#fffdf8] px-4 py-3.5">{RESIDENT_OPTIONS.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></div>}
  <div className="grid sm:grid-cols-2 gap-5"><div><label className="block text-sm font-black text-[#5b1624] mb-2">Full name *</label><input name="name" required value={formData.name} onChange={handleChange} className="w-full rounded-xl border border-[#dfcfaa] px-4 py-3.5"/></div><div><label className="block text-sm font-black text-[#5b1624] mb-2">Email *</label><input type="email" name="email" required value={formData.email} onChange={handleChange} className="w-full rounded-xl border border-[#dfcfaa] px-4 py-3.5"/></div></div>
  <div className="grid sm:grid-cols-2 gap-5"><div><label className="block text-sm font-black text-[#5b1624] mb-2">Phone</label><div className="relative"><Phone className="absolute left-3.5 top-3.5 w-5 h-5 text-[#a08351]"/><input type="tel" name="phone" value={formData.phone} onChange={handleChange} className="w-full rounded-xl border border-[#dfcfaa] pl-11 pr-4 py-3.5"/></div></div><div><label className="block text-sm font-black text-[#5b1624] mb-2">Business / organization</label><input name="organizationName" value={formData.organizationName} onChange={handleChange} className="w-full rounded-xl border border-[#dfcfaa] px-4 py-3.5"/></div></div>
  <div><label className="block text-sm font-black text-[#5b1624] mb-2">Service location *</label><div className="relative"><MapPin className="absolute left-3.5 top-3.5 w-5 h-5 text-[#a08351]"/><input name="locationAddress" required value={formData.locationAddress} onChange={handleChange} placeholder="Street address, city, or service location" className="w-full rounded-xl border border-[#dfcfaa] pl-11 pr-4 py-3.5"/></div></div>
  <div className="grid sm:grid-cols-2 gap-5"><div><label className="block text-sm font-black text-[#5b1624] mb-2">When do you need it?</label><input name="timeline" value={formData.timeline} onChange={handleChange} placeholder="ASAP or preferred date" className="w-full rounded-xl border border-[#dfcfaa] px-4 py-3.5"/></div><div><label className="block text-sm font-black text-[#5b1624] mb-2">Budget, if you have one</label><input name="budgetRange" value={formData.budgetRange} onChange={handleChange} placeholder="Optional" className="w-full rounded-xl border border-[#dfcfaa] px-4 py-3.5"/></div></div>
  <div><label className="block text-sm font-black text-[#5b1624] mb-2">What do you need? *</label><textarea name="details" rows={5} required value={formData.details} onChange={handleChange} placeholder="Tell us what needs to be done, quantities or property details, and anything important about timing or access." className="w-full rounded-xl border border-[#dfcfaa] px-4 py-3.5"/></div>
  <button type="submit" disabled={loading} className="w-full rounded-xl bg-[#6b1f2b] px-6 py-4 text-white font-black inline-flex items-center justify-center gap-2 disabled:opacity-50">{loading?'Submitting…':formData.serviceId?'Continue':'Submit Request'}<ArrowRight className="w-5 h-5"/></button><div className="flex items-center justify-center gap-2 text-xs text-[#806d72]"><ShieldCheck className="w-4 h-4"/>Secure payment is handled by Stripe when payment is available.</div>
 </form>}
 </div></div>;
}
