import React,{useEffect,useState} from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, Home, ShieldCheck, Sparkles, CalendarDays } from 'lucide-react';
const iconFor=(family)=>family==='HOME WATCH'?Home:(family==='SEASONAL'||family==='EVENT')?CalendarDays:(family==='HOME'||family==='ORGANIZATION'||family==='LAUNDRY')?Sparkles:ShieldCheck;
export default function ServicesPage(){
 const [services,setServices]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{fetch('/api/danis-specials').then(async r=>{const d=await r.json();if(!r.ok||!d.success)throw new Error(d.error||'We could not load services right now.');setServices(d.services||[])}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
 return <div className="bg-[#fffaf1] min-h-screen text-[#312428]"><section className="bg-[#5a1422] text-white"><div className="max-w-6xl mx-auto px-5 sm:px-8 py-14 md:py-20 text-center"><p className="text-[#efce72] font-black uppercase tracking-[.2em] text-xs">DANI DECLARES • DANI'S SPECIALS</p><h1 className="mt-3 text-4xl sm:text-5xl font-black">Services Danielle can handle directly.</h1><p className="mt-5 max-w-3xl mx-auto text-lg text-[#f0e2e4] leading-relaxed">The live Specials layer covers the owner-executable services Danielle can personally deliver in Georgia. Holiday setup and take-down are a featured seasonal priority.</p><div className="mt-7"><Link to="/request-service" className="rounded-xl bg-[#d2a83f] px-7 py-3.5 text-[#45101b] font-black">Request a Service</Link></div></div></section><section className="max-w-6xl mx-auto px-5 sm:px-8 py-14">{error&&<div className="mb-6 rounded-xl border border-red-200 bg-red-50 p-4 text-red-800">{error}</div>}{loading?<div className="py-16 text-center text-[#756469]">Loading DANI'S SPECIALS…</div>:<div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-5">{services.map(s=>{const Icon=iconFor(s.family);return <article key={s.serviceId} className="rounded-2xl border border-[#e8d5aa] bg-white p-6 shadow-sm"><Icon className="w-9 h-9 text-[#b58627]"/><div className="mt-4 text-xs uppercase tracking-[.12em] font-black text-[#a8791c]">Georgia • Owner Executed</div><h2 className="mt-2 text-xl font-black text-[#5c1725]">{s.name}</h2><p className="mt-2 text-sm text-[#6d5a60]">{s.family}</p><div className="mt-5 text-2xl font-black text-[#6b1f2b]">{s.pricingLabel}</div><Link to={`/request-service?service=${encodeURIComponent(s.serviceId)}`} className="mt-5 inline-flex items-center text-[#855d15] font-extrabold text-sm">Request <ArrowRight className="w-4 h-4 ml-1"/></Link></article>})}</div>}<div className="mt-12 rounded-3xl border border-[#dec68f] bg-[#f9edd2] p-7 sm:p-10"><h2 className="text-2xl sm:text-3xl font-black text-[#5b1624]">Need something outside DANI'S SPECIALS?</h2><p className="mt-2 text-[#6e5960]">Broader capabilities remain governed separately. This live menu is the work Danielle can personally execute now.</p></div></section></div>;
}
