import { evaluateRuntime, evaluateRegression, CANONICAL_IN_SCOPE_ANSWERS } from './dni01a001ReleaseContractProof2026';
const schema={ui_mode:'SPECIALIZED_CLEANING',pricing_model:'FIXED_SCOPE',scope_boundary:{bedroom_count:{max:1},bathroom_count:{max:1},square_footage:{max:1000},out_of_scope_action:'REQUIRE_DIFFERENT_SERVICE_OR_QUOTE'},fields:[{key:'bedroom_count',type:'select',options:['1'],required:true},{key:'bathroom_count',type:'select',options:['1'],required:true},{key:'square_footage',type:'number',max:1000,required:true}],commercial_inputs:[]};
function state(over={}){return {...{sku:'DNI-01A-001',release:{release_state:'HOLD',blocking_gate:'RUNTIME_ACCURACY',runtime_verified:false,production_smoke_verified:false,regression_verified:false,runtime_accuracy_ok:false},verification:{stripe_price_verified_at:'2026-09-23T03:16:55Z',runtime_verified_at:null,production_smoke_verified_at:null,regression_verified_at:null},offers:[{commercial_offer_status:'INTAKE_ONLY',fulfillment_gate_status:'FULFILLMENT_GATED',runtime_service_id:'svc-1'}],service:{id:'svc-1',sku:'DNI-01A-001',pricing_type:'FIXED',base_price_cents:14000,starting_price:140,is_active:true,quote_input_schema:schema},rules:[{channel_code:'CH01',status:'ACTIVE',lock_status:'LOCKED',base_price_cents:14000}],receipts:[]},...over};}
test('RUNTIME proves $140 in-scope and rejects out-of-scope',()=>{const r=evaluateRuntime(state());expect(r.failures).toEqual([]);expect(r.notes.join('\n')).toMatch(/\$140/);expect(r.notes.filter(n=>/out-of-scope/.test(n))).toHaveLength(4);});
test('RUNTIME fails on price drift',()=>{const s=state();s.service={...s.service,base_price_cents:10000,starting_price:100};expect(evaluateRuntime(s).failures.join('\n')).toMatch(/14000/);});
test('RUNTIME fails on scope-validator bypass',()=>{const s=state();s.service={...s.service,quote_input_schema:{...schema,ui_mode:'STANDARD'}};expect(evaluateRuntime(s).failures.join('\n')).toMatch(/ui_mode/);});
test('canonical in-scope request is 1BR 1BA 1000sqft',()=>{expect(CANONICAL_IN_SCOPE_ANSWERS).toMatchObject({bedroom_count:'1',bathroom_count:'1',square_footage:1000});});
test('REGRESSION passes current fail-closed HOLD',()=>expect(evaluateRegression(state()).failures).toEqual([]));
test('REGRESSION rejects LIVE_READY without timestamps',()=>{const s=state();s.release={...s.release,release_state:'LIVE_READY',blocking_gate:'NONE'};expect(evaluateRegression(s).failures.join('\n')).toMatch(/LIVE_READY/);});
test('REGRESSION rejects manual timestamp without receipt',()=>{const s=state();s.verification={...s.verification,runtime_verified_at:'2026-10-05T00:00:00Z'};s.release={...s.release,runtime_verified:true};expect(evaluateRegression(s).failures.join('\n')).toMatch(/without a governed RUNTIME receipt/);});
test('REGRESSION rejects PRODUCTION_SMOKE from TESTER',()=>{const s=state();s.receipts=[{id:'x',proof_kind:'PRODUCTION_SMOKE',proof_environment:'TESTER',proof_result:'PASS',source_sha:'abcdef1',workflow_run_id:'1',receipt_uri:'u'}];expect(evaluateRegression(s).failures.join('\n')).toMatch(/not from PRODUCTION/);});
