import stripeInvoiceFixture from './fixtures/recurringInvoiceStripe20261004.json';
import {isMonthlyOffer,hasPeriodEndCancellation,validateRecurringTerms,validatePaidInvoice,allowanceBalance,ownsRecurringRequest,reconcileRecurringInvoice} from './recurringServiceLifecycle2026.js';
const terms={objectType:'RET',channel:'CH05',scope:'Defined admin support',exclusions:'Licensed services',rollover:'NONE',overage:'QUOTE_REQUIRED',cancellation:'PERIOD_END',allowances:[{key:'admin_hours',quantity:10,unit:'hours'}]};
const invoice={id:'in_1',status:'paid',paid:true,currency:'usd',total:15000,amount_paid:15000,billing_reason:'subscription_create',lines:{data:[{type:'subscription',period:{start:1791000000,end:1793678400}}]}};
test('canonical MONTHLY and normalized month both use recurring checkout',()=>{expect(isMonthlyOffer({billingCycle:'MONTHLY'})).toBe(true);expect(isMonthlyOffer({billingCycle:'month'})).toBe(true);expect(isMonthlyOffer({billingCycle:'ONETIME'})).toBe(false)});
test('all seven object types and five owner-confirmed channels are preserved; CH06 denied',()=>{for(const objectType of ['SERV','PROD','DIGITAL','KIT','RET','EVENT','WORK-ORDER'])expect(validateRecurringTerms({...terms,objectType,channel:'CH05'}).objectType).toBe(objectType);expect(()=>validateRecurringTerms({...terms,channel:'CH06'})).toThrow();expect(()=>validateRecurringTerms({...terms,channel:'CH07'})).toThrow();expect(()=>validateRecurringTerms({...terms,objectType:'B2B'})).toThrow()});
test('duplicate allowances, automatic overages and implicit rollover fail closed',()=>{expect(()=>validateRecurringTerms({...terms,allowances:[terms.allowances[0],terms.allowances[0]]})).toThrow();expect(()=>validateRecurringTerms({...terms,overage:'AUTO_CHARGE'})).toThrow();expect(()=>validateRecurringTerms({...terms,rollover:'UNLIMITED'})).toThrow()});
test('short, failed, unpaid, wrong-currency and proration payments cannot fulfill',()=>{for(const change of [{amount_paid:14999},{total:14999},{paid:false},{status:'open'},{currency:'eur'},{billing_reason:'subscription_update'},{lines:{data:[{type:'subscription',proration:true,period:{start:1,end:2}}]}}])expect(()=>validatePaidInvoice({...invoice,...change},15000)).toThrow()});
test('ambiguous period or truncated invoice lines are review-required',()=>{expect(()=>validatePaidInvoice({...invoice,lines:{has_more:true,data:invoice.lines.data}},15000)).toThrow();expect(()=>validatePaidInvoice({...invoice,lines:{data:[]}},15000)).toThrow()});
test('usage retains excess without billing it; each cycle starts with its own allowance',()=>{expect(allowanceBalance(terms,[{allowance_key:'admin_hours',quantity:12}])[0]).toMatchObject({remaining:0,excess:2,overage:'QUOTE_REQUIRED'});expect(allowanceBalance(terms,[])[0].remaining).toBe(10)});
test('residents cannot inherit every subscription in their apartment organization',()=>{const ctx={role:'resident',identity:{entity_id:'lead_1',organization_id:'property_1'}};expect(ownsRecurringRequest(ctx,{lead_id:'lead_2',organization_id:'property_1'})).toBe(false);expect(ownsRecurringRequest(ctx,{lead_id:'lead_1'})).toBe(true);expect(ownsRecurringRequest({role:'provider',identity:{entity_id:'lead_1'}},{lead_id:'lead_1'})).toBe(false)});
function fixture({replay=false,renewal=false,paidInvoice=invoice}={}){
 const writes=[];let paymentRecorded=false;let cycleCount=renewal?1:0;
 const tx={$executeRaw:jest.fn(async(s,...v)=>{writes.push(s.join('?'));if(s.join('?').includes('dd_payment_events'))paymentRecorded=true;return 1}),$queryRaw:jest.fn(async(s,...v)=>{const sql=s.join('?');if(sql.includes('dd_activate_paid_estimate_assignments')&&!paymentRecorded)throw new Error('CUSTOMER_PAYMENT_REQUIRED_BEFORE_FULFILLMENT_OFFER');if(sql.includes('where stripe_invoice_id'))return replay?[{id:'cycle_1'}]:[];if(sql.includes('subscription_terms'))return [{canonical_sku:'DNI-04A-020',monthly_amount_cents:15000,terms}];if(sql.includes('period_start<'))return [];if(sql.includes('where subscription_id'))return cycleCount?[{id:'old_cycle'}]:[];if(sql.includes('insert into public.dd_service_subscription_cycles')){cycleCount++;return [{id:'cycle_1'}]};return []}),serviceRequest:{findUnique:jest.fn(async()=>({id:'request_1',leadId:'lead_1',organizationId:'org_1'})),update:jest.fn()},dd_estimates:{findUnique:jest.fn(async()=>({id:'estimate_1',intake_answers:{serviceSku:'DNI-04A-020',channelCode:'CH05'},estimate_status:'approved',estimated_total:150,economics_status:'PASS',active_economics_snapshot_id:'snapshot_1',division_slug:'administrative-business-operations'}))},dd_jobs:{findFirst:jest.fn(async()=>null),create:jest.fn(async()=>({id:'job_1'}))}};
 const db={$transaction:async fn=>fn(tx)};
 return {db,tx,writes,event:{id:'evt_1',type:'invoice.paid',data:{object:paidInvoice}},sub:{id:'sub_1',stripe_subscription_id:'sub_stripe',service_request_id:'request_1',estimate_id:'estimate_1',canonical_sku:'DNI-04A-020'}};
}
test('wrong amount fails before payment verification, job or allowance creation',async()=>{const f=fixture({paidInvoice:{...invoice,amount_paid:1}});await expect(reconcileRecurringInvoice(f.db,f.event,f.sub,jest.fn())).rejects.toThrow();expect(f.tx.dd_jobs.create).not.toHaveBeenCalled();expect(f.writes.some(s=>s.includes('first_payment_verified_at'))).toBe(false)});
test('first paid cycle uses existing assignment gate and records verified payment afterwards',async()=>{const f=fixture();const routes=jest.fn();const result=await reconcileRecurringInvoice(f.db,f.event,f.sub,routes);expect(result.jobId).toBe('job_1');expect(f.tx.$queryRaw.mock.calls.some(([s])=>s.join('').includes('dd_activate_paid_estimate_assignments'))).toBe(true);expect(routes).toHaveBeenCalledWith(f.db,'estimate_1')});
test('renewal is recorded as paid but does not reuse old assignment/economics authority',async()=>{const f=fixture({renewal:true});const result=await reconcileRecurringInvoice(f.db,f.event,f.sub,jest.fn());expect(result.fulfillmentStatus).toBe('REVIEW_REQUIRED');expect(f.tx.dd_jobs.create).not.toHaveBeenCalled();expect(f.tx.$queryRaw.mock.calls.some(([s])=>s.join('').includes('dd_activate_paid_estimate_assignments'))).toBe(false);expect(f.writes.some(s=>s.includes('dd_payment_events'))).toBe(true)});
test('redelivery of an invoice cannot duplicate a cycle, job or payment',async()=>{const f=fixture({replay:true});expect(await reconcileRecurringInvoice(f.db,f.event,f.sub,jest.fn())).toEqual({replay:true});expect(f.tx.dd_jobs.create).not.toHaveBeenCalled();expect(f.writes).toHaveLength(1)});

test('canceled subscriptions record paid evidence without dispatching new work',async()=>{const f=fixture();f.sub.currentStripeStatus='CANCELED';expect((await reconcileRecurringInvoice(f.db,f.event,f.sub,jest.fn())).fulfillmentStatus).toBe('REVIEW_REQUIRED');expect(f.tx.dd_jobs.create).not.toHaveBeenCalled()});

test('renewal delivered before the first invoice never masquerades as first-cycle authority',async()=>{const f=fixture({paidInvoice:{...invoice,billing_reason:'subscription_cycle'}});const result=await reconcileRecurringInvoice(f.db,f.event,f.sub,jest.fn());expect(result.fulfillmentStatus).toBe('REVIEW_REQUIRED');expect(f.tx.dd_jobs.create).not.toHaveBeenCalled()});

test('subscription checkout requires active period-end cancellation and no self-serve price changes',()=>{const valid={active:true,features:{subscription_cancel:{enabled:true,mode:'at_period_end'},subscription_update:{enabled:false}}};expect(hasPeriodEndCancellation(valid)).toBe(true);expect(hasPeriodEndCancellation(null)).toBe(false);expect(hasPeriodEndCancellation({...valid,active:false})).toBe(false);expect(hasPeriodEndCancellation({...valid,features:{...valid.features,subscription_update:{enabled:true}}})).toBe(false);expect(hasPeriodEndCancellation({...valid,features:{...valid.features,subscription_cancel:{enabled:true,mode:'immediately'}}})).toBe(false)});

test('modern Stripe paid invoices without the deprecated paid boolean remain verifiable',()=>{const {paid,...modern}=invoice;expect(validatePaidInvoice(modern,15000)).toEqual(expect.objectContaining({start:expect.any(String),end:expect.any(String)}))});

test('sanitized receipt from the actual Stripe test-mode invoice matches the period parser',()=>{expect(stripeInvoiceFixture.livemode).toBe(false);expect(validatePaidInvoice(stripeInvoiceFixture,100)).toEqual({start:new Date(1791091200*1000).toISOString(),end:new Date(1793769600*1000).toISOString()})});
