const words=s=>String(s||'').toLowerCase().split(/[^a-z0-9]+/).filter(x=>x.length>2);
const SIGNAL_TERMS={bathroom:['bath','bathroom','restroom','sanitize','sanitization'],bedroom:['bedroom','room','dust','vacuum'],kitchen:['kitchen'],move_out:['move','turn','vacant','deposit'],move_in:['move','reset','vacant'],vacuum:['vacuum','floor'],dust:['dust','detail'],carpet:['carpet','rug','extraction'],pet:['pet','soil','odor'],recurring:['refresh','maintenance','recurring','routine']};
function scoreService(service,evidence){const hay=new Set(words([service.name,service.sku,service.service_family,service.publicPrice].join(' ')));let score=0,matched=[];for(const signal of evidence.signals||[]){const terms=SIGNAL_TERMS[signal]||[];const hits=terms.filter(t=>[...hay].some(h=>h.includes(t)||t.includes(h)));if(hits.length){score+=Math.min(3,hits.length);matched.push(signal);}}return {score,matchedSignals:[...new Set(matched)]};}
export function composeScope({evidence,services=[],packages=[],addonRules=[],channelCode=null,jurisdictionCode=null}){
 const candidates=services.map(service=>({service,...scoreService(service,evidence)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score||String(a.service.name).localeCompare(String(b.service.name))).slice(0,8);
 const authorized=candidates.filter(x=>x.service.releaseState==='LIVE_READY'&&(x.service.governedOfferStatus==='SELL_NOW'||x.service.commercial_intent_status==='SELL_NOW'));
 const selectedSkus=new Set(authorized.slice(0,4).map(x=>x.service.sku));
 const packageCandidates=(packages||[]).filter(p=>p.commercial_status==='ACTIVE'&&(!channelCode||p.channel_code===channelCode)&&(!jurisdictionCode||!p.jurisdiction_code||p.jurisdiction_code===jurisdictionCode)).map(p=>{const components=p.components||[];const required=components.filter(c=>c.required!==false);const matched=required.filter(c=>selectedSkus.has(c.serviceSku)).length;return {...p,matchRatio:required.length?matched/required.length:0};}).filter(p=>p.matchRatio>0).sort((a,b)=>b.matchRatio-a.matchRatio);
 return {evidence,candidates,commerciallyAuthorizedCandidates:authorized,packageCandidates,addonCandidates:(addonRules||[]).filter(r=>r.status==='ACTIVE'),unresolvedQuestions:[...(evidence.unresolved||[])],suggestedComponents:authorized.slice(0,4).map(x=>({serviceSku:x.service.sku,name:x.service.name,quantity:1,evidenceSignals:x.matchedSignals,confidence:Math.min(.98,.45+x.score*.12)})),reviewRequired:true,note:'Suggestions are candidates only. Human review and governed estimate creation remain authoritative.'};
}
