jest.mock('../../../api-handlers/stripe-webhook.js',()=>({finalizeProposedProviderRoutes:jest.fn()}));
jest.mock('../../../api-handlers/create-checkout-session.js',()=>({__esModule:true,default:jest.fn()}));
jest.mock('../../../api-handlers/_portalAuth.js',()=>({authenticatePortalRequest:jest.fn()}));
jest.mock('../../../lib/prisma.js',()=>({__esModule:true,default:{$transaction:jest.fn()}}));
jest.mock('./governedCommercialGate2026.js',()=>({getChannelFromRequest:jest.fn(()=> 'CH05'),getGovernedCommercialOffer:jest.fn()}));
jest.mock('stripe',()=>jest.fn(()=>({billingPortal:{configurations:{retrieve:jest.fn()},sessions:{create:jest.fn()}},subscriptions:{retrieve:jest.fn()}})));
process.env.STRIPE_SECRET_KEY='sk_test_nonfunctional_fixture';
const handler=require('../../../api-handlers/service-subscriptions.js').default;
const {authenticatePortalRequest}=require('../../../api-handlers/_portalAuth.js');
const Stripe=require('stripe');
const stripe=Stripe.mock.results[0].value;
function response(){return {status:jest.fn(function(n){this.code=n;return this}),json:jest.fn(function(x){this.payload=x;return this})}}
function sbFor(rows){const queries=[];return {queries,from:jest.fn(table=>{const builder={};for(const name of ['select','eq','in','limit','order','is','update','insert'])builder[name]=jest.fn((...args)=>{queries.push({table,name,args});return builder});builder.single=jest.fn(async()=>rows[table]||{data:null});builder.then=(resolve,reject)=>Promise.resolve(rows[table]||{data:[]}).then(resolve,reject);return builder})}}
beforeEach(()=>{jest.clearAllMocks();delete process.env.STRIPE_BILLING_PORTAL_CONFIGURATION_ID});
test('unauthenticated request never queries business records',async()=>{authenticatePortalRequest.mockResolvedValue({error:'Authentication required',status:401});const res=response();await handler({method:'GET',headers:{}},res);expect(res.code).toBe(401)});
test('provider role cannot enumerate customer recurring records',async()=>{const sb=sbFor({});authenticatePortalRequest.mockResolvedValue({role:'provider',identity:{entity_id:'lead_1'},supabase:sb});const res=response();await handler({method:'GET',headers:{}},res);expect(res.code).toBe(403)});
test('resident reads use their lead, never shared property organization',async()=>{const sb=sbFor({service_requests:{data:[]}});authenticatePortalRequest.mockResolvedValue({role:'resident',identity:{entity_id:'lead_1',organization_id:'property_1'},supabase:sb});await handler({method:'GET',headers:{}},response());expect(sb.queries).toContainEqual({table:'service_requests',name:'eq',args:['lead_id','lead_1']});expect(sb.queries.some(q=>q.args[0]==='organization_id')).toBe(false)});
test('staff cannot accept recurring terms on a customer behalf',async()=>{authenticatePortalRequest.mockResolvedValue({isStaff:true,supabase:sbFor({})});const res=response();await handler({method:'POST',headers:{},body:{action:'accept_terms'}},res);expect(res.code).toBe(403)});
test('customer cannot approve terms or record allowance consumption',async()=>{for(const action of ['approve_terms','record_usage']){const sb=sbFor({dd_service_subscriptions:{data:{id:'sub_1',service_request_id:'req_1'}},service_requests:{data:{lead_id:'lead_1'}}});authenticatePortalRequest.mockResolvedValue({role:'customer',identity:{entity_id:'lead_1'},supabase:sb});const res=response();await handler({method:'POST',headers:{},body:{action,subscriptionId:'sub_1'}},res);expect(res.code).toBe(403);expect(sb.queries.some(q=>q.name==='insert')).toBe(false)}});
test('wrong account cannot open billing management',async()=>{const sb=sbFor({dd_service_subscriptions:{data:{id:'sub_1',service_request_id:'req_1',stripe_customer_id:'cus_1'}},service_requests:{data:{lead_id:'other'}}});authenticatePortalRequest.mockResolvedValue({role:'customer',identity:{entity_id:'lead_1'},supabase:sb});const res=response();await handler({method:'POST',headers:{},body:{action:'manage_billing',subscriptionId:'sub_1'}},res);expect(res.code).toBe(403);expect(stripe.billingPortal.sessions.create).not.toHaveBeenCalled()});
test('billing portal cannot use an unreviewed or immediate-cancellation configuration',async()=>{process.env.STRIPE_BILLING_PORTAL_CONFIGURATION_ID='bpc_1';const sb=sbFor({dd_service_subscriptions:{data:{id:'sub_1',service_request_id:'req_1',stripe_customer_id:'cus_1'}},service_requests:{data:{lead_id:'lead_1'}}});authenticatePortalRequest.mockResolvedValue({role:'customer',identity:{entity_id:'lead_1'},supabase:sb});stripe.billingPortal.configurations.retrieve.mockResolvedValue({active:true,features:{subscription_cancel:{enabled:true,mode:'immediately'},subscription_update:{enabled:false}}});const res=response();await handler({method:'POST',headers:{},body:{action:'manage_billing',subscriptionId:'sub_1'}},res);expect(res.code).toBe(409);expect(stripe.billingPortal.sessions.create).not.toHaveBeenCalled()});

test('accepted agreement checkout delegates to existing gates with the signed-in identity',async()=>{const sb=sbFor({dd_service_subscription_terms:{data:{id:'terms_1',estimate_id:'estimate_1',accepted_at:'2026-10-01'}},dd_estimates:{data:{service_request_id:'req_1'}},service_requests:{data:{id:'req_1',lead_id:'lead_1',property_details:{commercialIntent:{serviceId:'DNI-01A-001'}}}}});authenticatePortalRequest.mockResolvedValue({role:'customer',user:{email:'owner@example.invalid'},identity:{entity_id:'lead_1'},supabase:sb});const req={method:'POST',headers:{},body:{action:'start_checkout',termsId:'terms_1',email:'attacker@example.invalid'}};await handler(req,response());expect(require('../../../api-handlers/create-checkout-session.js').default).toHaveBeenCalledWith(expect.objectContaining({body:{requestId:'req_1',serviceId:'DNI-01A-001',email:'owner@example.invalid'}}),expect.anything())});
test('unaccepted agreement cannot open subscription checkout',async()=>{const sb=sbFor({dd_service_subscription_terms:{data:{id:'terms_1',accepted_at:null}}});authenticatePortalRequest.mockResolvedValue({role:'customer',supabase:sb});const res=response();await handler({method:'POST',headers:{},body:{action:'start_checkout',termsId:'terms_1'}},res);expect(res.code).toBe(409);expect(require('../../../api-handlers/create-checkout-session.js').default).not.toHaveBeenCalled()});
