import fs from 'node:fs';
import assert from 'node:assert/strict';
import {PGlite} from '@electric-sql/pglite';
const db=new PGlite();
const root=process.env.DANI_REPO_ROOT||process.cwd();
await db.exec(`create schema auth; create role anon; create role authenticated; create role service_role;
 create table auth.users(id uuid primary key);
 create table public.service_requests(id uuid primary key);
 create table public.services(id uuid primary key);
 create table public.dd_estimates(id uuid primary key);
 create table public.dd_jobs(id uuid primary key,job_status text);
 create table public.dd_completion_reviews(job_id uuid,status text);
 create table public.dd_job_tasks(id uuid,job_id uuid,status text,is_required boolean,evidence_required boolean);
 create table public.dd_job_evidence(job_id uuid,task_id uuid,storage_url text,verification_status text);`);
await db.exec(fs.readFileSync(root+'/supabase/migrations/20260922172732_paid_first_service_subscriptions.sql','utf8'));
await db.exec(fs.readFileSync(root+'/supabase/migrations/20261004050403_recurring_terms_cycles_usage.sql','utf8'));
await db.exec(fs.readFileSync(root+'/supabase/migrations/20260925123000_completion_authority_contract.sql','utf8'));
await db.exec(`create trigger completion_guard before update on dd_jobs for each row execute function dd_guard_job_completion();`);
const ids=Object.fromEntries(['user','request','service','estimate','job','otherJob','sub','cycle','task'].map((k,i)=>[k,`00000000-0000-0000-0000-${String(i+1).padStart(12,'0')}`]));
await db.exec(`insert into auth.users values('${ids.user}'); insert into service_requests values('${ids.request}'); insert into services values('${ids.service}'); insert into dd_estimates values('${ids.estimate}'); insert into dd_jobs values('${ids.job}','new'),('${ids.otherJob}','new');
insert into dd_service_subscriptions(id,service_request_id,estimate_id,service_id,canonical_sku) values('${ids.sub}','${ids.request}','${ids.estimate}','${ids.service}','DNI-04A-020');
insert into dd_service_subscription_cycles(id,subscription_id,stripe_invoice_id,period_start,period_end,amount_paid_cents,terms_snapshot,job_id) values('${ids.cycle}','${ids.sub}','in_proof','2026-10-01','2026-11-01',15000,'{"allowances":[{"key":"hours","quantity":10,"unit":"hours"}]}','${ids.job}');
insert into dd_job_tasks values('${ids.task}','${ids.job}','NEW',true,true);`);
let checks=0;
async function denied(sql,reason){await assert.rejects(db.exec(sql),new RegExp(reason));checks++}
const usage=(job=ids.job,key='hours')=>`insert into dd_service_subscription_usage(cycle_id,job_id,allowance_key,quantity,recorded_by) values('${ids.cycle}','${job}','${key}',12,'${ids.user}')`;
await denied(usage(),'COMPLETION_QA_APPROVAL_REQUIRED');
await denied(`update dd_jobs set job_status='COMPLETED' where id='${ids.job}'`,'REQUIRED_TASKS_INCOMPLETE');
await db.exec(`update dd_job_tasks set status='DONE';`);
await denied(`update dd_jobs set job_status='COMPLETED' where id='${ids.job}'`,'REQUIRED_EVIDENCE_MISSING');
await db.exec(`insert into dd_job_evidence values('${ids.job}','${ids.task}','proof/photo','PENDING');`);
await denied(`update dd_jobs set job_status='COMPLETED' where id='${ids.job}'`,'REQUIRED_EVIDENCE_NOT_QA_VERIFIED');
await db.exec(`update dd_job_evidence set verification_status='VERIFIED';`);
await denied(`update dd_jobs set job_status='COMPLETED' where id='${ids.job}'`,'COMPLETION_QA_APPROVAL_REQUIRED');
await db.exec(`insert into dd_completion_reviews values('${ids.job}','APPROVED'); update dd_jobs set job_status='COMPLETED' where id='${ids.job}';`);
await denied(usage(ids.otherJob),'CYCLE_JOB_MISMATCH');
await denied(usage(ids.job,'fake'),'ALLOWANCE_NOT_INCLUDED');
await db.exec(usage());checks++;
await denied(usage(),'duplicate key');
await denied(`insert into dd_service_subscription_cycles(subscription_id,stripe_invoice_id,period_start,period_end,amount_paid_cents,terms_snapshot) values('${ids.sub}','in_proof','2026-11-01','2026-12-01',15000,'{}')`,'duplicate key');
await denied(`insert into dd_service_subscription_cycles(subscription_id,stripe_invoice_id,period_start,period_end,amount_paid_cents,terms_snapshot) values('${ids.sub}','in_second','2026-10-01','2026-11-01',15000,'{}')`,'duplicate key');
await db.exec('set role anon');await denied('select * from dd_service_subscription_usage','permission denied');await db.exec('reset role');
assert.equal((await db.query('select count(*)::integer as n from dd_service_subscription_usage')).rows[0].n,1);checks++;
console.log(`PostgreSQL migration/QA/usage/isolation proof: ${checks} checks passed; isolated database only.`);
await db.close();
