function decodeBase64Url(value=''){if(!value)return '';const normalized=String(value).replace(/-/g,'+').replace(/_/g,'/');try{return Buffer.from(normalized,'base64').toString('utf8')}catch{return ''}}
export function walkGmailParts(payload,parentPartId=null,out=[]){if(!payload)return out;const partId=payload.partId??parentPartId??'0';const filename=payload.filename||null;const mimeType=payload.mimeType||null;const body=payload.body||{};if(filename||body.attachmentId){out.push({partId,filename,mimeType,attachmentId:body.attachmentId||null,size:Number(body.size||0),inlineData:body.data||null});}for(const child of payload.parts||[])walkGmailParts(child,partId,out);return out;}
export function gmailTextBodies(payload,out=[]){if(!payload)return out;const mime=String(payload.mimeType||'').toLowerCase();if((mime==='text/plain'||mime==='text/html')&&payload.body?.data)out.push({mimeType:mime,text:decodeBase64Url(payload.body.data),partId:payload.partId||'0'});for(const child of payload.parts||[])gmailTextBodies(child,out);return out;}
export function normalizeGmailMessage({message,accountEmail,sorting}){const headers=message?.payload?.headers||[];const h=n=>headers.find(x=>String(x.name).toLowerCase()===n.toLowerCase())?.value||null;return{sourceType:'EMAIL_MESSAGE',sourceSystem:'GMAIL',externalMessageId:message.id,externalThreadId:message.threadId||null,historyId:message.historyId||null,accountEmail:accountEmail||null,occurredAt:message.internalDate?new Date(Number(message.internalDate)).toISOString():null,subject:h('Subject'),from:h('From'),to:h('To'),cc:h('Cc'),labels:message.labelIds||[],snippet:message.snippet||null,bodies:gmailTextBodies(message.payload),attachments:walkGmailParts(message.payload),sorting:sorting||null,authorityStatus:'OBSERVATION_ONLY'};}
export function uniqueHistoryMessageIds(history=[]){const ids=new Set();for(const item of history||[]){for(const m of item.messagesAdded||[])if(m.message?.id)ids.add(m.message.id);for(const m of item.messages||[])if(m.id)ids.add(m.id);}return [...ids];}
export function isStaleHistoryResponse(status,body={}){return Number(status)===404||String(body?.error?.message||'').toLowerCase().includes('historyid');}
export function gmailSyncMode(connection){const cursor=connection?.metadata?.gmail_history_id||connection?.token_metadata?.gmail_history_id||null;const backfillComplete=Boolean(connection?.metadata?.gmail_intelligence_backfill_complete);return cursor&&backfillComplete?{mode:'INCREMENTAL',historyId:String(cursor)}:{mode:'BOUNDED_BACKFILL',historyId:cursor?String(cursor):null};}
export function gmailBackfillState(connection){const metadata=connection?.metadata||{};return{pageToken:metadata.gmail_intelligence_backfill_page_token||null,complete:Boolean(metadata.gmail_intelligence_backfill_complete)};}
export function shouldIngestCommunication(syncModeUsed){return syncModeUsed==='INCREMENTAL'||syncModeUsed==='STALE_CURSOR_RECOVERY';}
export function completeGmailBackfillMetadata(existing={},profileHistoryId=null){return nextGmailSyncMetadata(existing,{gmail_intelligence_backfill_page_token:null,gmail_intelligence_backfill_complete:true,gmail_history_id:profileHistoryId?String(profileHistoryId):(existing||{}).gmail_history_id||null,gmail_backfill_completed_at:new Date().toISOString()});}
export function nextGmailSyncMetadata(existing={},patch={}){return {...(existing||{}),...patch,gmail_intelligence_sync_version:2};}

export function attachmentEvidenceKey(connectionId,messageId,part){return `GMAIL_ATTACHMENT:${connectionId}:${messageId}:${part?.partId||part?.attachmentId||'unknown'}`;}
export function isTextLikeAttachment(part){const mime=String(part?.mimeType||'').toLowerCase();const name=String(part?.filename||'').toLowerCase();return mime.startsWith('text/')||mime==='application/json'||mime==='application/xml'||mime==='text/csv'||name.endsWith('.txt')||name.endsWith('.csv')||name.endsWith('.json')||name.endsWith('.xml')||name.endsWith('.md');}
export function boundedAttachmentText(base64UrlData,maxBytes=262144){if(!base64UrlData)return null;const normalized=String(base64UrlData).replace(/-/g,'+').replace(/_/g,'/');try{const buf=Buffer.from(normalized,'base64');if(buf.length>maxBytes)return null;return buf.toString('utf8').slice(0,maxBytes);}catch{return null;}}

export function attachmentFingerprint(connectionId,messageId,part,base64UrlData){const stable=[connectionId,messageId,part?.partId||'',part?.attachmentId||'',part?.filename||'',part?.mimeType||'',part?.size||0,base64UrlData||''].join('|');let h=2166136261;for(let i=0;i<stable.length;i++){h^=stable.charCodeAt(i);h=Math.imul(h,16777619);}return (h>>>0).toString(16).padStart(8,'0');}
export function historyPageToken(metadata={}){return metadata.gmail_history_page_token||null;}
