-- Production migration: 20260905204402_contract_acquisition_lifecycle_20260905
-- This file records the contract acquisition lifecycle applied to production.
-- Contract lifecycle: opportunity -> qualification -> pursuit -> solicitation -> proposal -> submission gate -> award -> contract -> performance.
-- Contract records are staff-controlled; buyer portal access is read-only and organization-scoped.
create table if not exists public.dd_contract_opportunities (id uuid primary key default gen_random_uuid(), public_reference text not null unique default ('DD-OPP-' || upper(substr(replace(gen_random_uuid()::text,'-',''),1,8))), source_system text not null default 'INTERNAL', source_url text, external_opportunity_id text, title text not null, buyer_name text, buyer_type text, buyer_organization_id uuid references public.dd_client_organizations(id), procurement_path text not null default 'OTHER', solicitation_type text, solicitation_number text, naics_code text, psc_code text, jurisdiction_code text not null default 'GA', place_of_performance text, posted_at timestamptz, response_deadline timestamptz, estimated_value numeric, contract_ceiling numeric, term_summary text, set_aside text, source_authority text, evidence_status text not null default 'UNVERIFIED', fit_status text not null default 'UNASSESSED', stage text not null default 'RESEARCH', bid_no_bid text not null default 'PENDING', priority text not null default 'NORMAL', research_notes text, qualification_notes text, metadata jsonb not null default '{}'::jsonb, created_by uuid references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.dd_contract_buyers (id uuid primary key default gen_random_uuid(), organization_id uuid references public.dd_client_organizations(id), buyer_name text not null, organization_name text, buyer_type text, title text, email text, phone text, website text, procurement_role text, notes text, source_opportunity_id uuid references public.dd_contract_opportunities(id) on delete set null, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.dd_contract_pursuits (id uuid primary key default gen_random_uuid(), public_reference text not null unique default ('DD-PUR-' || upper(substr(replace(gen_random_uuid()::text,'-',''),1,8))), opportunity_id uuid not null references public.dd_contract_opportunities(id) on delete restrict, buyer_id uuid references public.dd_contract_buyers(id) on delete set null, pursuit_owner uuid references auth.users(id), pursuit_stage text not null default 'QUALIFICATION', bid_no_bid text not null default 'PENDING', qualification_score numeric, qualification_gate text not null default 'OPEN', target_submission_at timestamptz, actual_submission_at timestamptz, estimated_bid_cost numeric, estimated_contract_value numeric, strategy text, teaming_strategy text, compliance_summary text, next_action text, next_action_due_at timestamptz, notes text, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.dd_contract_solicitations (id uuid primary key default gen_random_uuid(), pursuit_id uuid not null references public.dd_contract_pursuits(id) on delete cascade, solicitation_number text, solicitation_type text, title text, issuing_buyer text, issue_date timestamptz, question_deadline timestamptz, response_deadline timestamptz, amendment_count integer not null default 0, submission_method text, submission_instructions text, scope_summary text, requirements_summary text, pricing_instructions text, mandatory_forms jsonb not null default '[]'::jsonb, compliance_requirements jsonb not null default '[]'::jsonb, document_manifest jsonb not null default '[]'::jsonb, source_url text, current_version text, status text not null default 'ACTIVE', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.dd_contract_proposals (id uuid primary key default gen_random_uuid(), public_reference text not null unique default ('DD-PROP-' || upper(substr(replace(gen_random_uuid()::text,'-',''),1,8))), pursuit_id uuid not null references public.dd_contract_pursuits(id) on delete cascade, solicitation_id uuid references public.dd_contract_solicitations(id) on delete set null, version_number integer not null default 1, proposal_status text not null default 'DRAFT', proposal_title text, submission_deadline timestamptz, submitted_at timestamptz, submitted_by uuid references auth.users(id), pricing_summary jsonb not null default '{}'::jsonb, technical_approach text, management_approach text, quality_control_plan text, staffing_plan text, equipment_plan text, past_performance text, references_text text, teaming_partners jsonb not null default '[]'::jsonb, compliance_checklist jsonb not null default '[]'::jsonb, document_manifest jsonb not null default '[]'::jsonb, evaluator_notes text, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(pursuit_id,version_number));
create table if not exists public.dd_contract_awards (id uuid primary key default gen_random_uuid(), pursuit_id uuid not null unique references public.dd_contract_pursuits(id) on delete restrict, proposal_id uuid references public.dd_contract_proposals(id) on delete set null, award_status text not null default 'PENDING', contract_number text, award_date timestamptz, notice_date timestamptz, awarded_value numeric, ceiling_value numeric, funded_value numeric, award_term text, notice_url text, award_notes text, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.dd_contracts (id uuid primary key default gen_random_uuid(), public_reference text not null unique default ('DD-CON-' || upper(substr(replace(gen_random_uuid()::text,'-',''),1,8))), award_id uuid references public.dd_contract_awards(id) on delete set null, pursuit_id uuid references public.dd_contract_pursuits(id) on delete set null, buyer_organization_id uuid references public.dd_client_organizations(id) on delete set null, contract_number text, title text not null, contract_status text not null default 'DRAFT', procurement_path text, contract_type text, jurisdiction_code text not null default 'GA', start_date date, end_date date, option_years integer not null default 0, next_option_date date, recompete_date date, awarded_value numeric, funded_value numeric, ceiling_value numeric, payment_terms text, scope_summary text, performance_requirements text, reporting_requirements text, compliance_requirements jsonb not null default '[]'::jsonb, deliverables jsonb not null default '[]'::jsonb, key_contacts jsonb not null default '[]'::jsonb, contract_documents jsonb not null default '[]'::jsonb, performance_score numeric, renewal_strategy text, expansion_opportunities jsonb not null default '[]'::jsonb, owner_notes text, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.dd_contract_deliverables (id uuid primary key default gen_random_uuid(), contract_id uuid not null references public.dd_contracts(id) on delete cascade, deliverable_name text not null, description text, frequency text, due_at timestamptz, status text not null default 'OPEN', acceptance_criteria text, evidence_required boolean not null default false, completed_at timestamptz, completed_by uuid references auth.users(id), evidence_refs jsonb not null default '[]'::jsonb, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.dd_contract_compliance_items (id uuid primary key default gen_random_uuid(), contract_id uuid not null references public.dd_contracts(id) on delete cascade, requirement_name text not null, category text, required_by date, status text not null default 'OPEN', owner_user_id uuid references auth.users(id), evidence_refs jsonb not null default '[]'::jsonb, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.dd_contract_performance (id uuid primary key default gen_random_uuid(), contract_id uuid not null references public.dd_contracts(id) on delete cascade, period_start date, period_end date, work_orders_completed integer not null default 0, deliverables_completed integer not null default 0, qa_exceptions integer not null default 0, customer_issues integer not null default 0, invoices_issued numeric not null default 0, revenue_recognized numeric not null default 0, provider_cost numeric not null default 0, gross_contribution numeric not null default 0, performance_score numeric, buyer_feedback text, internal_notes text, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.dd_contract_events (id uuid primary key default gen_random_uuid(), contract_id uuid references public.dd_contracts(id) on delete cascade, pursuit_id uuid references public.dd_contract_pursuits(id) on delete cascade, opportunity_id uuid references public.dd_contract_opportunities(id) on delete cascade, event_type text not null, event_at timestamptz not null default now(), actor_user_id uuid references auth.users(id), description text, metadata jsonb not null default '{}'::jsonb);
alter table public.dd_work_orders add column if not exists contract_id uuid references public.dd_contracts(id) on delete set null;
alter table public.dd_jobs add column if not exists contract_id uuid references public.dd_contracts(id) on delete set null;
alter table public.dd_invoices add column if not exists contract_id uuid references public.dd_contracts(id) on delete set null;
create index if not exists idx_dd_contract_opportunities_stage_deadline on public.dd_contract_opportunities(stage,response_deadline);
create index if not exists idx_dd_contract_pursuits_stage_action on public.dd_contract_pursuits(pursuit_stage,next_action_due_at);
create index if not exists idx_dd_contract_proposals_status_deadline on public.dd_contract_proposals(proposal_status,submission_deadline);
create index if not exists idx_dd_contracts_status_end on public.dd_contracts(contract_status,end_date,recompete_date);
create index if not exists idx_dd_contract_deliverables_due on public.dd_contract_deliverables(contract_id,due_at,status);
create index if not exists idx_dd_contract_compliance_due on public.dd_contract_compliance_items(contract_id,required_by,status);
create index if not exists idx_dd_contract_performance_period on public.dd_contract_performance(contract_id,period_end);
create index if not exists idx_dd_contract_events_time on public.dd_contract_events(event_at desc);
alter table public.dd_contract_opportunities enable row level security; alter table public.dd_contract_buyers enable row level security; alter table public.dd_contract_pursuits enable row level security; alter table public.dd_contract_solicitations enable row level security; alter table public.dd_contract_proposals enable row level security; alter table public.dd_contract_awards enable row level security; alter table public.dd_contracts enable row level security; alter table public.dd_contract_deliverables enable row level security; alter table public.dd_contract_compliance_items enable row level security; alter table public.dd_contract_performance enable row level security; alter table public.dd_contract_events enable row level security;
create or replace function public.dd_contract_staff_access() returns boolean language sql stable security definer set search_path=public as $$ select coalesce((auth.jwt()->'app_metadata'->>'role') in ('owner','admin','staff_admin','staff'),false) or exists (select 1 from public.dd_portal_identities p where p.auth_user_id=auth.uid() and p.is_active and p.portal_role in ('staff_admin','owner')); $$;
revoke all on function public.dd_contract_staff_access() from public; grant execute on function public.dd_contract_staff_access() to authenticated;
create policy dd_contract_opportunities_staff_all on public.dd_contract_opportunities for all to authenticated using (public.dd_contract_staff_access()) with check (public.dd_contract_staff_access());
create policy dd_contract_buyers_staff_all on public.dd_contract_buyers for all to authenticated using (public.dd_contract_staff_access()) with check (public.dd_contract_staff_access());
create policy dd_contract_pursuits_staff_all on public.dd_contract_pursuits for all to authenticated using (public.dd_contract_staff_access()) with check (public.dd_contract_staff_access());
create policy dd_contract_solicitations_staff_all on public.dd_contract_solicitations for all to authenticated using (public.dd_contract_staff_access()) with check (public.dd_contract_staff_access());
create policy dd_contract_proposals_staff_all on public.dd_contract_proposals for all to authenticated using (public.dd_contract_staff_access()) with check (public.dd_contract_staff_access());
create policy dd_contract_awards_staff_all on public.dd_contract_awards for all to authenticated using (public.dd_contract_staff_access()) with check (public.dd_contract_staff_access());
create policy dd_contracts_staff_all on public.dd_contracts for all to authenticated using (public.dd_contract_staff_access()) with check (public.dd_contract_staff_access());
create policy dd_contract_deliverables_staff_all on public.dd_contract_deliverables for all to authenticated using (public.dd_contract_staff_access()) with check (public.dd_contract_staff_access());
create policy dd_contract_compliance_staff_all on public.dd_contract_compliance_items for all to authenticated using (public.dd_contract_staff_access()) with check (public.dd_contract_staff_access());
create policy dd_contract_performance_staff_all on public.dd_contract_performance for all to authenticated using (public.dd_contract_staff_access()) with check (public.dd_contract_staff_access());
create policy dd_contract_events_staff_all on public.dd_contract_events for all to authenticated using (public.dd_contract_staff_access()) with check (public.dd_contract_staff_access());
create policy dd_contracts_customer_read on public.dd_contracts for select to authenticated using (buyer_organization_id is not null and exists (select 1 from public.dd_portal_identities p where p.auth_user_id=auth.uid() and p.is_active and p.organization_id=dd_contracts.buyer_organization_id and p.portal_role in ('property_manager','procurement','customer')));
create policy dd_contract_events_customer_read on public.dd_contract_events for select to authenticated using (contract_id is not null and exists (select 1 from public.dd_contracts c join public.dd_portal_identities p on p.organization_id=c.buyer_organization_id where c.id=dd_contract_events.contract_id and p.auth_user_id=auth.uid() and p.is_active and p.portal_role in ('property_manager','procurement','customer')));
create or replace function public.dd_contract_touch_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end; $$;

drop trigger if exists trg_dd_contract_opportunities_updated on public.dd_contract_opportunities; create trigger trg_dd_contract_opportunities_updated before update on public.dd_contract_opportunities for each row execute function public.dd_contract_touch_updated_at();
drop trigger if exists trg_dd_contract_buyers_updated on public.dd_contract_buyers; create trigger trg_dd_contract_buyers_updated before update on public.dd_contract_buyers for each row execute function public.dd_contract_touch_updated_at();
drop trigger if exists trg_dd_contract_pursuits_updated on public.dd_contract_pursuits; create trigger trg_dd_contract_pursuits_updated before update on public.dd_contract_pursuits for each row execute function public.dd_contract_touch_updated_at();
drop trigger if exists trg_dd_contract_solicitations_updated on public.dd_contract_solicitations; create trigger trg_dd_contract_solicitations_updated before update on public.dd_contract_solicitations for each row execute function public.dd_contract_touch_updated_at();
drop trigger if exists trg_dd_contract_proposals_updated on public.dd_contract_proposals; create trigger trg_dd_contract_proposals_updated before update on public.dd_contract_proposals for each row execute function public.dd_contract_touch_updated_at();
drop trigger if exists trg_dd_contract_awards_updated on public.dd_contract_awards; create trigger trg_dd_contract_awards_updated before update on public.dd_contract_awards for each row execute function public.dd_contract_touch_updated_at();
drop trigger if exists trg_dd_contracts_updated on public.dd_contracts; create trigger trg_dd_contracts_updated before update on public.dd_contracts for each row execute function public.dd_contract_touch_updated_at();
drop trigger if exists trg_dd_contract_deliverables_updated on public.dd_contract_deliverables; create trigger trg_dd_contract_deliverables_updated before update on public.dd_contract_deliverables for each row execute function public.dd_contract_touch_updated_at();
drop trigger if exists trg_dd_contract_compliance_updated on public.dd_contract_compliance_items; create trigger trg_dd_contract_compliance_updated before update on public.dd_contract_compliance_items for each row execute function public.dd_contract_touch_updated_at();
drop trigger if exists trg_dd_contract_performance_updated on public.dd_contract_performance; create trigger trg_dd_contract_performance_updated before update on public.dd_contract_performance for each row execute function public.dd_contract_touch_updated_at();

create table if not exists public.dd_contract_qualification_items (id uuid primary key default gen_random_uuid(), pursuit_id uuid not null references public.dd_contract_pursuits(id) on delete cascade, requirement_key text not null, requirement_name text not null, category text, status text not null default 'OPEN', required boolean not null default true, evidence_refs jsonb not null default '[]'::jsonb, notes text, owner_user_id uuid references auth.users(id), completed_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(pursuit_id,requirement_key));
create table if not exists public.dd_contract_submission_gates (id uuid primary key default gen_random_uuid(), proposal_id uuid not null unique references public.dd_contract_proposals(id) on delete cascade, status text not null default 'BLOCKED', solicitation_verified boolean not null default false, deadline_verified boolean not null default false, pricing_approved boolean not null default false, proposal_sections_complete boolean not null default false, compliance_complete boolean not null default false, required_attachments_complete boolean not null default false, submission_method_verified boolean not null default false, final_qa_complete boolean not null default false, authorized_to_submit boolean not null default false, submitted_at timestamptz, submitted_by uuid references auth.users(id), blocking_notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
alter table public.dd_contract_qualification_items enable row level security; alter table public.dd_contract_submission_gates enable row level security;
drop policy if exists dd_contract_qualification_staff_all on public.dd_contract_qualification_items; create policy dd_contract_qualification_staff_all on public.dd_contract_qualification_items for all to authenticated using (public.dd_contract_staff_access()) with check (public.dd_contract_staff_access());
drop policy if exists dd_contract_submission_gates_staff_all on public.dd_contract_submission_gates; create policy dd_contract_submission_gates_staff_all on public.dd_contract_submission_gates for all to authenticated using (public.dd_contract_staff_access()) with check (public.dd_contract_staff_access());
create index if not exists idx_dd_contract_qualification_pursuit_status on public.dd_contract_qualification_items(pursuit_id,status);
create index if not exists idx_dd_contract_submission_gate_status on public.dd_contract_submission_gates(status);
drop trigger if exists trg_dd_contract_qualification_updated on public.dd_contract_qualification_items; create trigger trg_dd_contract_qualification_updated before update on public.dd_contract_qualification_items for each row execute function public.dd_contract_touch_updated_at();
drop trigger if exists trg_dd_contract_submission_gate_updated on public.dd_contract_submission_gates; create trigger trg_dd_contract_submission_gate_updated before update on public.dd_contract_submission_gates for each row execute function public.dd_contract_touch_updated_at();
