-- TESTER research seeds for provider/compliance intelligence.
-- Source watches feed evidence only; evidence does not directly mutate provider authority.

insert into public.dd_research_work_queue(program_key,work_key,question,required_evidence,priority,status,next_action,owner_decision_required,metadata)
values
('WORKFORCE_ECONOMICS','PROVIDER_COMPLIANCE_REQUIREMENTS_GA_SC','Which provider onboarding, worker-classification, tax, identity, agreement, insurance, background-check and service-credential requirements apply to DANI providers in Georgia and South Carolina, by provider type and service risk?','Current primary/regulator authority with jurisdiction, effective date, applicability and evidence required','P0','QUEUED','Research and reconcile into provider requirement candidates; do not auto-authorize or reclassify providers.',false,'{"domain":"PROVIDER_ONBOARDING","feeds":["dd_provider_capability_requirements","dd_service_capability_requirements"],"release_blocked":true}'::jsonb),
('WORKFORCE_ECONOMICS','PROVIDER_DISPATCH_ELIGIBILITY_EVIDENCE','What evidence must be present before a DANI provider may be dispatch-eligible for a specific service, geography and job, and which requirements are universal versus service-specific?','Primary/regulator authority plus governed DANI operating evidence; distinguish legal requirement from DANI risk control','P0','QUEUED','Produce evidence-backed readiness inputs and explicit missing-data blockers; no provider authorization.',false,'{"domain":"PROVIDER_ONBOARDING","feeds":["provider_readiness","dispatch_eligibility"],"release_blocked":true}'::jsonb),
('WORKFORCE_ECONOMICS','PROVIDER_CLASSIFICATION_DECISION_INPUTS','Which current federal, Georgia and South Carolina worker-classification factors must DANI capture before routing a worker as 1099 provider versus W-2 employee?','IRS, DOL and state primary/regulator authority; effective dates and change status','P0','QUEUED','Map research evidence to classification decision inputs; never auto-classify a person.',false,'{"domain":"PROVIDER_ONBOARDING","feeds":["dd_worker_assignment_classification_guard_v1"],"release_blocked":true}'::jsonb),
('PROTECTION_BENEFITS','PROVIDER_INSURANCE_BACKGROUND_BOUNDARIES','When are liability/auto insurance, background screening, consent, credential verification or other protection controls legally required or prudent for DANI provider services in GA/SC?','Primary/regulator authority plus service-risk evidence; separate legal mandates from DANI policy choices','P0','QUEUED','Generate governed requirement candidates by service/risk; owner approval required for policy changes.',true,'{"domain":"PROVIDER_ONBOARDING","feeds":["dd_provider_capability_requirements","dd_service_capability_requirements"],"release_blocked":true}'::jsonb)
on conflict(work_key) do update set
 question=excluded.question,required_evidence=excluded.required_evidence,priority=excluded.priority,
 next_action=excluded.next_action,metadata=excluded.metadata,updated_at=now();

insert into public.dd_research_sources(program_key,work_key,source_key,source_title,source_url,authority_level,temporal_class,status,check_interval_minutes,expected_signals,next_check_at,metadata)
values
('WORKFORCE_ECONOMICS','PROVIDER_CLASSIFICATION_DECISION_INPUTS','IRS_IC_FORMS_TAX','IRS Forms and associated taxes for independent contractors','https://www.irs.gov/businesses/small-businesses-self-employed/forms-and-associated-taxes-for-independent-contractors','REGULATOR','CURRENT','ACTIVE',1440,'[{"signal":"w9_requirement","any":["Form W-9","W-9"]},{"signal":"1099_nec","any":["1099-NEC","nonemployee compensation"]}]'::jsonb,now(),'{"domain":"PROVIDER_ONBOARDING","publicOnly":true}'::jsonb),
('WORKFORCE_ECONOMICS','PROVIDER_CLASSIFICATION_DECISION_INPUTS','DOL_IC_CURRENT_2026','DOL Independent Contractor Classification','https://www.dol.gov/agencies/whd/flsa/misclassification/2026rulemaking','REGULATOR','CURRENT','ACTIVE',1440,'[{"signal":"classification_rule_status","any":["independent contractor","employee"]},{"signal":"economic_reality","any":["economic reality","control","profit or loss"]}]'::jsonb,now(),'{"domain":"PROVIDER_ONBOARDING","publicOnly":true}'::jsonb),
('PROTECTION_BENEFITS','PROVIDER_INSURANCE_BACKGROUND_BOUNDARIES','FTC_BACKGROUND_CHECKS','FTC/EEOC Background Checks: What Employers Need to Know','https://www.ftc.gov/business-guidance/resources/background-checks-what-employers-need-know','REGULATOR','CURRENT','ACTIVE',10080,'[{"signal":"fcra_background","any":["Fair Credit Reporting Act","FCRA"]},{"signal":"adverse_action","any":["adverse action","consumer report"]}]'::jsonb,now(),'{"domain":"PROVIDER_ONBOARDING","publicOnly":true}'::jsonb),
('WORKFORCE_ECONOMICS','PROVIDER_COMPLIANCE_REQUIREMENTS_GA_SC','GA_SOS_LICENSING_BOARDS','Georgia Secretary of State Licensing Division','https://sos.ga.gov/licensing-division-georgia-secretary-states-office','REGULATOR','CURRENT','ACTIVE',10080,'[{"signal":"ga_professional_licensing","any":["Professional Licensing","Licensing Boards","Contractors"]}]'::jsonb,now(),'{"jurisdiction":"GA","domain":"PROVIDER_ONBOARDING","publicOnly":true}'::jsonb),
('WORKFORCE_ECONOMICS','PROVIDER_COMPLIANCE_REQUIREMENTS_GA_SC','SC_LLR_PROFESSIONS','South Carolina LLR Professions and Occupations','https://www.llr.sc.gov/professions.aspx','REGULATOR','CURRENT','ACTIVE',10080,'[{"signal":"sc_professional_licensing","any":["Professional","Occupational","Licensing"]}]'::jsonb,now(),'{"jurisdiction":"SC","domain":"PROVIDER_ONBOARDING","publicOnly":true}'::jsonb)
on conflict(source_key) do update set
 work_key=excluded.work_key,source_title=excluded.source_title,source_url=excluded.source_url,
 authority_level=excluded.authority_level,status='ACTIVE',expected_signals=excluded.expected_signals,
 next_check_at=now(),metadata=excluded.metadata,updated_at=now();