insert into public.dd_master_service_universe (division,section,capability,service_family,service_name,commercial_object_type,canonical_sku,scope,exclusions,lifecycle_status,source_authority,legacy_ids_aliases) values
('01','01-B','CAP-01B-PET','Pet Care','Pet Sitting, Drop-In & Routine Pet Care','SERV','DNI-01B-001','Routine in-home pet care; visits, walks, cat/small-animal care and basic pet-area support.','Veterinary care, boarding, training and professional grooming.','PENDING_RECONCILIATION','Master pricing architecture','01B-001'),
('01','01-B','CAP-01B-PET','Pet Care','Pet Waste Removal & Pet Area Sanitation','SERV','DNI-01B-002','Pet waste and pet-area sanitation support.','Specialized remediation.','PENDING_RECONCILIATION','Master pricing architecture','01B-002'),
('01','01-B','CAP-01B-PET','Pet Care','Pet Feeding, Walking & Routine Care Plans','PROGRAM','DNI-01B-003','Scheduled recurring feeding, walking and routine pet-care plans.','Veterinary and regulated professional care.','PENDING_RECONCILIATION','Master pricing architecture','01B-003'),
('01','01-B','CAP-01B-PET','Pet Care','Pet Transportation & Appointment Support','SERV','DNI-01B-004','Pet transportation and appointment logistics through appropriately qualified providers.','Veterinary services themselves.','PENDING_RECONCILIATION','Master pricing architecture','01B-004'),
('01','01-B','CAP-01B-PET','Pet Care','Pet Supply Procurement & Delivery Coordination','SERV','DNI-01B-005','Pet food, litter, supplies and approved pickup/delivery coordination.','Prescription/regulated activity beyond permitted procurement scope.','PENDING_RECONCILIATION','Master pricing architecture','01B-005'),
('01','01-B','CAP-01B-PET','Pet Care','Pet Grooming, Hygiene & Grooming Coordination','SERV','DNI-01B-006','Basic household pet hygiene and coordination with qualified professional groomers.','Professional grooming unless performed by appropriately qualified/insured provider; veterinary care.','PENDING_RECONCILIATION','Master pricing architecture','01B-006'),
('01','01-B','CAP-01B-PET','Pet Care','Pet Move-In, Move-Out & Transition Support','SERV','DNI-01B-007','Pet-specific relocation preparation, moving-day support and new-home setup.','Moving company services and regulated transportation unless separately qualified.','PENDING_RECONCILIATION','Master pricing architecture','01B-007'),
('01','01-B','CAP-01B-PET','Pet Care + Household Concierge','Pet Home Watch & Away-From-Home Support','PROGRAM','DNI-01B-008','Pet support plus basic household observation while client is away.','Dedicated home-watch/regulated specialty services beyond scope.','PENDING_RECONCILIATION','Master pricing architecture','01B-008'),
('01','01-B','CAP-01B-PET','Pet Care','Pet Event, Gathering & Social Support','SERV','DNI-01B-009','Temporary pet-care and pet-logistics support around events and gatherings.','Event planning itself.','PENDING_RECONCILIATION','Master pricing architecture','01B-009'),
('01','01-B','CAP-01B-PET','Pet Care','Pet-Safe Home Preparation, Pet-Proofing & Pet Area Setup','SERV','DNI-01B-010','Pet-proofing, pet-area setup and household preparation.','Structural work.','PENDING_RECONCILIATION','Master pricing architecture','01B-010'),
('01','01-F','CAP-01F-SEASONAL','Seasonal & Holiday Home Services','Holiday & Seasonal Home Decorating','SERV','DNI-01F-001','Seasonal/holiday decorating, setup, takedown and related coordination.','Electrical repairs and unsafe/high-access work without qualified specialists.','PENDING_RECONCILIATION','Master pricing architecture','01D-003 historical placement'),
('01','01-G','CAP-01G-SEASONAL','Household Programs','Household Membership & Maintenance Programs','PROGRAM','DNI-01G-001','Recurring household maintenance/member program concepts combining eligible Division 01 services.','No assumption that every component is included; individual services remain separately governed.','PENDING_RECONCILIATION','Audit & Strategic Plan + Master pricing architecture','01G legacy program layer')
ON CONFLICT DO NOTHING;