CREATE TABLE IF NOT EXISTS public.dd_service_commercial_behavior (service_id uuid PRIMARY KEY REFERENCES public.services(id) ON DELETE CASCADE, independent_purchase boolean NOT NULL, multi_division_composable boolean NOT NULL, multi_service_work_order boolean NOT NULL, primary_use_cases text[] NOT NULL DEFAULT '{}', primary_form_factors text[] NOT NULL DEFAULT '{}', customer_journey text, composition_notes text, fulfillment_implications text, ingress_rule text, gate_status text NOT NULL DEFAULT 'PENDING', gate_version text NOT NULL DEFAULT '2026-08-27-G01', reviewed_at timestamptz NOT NULL DEFAULT now(), notes text);
CREATE INDEX IF NOT EXISTS idx_dd_service_commercial_behavior_gate_status ON public.dd_service_commercial_behavior(gate_status);
ALTER TABLE public.dd_service_commercial_behavior ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.dd_service_commercial_behavior FROM anon, authenticated;

INSERT INTO public.dd_service_commercial_behavior(service_id,independent_purchase,multi_division_composable,multi_service_work_order,primary_use_cases,primary_form_factors,customer_journey,composition_notes,fulfillment_implications,ingress_rule,gate_status,notes)
SELECT s.id,true,true,true,ARRAY['Routine household maintenance','Weekly/bi-weekly upkeep','Lifestyle preservation'],ARRAY['ONE_TIME_TRIAL','MEMBERSHIP','PROGRAM'],'High-frequency recurring loop','Can be composed with services from other divisions; supports multi-service household work orders.','Consistent scheduling, access/key management, SOPs, time-boxing and quality control.','Direct purchase permitted; recurring membership/program optimized.','LOCKED','Gate 01 review based on current commercial behavior matrix.' FROM public.services s WHERE s.sku='DNI-01A-001'
ON CONFLICT(service_id) DO UPDATE SET independent_purchase=EXCLUDED.independent_purchase,multi_division_composable=EXCLUDED.multi_division_composable,multi_service_work_order=EXCLUDED.multi_service_work_order,primary_use_cases=EXCLUDED.primary_use_cases,primary_form_factors=EXCLUDED.primary_form_factors,customer_journey=EXCLUDED.customer_journey,composition_notes=EXCLUDED.composition_notes,fulfillment_implications=EXCLUDED.fulfillment_implications,ingress_rule=EXCLUDED.ingress_rule,gate_status=EXCLUDED.gate_status,reviewed_at=now();

INSERT INTO public.dd_service_commercial_behavior(service_id,independent_purchase,multi_division_composable,multi_service_work_order,primary_use_cases,primary_form_factors,customer_journey,composition_notes,fulfillment_implications,ingress_rule,gate_status,notes)
SELECT s.id,true,true,true,ARRAY['Seasonal deep clean','Post-renovation dust recovery','Onboarding baseline before routine service'],ARRAY['ONE_TIME','MEMBERSHIP_ENTRY_REQUIREMENT'],'Low-frequency transactional milestone','Can be composed with transition, plant, pet and other household services.','Variable duration, intensive materials, extended or multi-provider allocation may be required.','Direct purchase permitted; may serve as onboarding requirement.','LOCKED','Gate 01 review based on current commercial behavior matrix.' FROM public.services s WHERE s.sku='DNI-01A-002'
ON CONFLICT(service_id) DO UPDATE SET independent_purchase=EXCLUDED.independent_purchase,multi_division_composable=EXCLUDED.multi_division_composable,multi_service_work_order=EXCLUDED.multi_service_work_order,primary_use_cases=EXCLUDED.primary_use_cases,primary_form_factors=EXCLUDED.primary_form_factors,customer_journey=EXCLUDED.customer_journey,composition_notes=EXCLUDED.composition_notes,fulfillment_implications=EXCLUDED.fulfillment_implications,ingress_rule=EXCLUDED.ingress_rule,gate_status=EXCLUDED.gate_status,reviewed_at=now();

INSERT INTO public.dd_service_commercial_behavior(service_id,independent_purchase,multi_division_composable,multi_service_work_order,primary_use_cases,primary_form_factors,customer_journey,composition_notes,fulfillment_implications,ingress_rule,gate_status,notes)
SELECT s.id,true,true,true,ARRAY['End-of-tenancy compliance','Security-deposit preparation','Immediate rental/listing preparation'],ARRAY['ONE_TIME','PACKAGE_COMPONENT','CUSTOM_PROJECT'],'Single-event transition milestone','Can combine with move/transition, disposal and other property services.','Time-critical; photo/evidence trail and zero-tolerance QA required.','Direct purchase permitted; may be packaged.','LOCKED','Gate 01 review based on current commercial behavior matrix. No promise of deposit refund.' FROM public.services s WHERE s.sku='DNI-01A-003'
ON CONFLICT(service_id) DO UPDATE SET independent_purchase=EXCLUDED.independent_purchase,multi_division_composable=EXCLUDED.multi_division_composable,multi_service_work_order=EXCLUDED.multi_service_work_order,primary_use_cases=EXCLUDED.primary_use_cases,primary_form_factors=EXCLUDED.primary_form_factors,customer_journey=EXCLUDED.customer_journey,composition_notes=EXCLUDED.composition_notes,fulfillment_implications=EXCLUDED.fulfillment_implications,ingress_rule=EXCLUDED.ingress_rule,gate_status=EXCLUDED.gate_status,reviewed_at=now(),notes=EXCLUDED.notes;

INSERT INTO public.dd_service_commercial_behavior(service_id,independent_purchase,multi_division_composable,multi_service_work_order,primary_use_cases,primary_form_factors,customer_journey,composition_notes,fulfillment_implications,ingress_rule,gate_status,notes)
SELECT s.id,false,true,true,ARRAY['Weekly textile management','Convenience','Garment/textile preservation'],ARRAY['MEMBERSHIP_ALLOCATION','PROGRAM_COMPONENT','ADD_ON'],'High-frequency routine lifestyle loop','May combine with cleaning, linen and household programs.','Requires textile-processing workflow, transport/bag tracking, facility/vendor coordination and chain-of-custody controls.','Must be attached to an eligible cleaning service or membership/program; standalone purchase disabled by current commercial rule.','LOCKED','Gate 01 review based on current commercial behavior matrix.' FROM public.services s WHERE s.sku='DNI-01A-004'
ON CONFLICT(service_id) DO UPDATE SET independent_purchase=EXCLUDED.independent_purchase,multi_division_composable=EXCLUDED.multi_division_composable,multi_service_work_order=EXCLUDED.multi_service_work_order,primary_use_cases=EXCLUDED.primary_use_cases,primary_form_factors=EXCLUDED.primary_form_factors,customer_journey=EXCLUDED.customer_journey,composition_notes=EXCLUDED.composition_notes,fulfillment_implications=EXCLUDED.fulfillment_implications,ingress_rule=EXCLUDED.ingress_rule,gate_status=EXCLUDED.gate_status,reviewed_at=now();

INSERT INTO public.dd_service_commercial_behavior(service_id,independent_purchase,multi_division_composable,multi_service_work_order,primary_use_cases,primary_form_factors,customer_journey,composition_notes,fulfillment_implications,ingress_rule,gate_status,notes)
SELECT s.id,false,true,true,ARRAY['Hospitality-grade bed management','Recurring linen hygiene','Guest-room preparation'],ARRAY['MEMBERSHIP_ADD_ON','PROGRAM_COMPONENT','RETAINER_COMPONENT'],'Ultra-high-frequency recurring layer','May combine with cleaning, home-watch and property operations.','Requires access schedule synchronization, presentation standards and laundry/inventory turnaround controls.','Must attach to eligible cleaning, membership, program or retainer; no raw standalone purchase.','LOCKED','Gate 01 review based on current commercial behavior matrix.' FROM public.services s WHERE s.sku='DNI-01A-005'
ON CONFLICT(service_id) DO UPDATE SET independent_purchase=EXCLUDED.independent_purchase,multi_division_composable=EXCLUDED.multi_division_composable,multi_service_work_order=EXCLUDED.multi_service_work_order,primary_use_cases=EXCLUDED.primary_use_cases,primary_form_factors=EXCLUDED.primary_form_factors,customer_journey=EXCLUDED.customer_journey,composition_notes=EXCLUDED.composition_notes,fulfillment_implications=EXCLUDED.fulfillment_implications,ingress_rule=EXCLUDED.ingress_rule,gate_status=EXCLUDED.gate_status,reviewed_at=now();

INSERT INTO public.dd_service_commercial_behavior(service_id,independent_purchase,multi_division_composable,multi_service_work_order,primary_use_cases,primary_form_factors,customer_journey,composition_notes,fulfillment_implications,ingress_rule,gate_status,notes)
SELECT s.id,true,true,true,ARRAY['Seasonal wardrobe change','Lifestyle clutter management','Post-move unpacking organization'],ARRAY['STANDALONE','PACKAGE','MEMBERSHIP_BENEFIT','CUSTOM_PROJECT'],'Medium-frequency lifestyle transformation milestone','Can combine with move, cleaning and household concierge services.','Requires trusted organizational provider and careful handling of personal property.','Direct purchase permitted.','LOCKED','Gate 01 review based on current commercial behavior matrix.' FROM public.services s WHERE s.sku='DNI-01A-006'
ON CONFLICT(service_id) DO UPDATE SET independent_purchase=EXCLUDED.independent_purchase,multi_division_composable=EXCLUDED.multi_division_composable,multi_service_work_order=EXCLUDED.multi_service_work_order,primary_use_cases=EXCLUDED.primary_use_cases,primary_form_factors=EXCLUDED.primary_form_factors,customer_journey=EXCLUDED.customer_journey,composition_notes=EXCLUDED.composition_notes,fulfillment_implications=EXCLUDED.fulfillment_implications,ingress_rule=EXCLUDED.ingress_rule,gate_status=EXCLUDED.gate_status,reviewed_at=now();

INSERT INTO public.dd_service_commercial_behavior(service_id,independent_purchase,multi_division_composable,multi_service_work_order,primary_use_cases,primary_form_factors,customer_journey,composition_notes,fulfillment_implications,ingress_rule,gate_status,notes)
SELECT s.id,true,true,true,ARRAY['Kitchen functional optimization','Meal-prep staging','Post-move household baseline'],ARRAY['STANDALONE','PACKAGE','PROGRAM_COMPONENT'],'Project-based transformation milestone','Can combine with cleaning, move/transition, concierge and household programs.','Requires organizational capability, container/product sourcing and customer preference coordination.','Direct purchase permitted.','LOCKED','Gate 01 review based on current commercial behavior matrix.' FROM public.services s WHERE s.sku='DNI-01A-007'
ON CONFLICT(service_id) DO UPDATE SET independent_purchase=EXCLUDED.independent_purchase,multi_division_composable=EXCLUDED.multi_division_composable,multi_service_work_order=EXCLUDED.multi_service_work_order,primary_use_cases=EXCLUDED.primary_use_cases,primary_form_factors=EXCLUDED.primary_form_factors,customer_journey=EXCLUDED.customer_journey,composition_notes=EXCLUDED.composition_notes,fulfillment_implications=EXCLUDED.fulfillment_implications,ingress_rule=EXCLUDED.ingress_rule,gate_status=EXCLUDED.gate_status,reviewed_at=now();

INSERT INTO public.dd_service_commercial_behavior(service_id,independent_purchase,multi_division_composable,multi_service_work_order,primary_use_cases,primary_form_factors,customer_journey,composition_notes,fulfillment_implications,ingress_rule,gate_status,notes)
SELECT s.id,true,true,true,ARRAY['Estate clearing','Downsizing','Divorce/life transition','Estate disposition preparation'],ARRAY['CUSTOM_PROJECT','SOW'],'High-friction, high-value single-event milestone','May combine with organization, cleaning, logistics, disposal, real-estate preparation and other divisions.','Sensitive handling, sorting, inventory, logistics/hauling coordination and vendor management.','Direct inquiry permitted; quote/SOW required before execution.','LOCKED','Gate 01 review based on current commercial behavior matrix. Probate-attorney relationship belongs to CH05 Businesses/Commercial unless the buyer is itself a qualifying real-estate office/brokerage.' FROM public.services s WHERE s.sku='DNI-01A-008'
ON CONFLICT(service_id) DO UPDATE SET independent_purchase=EXCLUDED.independent_purchase,multi_division_composable=EXCLUDED.multi_division_composable,multi_service_work_order=EXCLUDED.multi_service_work_order,primary_use_cases=EXCLUDED.primary_use_cases,primary_form_factors=EXCLUDED.primary_form_factors,customer_journey=EXCLUDED.customer_journey,composition_notes=EXCLUDED.composition_notes,fulfillment_implications=EXCLUDED.fulfillment_implications,ingress_rule=EXCLUDED.ingress_rule,gate_status=EXCLUDED.gate_status,reviewed_at=now(),notes=EXCLUDED.notes;