-- Thumbtack Pro webhook integration. Applied to production via Supabase migration add_thumbtack_pro_webhook_integration.
create table if not exists public.dd_integration_webhook_credentials(provider text primary key,secret_sha256 text not null,header_name text not null default 'x-dani-webhook-secret',is_active boolean not null default true,updated_at timestamptz not null default now());
alter table public.dd_integration_webhook_credentials enable row level security;
insert into public.dd_integration_webhook_credentials(provider,secret_sha256,header_name,is_active) values ('THUMBTACK','a27460f9f8cacb11f84f09603c0b1aa93c70004b73fd3a80968bfa9b9ca4739b','x-dani-webhook-secret',true) on conflict(provider) do update set secret_sha256=excluded.secret_sha256,header_name=excluded.header_name,is_active=true,updated_at=now();
create table if not exists public.dd_external_webhook_events(id uuid primary key default gen_random_uuid(),provider text not null,event_key text not null,event_type text,external_object_id text,payload jsonb not null default '{}'::jsonb,processing_status text not null default 'RECEIVED',processing_error text,received_at timestamptz not null default now(),processed_at timestamptz,unique(provider,event_key));
alter table public.dd_external_webhook_events enable row level security;
create table if not exists public.dd_external_lead_messages(id uuid primary key default gen_random_uuid(),provider text not null,external_message_id text not null,external_lead_id text,sales_queue_id uuid references public.dd_sales_queue(id) on delete set null,direction text,sender_name text,message_text text,occurred_at timestamptz,raw_payload jsonb not null default '{}'::jsonb,needs_response boolean not null default true,created_at timestamptz not null default now(),unique(provider,external_message_id));
alter table public.dd_external_lead_messages enable row level security;
create table if not exists public.dd_external_reviews(id uuid primary key default gen_random_uuid(),provider text not null,external_review_id text not null,external_lead_id text,sales_queue_id uuid references public.dd_sales_queue(id) on delete set null,reviewer_name text,rating numeric,review_text text,occurred_at timestamptz,raw_payload jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),unique(provider,external_review_id));
alter table public.dd_external_reviews enable row level security;
create unique index if not exists dd_sales_queue_thumbtack_lead_unique on public.dd_sales_queue ((sales_metadata->>'thumbtack_lead_id')) where source='THUMBTACK' and sales_metadata ? 'thumbtack_lead_id';