-- Release-contract reconciliation for the ordered remediation pass.
-- Quote schemas are derived from each service's canonical description.
-- Initial-payment ledger is a separate contract from the full-service Stripe price.

UPDATE public.services
SET quote_input_schema = '{"ui_mode":"CONFIGURED_QUOTE","version":"2026-09-20-notary-route-v1","fields":[{"key":"appointment_count","label":"Appointments","type":"number","classification":"PRICING","required":true,"min":1},{"key":"signer_count","label":"Signer Count","type":"number","classification":"SCOPE","required":true,"min":1},{"key":"package_summary","label":"Package / Document Summary","type":"textarea","classification":"SCOPE","required":true},{"key":"lender_title_instructions","label":"Lender / Title Instructions","type":"textarea","classification":"UNDERWRITING","required":true},{"key":"signing_location","label":"Signing Location","type":"text","classification":"SCOPE","required":true},{"key":"miles_one_way","label":"Miles One Way","type":"number","classification":"PRICING_MODIFIER","required":true,"min":0},{"key":"rush","label":"Rush","type":"boolean","classification":"PRICING_MODIFIER","required":false},{"key":"return_instructions","label":"Document Return Instructions","type":"textarea","classification":"ROUTING","required":true}],"commercial_inputs":["miles_one_way","rush"],"quote_rules":{"base_price":150,"travel":"standard travel rate after included local mileage","rush":"standard rush policy"},"notes":"Structured quote path derived only from the canonical service description; legal/title instructions remain customer-supplied and require review."}'::jsonb
WHERE sku='DNI-05A-008';

UPDATE public.services
SET quote_input_schema = '{"ui_mode":"CONFIGURED_QUOTE","version":"2026-09-20-notary-route-v1","fields":[{"key":"appointment_count","label":"Appointments","type":"number","classification":"PRICING","required":true,"min":1},{"key":"document_stop_count","label":"Document Stops","type":"number","classification":"PRICING","required":true,"min":1},{"key":"route_start","label":"Route Start","type":"text","classification":"ROUTING","required":true},{"key":"route_end","label":"Route End","type":"text","classification":"ROUTING","required":true},{"key":"miles_one_way","label":"Miles One Way","type":"number","classification":"PRICING_MODIFIER","required":true,"min":0},{"key":"commission_scope_notes","label":"Commission Scope Notes","type":"textarea","classification":"UNDERWRITING","required":true},{"key":"document_stop_notes","label":"Document Stop Notes","type":"textarea","classification":"SCOPE","required":true},{"key":"rush","label":"Rush","type":"boolean","classification":"PRICING_MODIFIER","required":false}],"commercial_inputs":["miles_one_way","rush"],"quote_rules":{"base_price":95,"travel":"standard travel rate after included local mileage","rush":"standard rush policy"},"notes":"Structured quote path derived only from the canonical service description; commission scope remains subject to applicable restrictions."}'::jsonb
WHERE sku='DNI-05A-016';

ALTER TABLE public.dd_service_work_order_routing_templates ALTER COLUMN channel_code DROP NOT NULL;

-- Do not manufacture channel authorization rows. Matrix PENDING rows remain pending until explicit channel adjudication exists.
