-- DANI DECLARES LLC
-- Phase 4 / Migration 1: Operations Command Center Foundation
--
-- SAFETY STATUS: DRAFT ONLY. DO NOT RUN AGAINST PRODUCTION UNTIL THE LIVE
-- DATABASE CATALOG HAS BEEN VERIFIED AGAINST THIS MIGRATION.
--
-- Design goals:
--   * additive only
--   * no ALTER/DROP/RENAME of existing business tables
--   * no data movement
--   * explicit dependencies on Supabase auth.users
--   * RLS enabled on every new application table
--
-- Existing repository evidence shows an established schema containing leads,
-- service_requests, divisions, services, estimates, jobs, invoices, fieldops,
-- and related tables. See docs/database-baseline-phase4.md.

begin;

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------------
-- 1. Portal profiles
-- ---------------------------------------------------------------------------
create table if not exists public.dd_portal_profiles (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique references auth.users(id) on delete cascade,
  role text not null default 'customer',
  full_name text,
  phone text,
  company_name text,
  is_active boolean not null default true,
  referral_code text unique,
  referred_by_profile_id uuid references public.dd_portal_profiles(id) on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint dd_portal_profiles_role_not_blank check (char_length(trim(role)) > 0)
);

create index if not exists idx_dd_portal_profiles_role
  on public.dd_portal_profiles(role);

create index if not exists idx_dd_portal_profiles_active
  on public.dd_portal_profiles(is_active);

create index if not exists idx_dd_portal_profiles_role_active
  on public.dd_portal_profiles(role, is_active);

-- ---------------------------------------------------------------------------
-- 2. Explicit application roles
-- ---------------------------------------------------------------------------
create table if not exists public.dd_user_roles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null,
  is_active boolean not null default true,
  granted_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint dd_user_roles_role_allowed
    check (role in ('owner', 'admin', 'staff_admin', 'staff', 'vendor', 'client', 'resident'))
);

create index if not exists idx_dd_user_roles_role_active
  on public.dd_user_roles(role, is_active);

-- ---------------------------------------------------------------------------
-- 3. Audit log
-- ---------------------------------------------------------------------------
create table if not exists public.dd_audit_logs (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references auth.users(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id text,
  old_data jsonb,
  new_data jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_dd_audit_logs_actor_created
  on public.dd_audit_logs(actor_user_id, created_at desc);

create index if not exists idx_dd_audit_logs_entity
  on public.dd_audit_logs(entity_type, entity_id, created_at desc);

create index if not exists idx_dd_audit_logs_action
  on public.dd_audit_logs(action, created_at desc);

-- ---------------------------------------------------------------------------
-- 4. Timestamp maintenance
-- ---------------------------------------------------------------------------
create or replace function public.dd_set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- Drop/recreate only the trigger objects owned by this migration; this does
-- not touch rows or table definitions.
drop trigger if exists trg_dd_portal_profiles_updated_at on public.dd_portal_profiles;
create trigger trg_dd_portal_profiles_updated_at
before update on public.dd_portal_profiles
for each row execute function public.dd_set_updated_at();

drop trigger if exists trg_dd_user_roles_updated_at on public.dd_user_roles;
create trigger trg_dd_user_roles_updated_at
before update on public.dd_user_roles
for each row execute function public.dd_set_updated_at();

-- ---------------------------------------------------------------------------
-- 5. Row-level security
-- ---------------------------------------------------------------------------
alter table public.dd_portal_profiles enable row level security;
alter table public.dd_user_roles enable row level security;
alter table public.dd_audit_logs enable row level security;

-- Users can read/update their own profile. Inserts are intentionally not
-- granted to anon/authenticated users; provisioning should happen through a
-- trusted server/admin workflow.
drop policy if exists dd_portal_profiles_select_own on public.dd_portal_profiles;
create policy dd_portal_profiles_select_own
on public.dd_portal_profiles
for select to authenticated
using (user_id = auth.uid());

drop policy if exists dd_portal_profiles_update_own on public.dd_portal_profiles;
create policy dd_portal_profiles_update_own
on public.dd_portal_profiles
for update to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

-- A user may read only their own explicit role row. Administrative writes are
-- reserved for service_role until a dedicated admin RPC is introduced.
drop policy if exists dd_user_roles_select_own on public.dd_user_roles;
create policy dd_user_roles_select_own
on public.dd_user_roles
for select to authenticated
using (user_id = auth.uid());

-- Audit records are append-only from trusted backend/service-role code.
-- No authenticated client policy is created in Migration 1.

commit;

-- IMPORTANT: service_role bypasses RLS. Future admin RPCs should use
-- SECURITY DEFINER only where required, with a fixed search_path and explicit
-- authorization checks. Do not expose service_role credentials to React.
