insert into public.dd_research_intelligence_signals
(signal_key,source_kind,subject,observed_claim,evidence_locator,capability_tags,requires_independent_verification,metadata)
values
('seed-braintrust-agent-evals','RESEARCH_HYPOTHESIS','LLM regression and evaluation engineering','Agent changes should be scored against stable DANI cases before release.','{"origin":"user screenshot batch"}','{agent_evaluation,regression,release_gate}',true,'{"vendor_purchase_authority":false}'),
('seed-tripleten-systems','RESEARCH_HYPOTHESIS','Systems architecture and engineering defense','Architecture topics are research categories; scale-heavy components must be justified by measured need.','{"origin":"user screenshot batch"}','{system_design,api_contracts,data_architecture,cicd,threat_modeling}',true,'{"avoid_premature_complexity":true}'),
('seed-gatewise-property-tech','COMPETITOR_EVIDENCE','Property access and resident directory technology','Resident directories, QR/NFC access and visitor-management may expose CH03 capability opportunities.','{"origin":"user screenshot batch"}','{ch03,property_technology,nfc,qr,visitor_management}',true,'{"commercial_unlock":false}'),
('seed-quickbase-orchestration','COMPETITOR_EVIDENCE','Cross-system process orchestration','Cross-system process orchestration is a capability benchmark for the DANI control plane.','{"origin":"user screenshot batch"}','{orchestration,workflow,control_plane}',true,'{"vendor_purchase_authority":false}'),
('seed-close-crm','COMPETITOR_EVIDENCE','Communication-centered CRM','Communication-first CRM and reduced manual entry are benchmark capabilities.','{"origin":"user screenshot batch"}','{crm,communications,automation}',true,'{"vendor_purchase_authority":false}'),
('seed-housecallpro-field-service','COMPETITOR_EVIDENCE','Field-service platform capability packaging','Booking through accounting and recurring relationship should be benchmarked as an end-to-end chain.','{"origin":"user screenshot batch"}','{booking,estimate,payment,scheduling,dispatch,field_execution,qa,reviews,accounting}',true,'{"copy_competitor_prices":false}'),
('seed-linkedin-marketing','EXPERIMENT_HYPOTHESIS','Marketing funnel experiments','Text-first, link timing and engagement-to-offer tactics are hypotheses requiring DANI experiments.','{"origin":"user screenshot batch"}','{marketing,experiments,conversion}',true,'{"promote_to_fact":false}'),
('seed-hmg-provider-funnel','WORKFLOW_EVIDENCE','Recruiting and provider funnel','Acknowledgement, education, qualification, selection and scheduling form a workflow benchmark.','{"origin":"user screenshot batch"}','{provider_onboarding,nurture,qualification}',true,'{"copy_language":false}'),
('seed-for-rent-visual-lead','LEAD_SIGNAL','Observable rental lead signal','A public FOR RENT sign can be a lawful lead-discovery seed after public identity/contact verification.','{"origin":"user photo"}','{ch03,ch04,lead_discovery,property}',true,'{"automatic_outreach":false}'),
('seed-tobano-rental-lead','LEAD_SIGNAL','10411 Tobano Trail rental advertisement','A public rental advertisement can seed CH03/CH04 lead research after identity/contact verification.','{"origin":"user photo","address_as_observed":"10411 Tobano Trail, Jonesboro, GA 30238"}','{ch03,ch04,lead_discovery,property}',true,'{"automatic_outreach":false}'),
('seed-dani-historical-flyers','DANI_HISTORICAL_EVIDENCE','Historical DANI marketing and offers','Historical flyers expose offer evolution but legacy price/contact/discount/QR/service claims are not current authority.','{"origin":"user screenshot batch and Google Drive"}','{historical_offers,pricing_history,branding,services}',true,'{"authority":false}'),
('seed-cleaning-operations-system','DANI_HISTORICAL_EVIDENCE','Vertical business operations systems','Historical Cleaning Operations System suggests a verticalized business-in-a-box product hypothesis requiring current economics and market proof.','{"origin":"user flyer"}','{product_systems,vertical_saas_like,physical_digital_kits}',true,'{"commercial_unlock":false}'),
('seed-fortune-first-event-packages','COMPETITOR_EVIDENCE','Packaged event-rental economics','Package structure, inclusions, add-ons and booking incentives are competitor evidence, not DANI pricing authority.','{"origin":"user screenshot batch"}','{events,packages,addons,pricing_research}',true,'{"copy_price_authority":false}')
on conflict(signal_key) do update set observed_claim=excluded.observed_claim,capability_tags=excluded.capability_tags,metadata=public.dd_research_intelligence_signals.metadata||excluded.metadata,updated_at=now();

insert into public.dd_capability_gap_assessments(capability_key,capability_name,research_work_key,metadata)
values
('agent_regression_evals','Agent regression/evaluation harness','agent-regression-evaluation-engineering','{"required_flow":["test_case","score","baseline","version","release_gate"]}'),
('ai_reliability_sre','Autonomous-agent reliability/SRE controls','ai-reliability-sre-control-plane','{"required_flow":["observe","slo","rollback","incident"]}'),
('security_threat_model','Threat-model driven security','security-threat-modeling','{"required_flow":["asset","identity","trust_boundary","attack_path","blast_radius","detection","recovery"]}'),
('property_access_tech','CH03 property access/directory technology','property-access-directory-technology','{"commercial_unlock":false}'),
('cross_system_orchestration','Cross-system orchestration','process-orchestration-benchmark','{"compare_existing_control_plane":true}'),
('field_service_chain','End-to-end field-service lifecycle','field-service-crm-capability-benchmark','{"proof_not_checkbox":true}'),
('visual_property_leads','Visual property lead discovery','visual-property-lead-discovery','{"automatic_outreach":false}'),
('vertical_business_systems','Vertical business operations systems','vertical-business-system-product-line','{"commercial_unlock":false}')
on conflict(capability_key) do update set research_work_key=excluded.research_work_key,metadata=public.dd_capability_gap_assessments.metadata||excluded.metadata,updated_at=now();
