begin;
-- Hydrate DANI-generic research programs only. ENTITY_ARCHITECTURE and project-specific
-- Shadow & Sol / Own Land research are intentionally excluded. All programs remain
-- RESEARCHING + release_blocked; this migration grants no commercialization authority.
insert into public.dd_research_programs(program_key,program_name,domain,objective,status,release_blocked,green_rule,metadata) values
('AI_DATA_GOVERNANCE_INTELLIGENCE','AI and Data Governance Intelligence','AI_DATA_GOVERNANCE','Continuously research model lifecycle governance, data provenance, evaluation, human oversight and automation boundaries.','RESEARCHING',true,'Evidence must be reconciled through governance before downstream authority.','{}'),
('BRAND_CREATIVE_INTELLIGENCE','Brand & Creative Intelligence','BRAND_CREATIVE','Continuously research DANI visual identity, photography, video, advertising creative, trust signals, presentation patterns and asset requirements without copying protected creative expression.','RESEARCHING',true,'Evidence-backed creative principles reconciled into brand governance; research never directly publishes customer-facing assets.','{"multimodal":true,"consumer_engines":["brand","marketing","website","sales","content"]}'),
('COMPANY_FINANCIAL_INTELLIGENCE','Company Financial & LLC Intelligence','COMPANY_FINANCIAL_QUARTERLY_COMPLIANCE','Continuously track comparable-company quarterly economics plus DANI LLC employer/tax/compliance obligations and material changes.','RESEARCHING',true,'Research informs candidates and owner/accounting decisions; it never automatically changes production pricing, payroll, classification or dispatch.','{"cadence":"DAILY_CHECK_EVENT_DRIVEN_QUARTERLY","production_mutation":false}'),
('CUSTOMER_MARKET_INTELLIGENCE','Customer & Market Intelligence','CUSTOMER_MARKET','Continuously research buyer needs, segments, journeys, objections, expectations, service gaps, competitor patterns, reputation signals and willingness-to-pay.','RESEARCHING',true,'Market evidence is reconciled into segment/service/experience hypotheses and tested; competitor evidence never becomes copied content.','{"consumer_engines":["service_discovery","sales","pricing","marketing","product"]}'),
('DIGITAL_EXPERIENCE_INTELLIGENCE','Digital Experience Intelligence','DIGITAL_EXPERIENCE','Continuously research UX, dashboards, portals, apps, navigation, forms, onboarding, accessibility and workflow design for customer, provider, staff and owner experiences.','RESEARCHING',true,'Evidence-backed experience requirements reconciled into product governance and tester acceptance before production.','{"multimodal":true,"consumer_engines":["owner_hq","customer_portal","provider_portal","staff_portal","quote_builder","apps"]}'),
('ENTERPRISE_RISK_INTELLIGENCE','Enterprise Risk Intelligence','ENTERPRISE_RISK','Continuously research privacy, accessibility, safety, insurance, legal/compliance, fraud/abuse, records retention, continuity and enterprise risk across DANI systems and services.','RESEARCHING',true,'Risk evidence is reconciled into governed controls with jurisdiction/effective-date provenance; no research item silently changes authority.','{"consumer_engines":["compliance","security","provider","customer","operations"]}'),
('FACILITIES_GEOGRAPHY_INTELLIGENCE','Facilities and Geography Intelligence','FACILITIES_GEOGRAPHY','Continuously research service geography, travel, facilities, storage, local operating dependencies, multistate operations and expansion readiness.','RESEARCHING',true,'Evidence must be reconciled through governance before downstream authority.','{}'),
('GROWTH_MEDIA_INTELLIGENCE','Growth & Media Intelligence','GROWTH_MEDIA','Continuously research campaigns, commercials, short-form/long-form video, social creative, media/channel behavior, lifecycle messaging, attribution and experimentation.','RESEARCHING',true,'Campaign and media hypotheses require governed claims, consent/compliance, creative review and measured tester/production feedback.','{"multimodal":true,"consumer_engines":["marketing","sales","creative","analytics"]}'),
('LEGAL_CONTRACT_INTELLIGENCE','Legal and Contract Intelligence','LEGAL_CONTRACT','Continuously research contract terms, notices, agreements, disputes, jurisdiction changes and transaction dependencies.','RESEARCHING',true,'Evidence must be reconciled through governance before downstream authority.','{}'),
('MERCH_COMMERCE','DANI Merch & Provider Gear Commerce','MERCH_RETAIL_PROVIDER_GEAR','Determine the governed DANI merchandise assortment, provider gear model, fulfillment rails and unit economics while preserving DANI runtime authority and avoiding duplicate commerce infrastructure.','RESEARCHING',true,'No merch lane is production-authorized until demand evidence, product/variant economics, fulfillment path, accounting/tax treatment, brand/IP, provider-classification implications, returns/support and release ownership are reconciled and owner-approved.','{"cass_review":true,"research_only":true,"production_authorized":false}'),
('OPERATING_MODEL_INTELLIGENCE','Peer Company Operating Model & Public Architecture Intelligence','COMPETITOR_OPERATIONS_PUBLIC_TECH_ARCHITECTURE','Continuously discover and compare public operating-model and architecture patterns from peer field-service, marketplace, property-service and multi-service companies so DANI can improve its own workflows with evidence instead of guesswork.','RESEARCHING',true,'Research may propose architecture/workflow changes only after multiple-source evidence and DANI-specific authority/economics/compliance review; it may never auto-copy a competitor pattern into production.','{"research_mode":"continuous","public_sources_only":true,"production_authorized":false}'),
('PEOPLE_ORG_INTELLIGENCE','People and Organization Intelligence','PEOPLE_ORG','Continuously research roles, training, supervision, separation of duties and organizational capacity.','RESEARCHING',true,'Evidence must be reconciled through governance before downstream authority.','{}'),
('PROCUREMENT_CAPITAL_INTELLIGENCE','Procurement & Capital Intelligence','PROCUREMENT_CAPITAL','Continuously research government procurement, certifications, solicitations, funding, grants, lending, bonding, vendor readiness and capital requirements relevant to DANI.','RESEARCHING',true,'Opportunities and requirements are reconciled to authoritative sources and DANI readiness; research cannot submit applications or commitments.','{"consumer_engines":["b2g","capital","accounting","owner_hq"]}'),
('RECORDS_KNOWLEDGE_INTELLIGENCE','Records and Knowledge Intelligence','RECORDS_KNOWLEDGE','Continuously research records lifecycle, retention, evidence preservation, metadata, versioning, archival, export and retrieval.','RESEARCHING',true,'Evidence must be reconciled through governance before downstream authority.','{}'),
('RESEARCH_GOVERNANCE_INTELLIGENCE','Research Governance and Coverage Intelligence','RESEARCH_GOVERNANCE','Audit research coverage, source freshness, unanswered questions and feedback gaps.','RESEARCHING',true,'Every governed engine has evidence inputs and feedback without research becoming authority.','{"self_audit":true}'),
('RESILIENCE_SUPPLY_CHAIN_INTELLIGENCE','Resilience and Supply Chain Intelligence','RESILIENCE_SUPPLY_CHAIN','Continuously research critical suppliers, equipment and material dependencies, alternatives, continuity, outages and recovery.','RESEARCHING',true,'Evidence must be reconciled through governance before downstream authority.','{}'),
('SERVICE_DISCOVERY','Continuous Service Discovery','MULTI_DIVISION_SERVICE_DISCOVERY','Continuously identify adjacent services across every DANI division, then determine market benefit, legal/insurance/safety boundaries, provider capability, economics, fulfillment and channel fit before any release.','RESEARCHING',true,'No candidate may enter the sellable catalog until duplicate check, authoritative compliance/licensing, insurance/safety, provider capability, economics, fulfillment, channel rules, underwriting and dd_service_release_contract_v1 all pass.','{"all_divisions":true,"research_mode":"continuous","auto_activation":false,"customer_release":"BLOCKED"}'),
('SERVICE_QUALITY_INTELLIGENCE','Service Quality & Fulfillment Intelligence','SERVICE_QUALITY','Continuously research service standards, QA evidence, failure modes, field procedures, materials/equipment, customer expectations and recovery patterns by service family.','RESEARCHING',true,'Evidence-backed service standards map to canonical services, fulfillment controls and QA tests before commercialization.','{"consumer_engines":["service_catalog","fulfillment","provider","qa","pricing"]}'),
('SUPPORT_CONVERSATION_INTELLIGENCE','Support & Conversation Intelligence','SUPPORT_CONVERSATION','Continuously research contact/help patterns, chatbot boundaries, escalation, knowledge retrieval, self-service, accessibility, service recovery and human handoff.','RESEARCHING',true,'Bot/support policies have evidence, safe escalation, tester replay and governed knowledge sources before customer-facing activation.','{"consumer_engines":["help_bot","contact_bot","support","crm","owner_hq"]}'),
('VENDOR_TECH_INTELLIGENCE','Vendor & Technology Intelligence','VENDOR_TECH','Continuously research platform/vendor changes, build-vs-buy options, integrations, costs, limits, deprecations, reliability, AI capabilities and exit risk.','RESEARCHING',true,'Technology recommendations require authority mapping, cost/risk evidence and tester proof before runtime adoption.','{"consumer_engines":["platform_runtime","integrations","security","finance"]}'),
('WEB_CONTENT_DISCOVERY','Web, Content & Discovery Intelligence','WEB_CONTENT_DISCOVERY','Continuously research site architecture, required pages, SEO/local discovery, content structure, conversion paths, schema, FAQs and channel-specific landing experiences.','RESEARCHING',true,'Governed information architecture and content requirements are evidenced, tested and approved; research cannot publish pages.','{"consumer_engines":["website","seo","content","sales","marketing"]}'),
('WORKFORCE_ECONOMICS','Workforce Economics & Classification','WORKFORCE_ECONOMICS_CLASSIFICATION','Continuously compare lawful W-2 and independent-provider fulfillment economics, utilization, quality, capacity and classification risk.','RESEARCHING',true,'No workforce-model promotion until loaded economics, classification, payroll, safety and stateful tester evidence are verified.','{"cadence":"CONTINUOUS_CODE_WORKER","production_mutation":false,"human_verification_required":true,"provider_readiness_fail_closed":true,"research_may_not_authorize_provider":true}')
on conflict(program_key) do update set
 program_name=excluded.program_name,domain=excluded.domain,objective=excluded.objective,status='RESEARCHING',
 release_blocked=true,green_rule=excluded.green_rule,
 metadata=coalesce(public.dd_research_programs.metadata,'{}'::jsonb)||excluded.metadata||jsonb_build_object('hydrated_for_production_research',true,'research_authority_only',true),
 updated_at=now();

-- Preserve existing production-only backfill and existing Protection & Benefits.
-- Explicit exclusion proof: this migration contains no ENTITY_ARCHITECTURE program key.
commit;
