-- South Carolina multi-state / foreign LLC + flex/live-work research expansion.
insert into public.dd_research_work_queue(program_key,work_key,question,required_evidence,priority,status,next_action,owner_decision_required,metadata)
values
('ENTITY_ARCHITECTURE','EA_SC_FOREIGN_LLC','What must DANI DECLARES LLC do to lawfully transact business in South Carolina as a Georgia foreign LLC, and what recurring entity/registered-agent/compliance duties follow?','South Carolina Secretary of State + SCDOR + governing statutes','P0','QUEUED','Track certificate-of-authority, certificate-of-existence, registered-agent, tax-account and renewal/compliance requirements.',true,'{"jurisdiction":"SC","cadence":"DAILY","cass_review":true,"accounting_impact":true}'::jsonb),
('ENTITY_ARCHITECTURE','EA_SC_FLEX_PROPERTY','What acquisition, financing, zoning, occupancy, building-code, fire/life-safety, accessibility and licensing rules apply to a South Carolina flex property used by DANI?','SC state authorities + specific county/municipal zoning/building/fire authorities + lender/insurer requirements','P0','QUEUED','Research statewide framework now; switch to parcel-specific diligence once a target property/location is identified.',true,'{"jurisdiction":"SC","cadence":"DAILY","cass_review":true,"accounting_impact":true,"parcel_specific_required":true}'::jsonb),
('ENTITY_ARCHITECTURE','EA_SC_LIVE_WORK','Under what legal conditions can Danielle live above or within a flex/commercial property used by DANI in South Carolina?','Parcel zoning district, permitted-use table, certificate of occupancy, building/fire code classification, local ordinances, lender and insurer requirements','P0','QUEUED','Treat residential occupancy as unverified until the exact parcel and municipality/county approve the use.',true,'{"jurisdiction":"SC","cadence":"DAILY","cass_review":true,"accounting_impact":true,"no_feasibility_assumption":true}'::jsonb),
('ENTITY_ARCHITECTURE','EA_SC_TAX_ACCOUNTS','What SC income, sales/use, business-personal-property, local-license and location-specific tax accounts will DANI need after foreign qualification and opening a flex location?','SCDOR + local government primary sources','P0','QUEUED','Build location-specific filing calendar and chart-of-accounts impacts before opening.',false,'{"jurisdiction":"SC","cadence":"DAILY","cass_review":true,"accounting_impact":true}'::jsonb),
('ENTITY_ARCHITECTURE','EA_SC_INTERENTITY','How can the SC DANI location lawfully interact with Shadow & Sol while preserving separate entities, books, assets, charitable purpose and FMV related-party rules?','IRS + SC/GA authority + actual contracts + legal/tax review','P1','QUEUED','Model service, lease, program, storage, event and shared-resource arrangements without commingling.',true,'{"jurisdiction":["SC","GA","US"],"cadence":"WEEKLY","cass_review":true,"accounting_impact":true}'::jsonb)
on conflict (work_key) do update set question=excluded.question,required_evidence=excluded.required_evidence,priority=excluded.priority,next_action=excluded.next_action,owner_decision_required=excluded.owner_decision_required,metadata=excluded.metadata,updated_at=now();

insert into public.dd_research_sources(program_key,work_key,source_key,source_title,source_url,authority_level,temporal_class,status,check_interval_minutes,expected_signals,next_check_at,metadata)
values
('ENTITY_ARCHITECTURE','EA_SC_FOREIGN_LLC','SC_SOS_FOREIGN_ENTITY','South Carolina SOS Business Entity FAQ - Foreign Entities','https://sos.sc.gov/node/155','REGULATOR','CURRENT','ACTIVE',1440,'["foreign","certificate of authority","certificate of existence","registered agent"]'::jsonb,now(),'{"jurisdiction":"SC","cass_review":true}'::jsonb),
('ENTITY_ARCHITECTURE','EA_SC_TAX_ACCOUNTS','SC_DOR_BUSINESS_TAX','SCDOR Business Tax Account Registration','https://dor.sc.gov/businesses/apply-business-tax-account','REGULATOR','CURRENT','ACTIVE',4320,'["business tax","physical address","NAICS","registration"]'::jsonb,now(),'{"jurisdiction":"SC","cass_review":true}'::jsonb),
('ENTITY_ARCHITECTURE','EA_SC_TAX_ACCOUNTS','SC_DOR_BPP','SCDOR Business Personal Property','https://dor.sc.gov/property/business-personal-property','REGULATOR','CURRENT','ACTIVE',4320,'["business personal property","equipment","fixtures","return","location"]'::jsonb,now(),'{"jurisdiction":"SC","cass_review":true}'::jsonb),
('ENTITY_ARCHITECTURE','EA_SC_TAX_ACCOUNTS','SC_DOR_SALES_TAX','SCDOR Sales Tax','https://dor.sc.gov/sales-use-tax-index/sales-tax','REGULATOR','CURRENT','ACTIVE',4320,'["retail license","sales tax","outlet","local tax"]'::jsonb,now(),'{"jurisdiction":"SC","cass_review":true}'::jsonb)
on conflict (source_key) do update set work_key=excluded.work_key,source_title=excluded.source_title,source_url=excluded.source_url,status='ACTIVE',check_interval_minutes=excluded.check_interval_minutes,expected_signals=excluded.expected_signals,next_check_at=least(dd_research_sources.next_check_at,now()),metadata=excluded.metadata,updated_at=now();

insert into public.dd_cass_finance_compliance_queue
(source_domain,source_key,review_type,title,accounting_question,legal_or_tax_dependency,financial_statement_area,entity_scope,priority,owner_decision_required)
values
('ENTITY_ARCHITECTURE','EA_SC_FOREIGN_LLC','MULTISTATE_ENTITY','DANI South Carolina foreign qualification','Track foreign-qualification costs, registered-agent costs, SC tax registrations, recurring compliance and nexus effects separately from Georgia-only overhead.','SC certificate of authority and tax/nexus requirements','Compliance expense / state taxes / entity records','DANI - GA domestic + SC foreign','P0',true),
('ENTITY_ARCHITECTURE','EA_SC_FLEX_PROPERTY','PROPERTY_ACCOUNTING','South Carolina flex property','Model purchase/lease, buildout, equipment, depreciation, utilities, insurance, property tax and business-personal-property consequences for a DANI flex site.','Zoning, occupancy, financing, insurance, BPP and local tax rules','Fixed assets / lease / buildout / depreciation / occupancy','DANI - SC location','P0',true),
('ENTITY_ARCHITECTURE','EA_SC_LIVE_WORK','MIXED_USE_ALLOCATION','SC live/work allocation','If residential occupancy is legally allowed, establish defensible allocation of personal housing costs versus DANI business-use costs and prohibit improper business deductions or charitable subsidy.','Local live/work approval + tax allocation + lender/insurer rules','Occupancy / utilities / rent or mortgage allocation','DANI + private','P0',true),
('ENTITY_ARCHITECTURE','EA_SC_TAX_ACCOUNTS','MULTISTATE_TAX','SC location tax/accounts','Set up SC location-level tracking for taxable sales, BPP assets, local licenses and state tax obligations when triggered.','SCDOR and local rules','Sales tax / BPP / state & local tax / location accounting','DANI - SC location','P0',false),
('ENTITY_ARCHITECTURE','EA_SC_INTERENTITY','INTERENTITY_ACCOUNTING','SC DANI / Shadow & Sol interaction','Keep SC DANI property/use/contracts separate from Shadow & Sol charitable assets and record any interentity service/lease arrangement at supported FMV.','Related-party/FMV/private-benefit rules','Intercompany / leases / service revenue / program expense','DANI + Shadow & Sol','P1',true)
on conflict (source_domain,source_key,review_type) do update set title=excluded.title,accounting_question=excluded.accounting_question,legal_or_tax_dependency=excluded.legal_or_tax_dependency,financial_statement_area=excluded.financial_statement_area,entity_scope=excluded.entity_scope,priority=excluded.priority,owner_decision_required=excluded.owner_decision_required,updated_at=now();
