alter table public.dd_commercial_reconciliation_runs enable row level security;
revoke all on public.dd_commercial_reconciliation_runs from public, anon, authenticated;
revoke all on public.dd_commercial_reconciliation_runs from service_role;
grant select, insert, update, delete on public.dd_commercial_reconciliation_runs to service_role;
alter table public.dd_operator_dashboard_external_tasks enable row level security;
revoke all on public.dd_operator_dashboard_external_tasks from public, anon, authenticated;
revoke all on public.dd_operator_dashboard_external_tasks from service_role;
grant select, insert, update, delete on public.dd_operator_dashboard_external_tasks to service_role;
alter table public.dd_support_cases enable row level security;
revoke all on public.dd_support_cases from public, anon, authenticated;
revoke all on public.dd_support_cases from service_role;
grant select, insert, update, delete on public.dd_support_cases to service_role;
alter table public.dd_unattended_green_runs enable row level security;
revoke all on public.dd_unattended_green_runs from public, anon, authenticated;
revoke all on public.dd_unattended_green_runs from service_role;
grant select, insert, update, delete on public.dd_unattended_green_runs to service_role;
alter table public.dd_software_build_runs enable row level security;
revoke all on public.dd_software_build_runs from public, anon, authenticated;
revoke all on public.dd_software_build_runs from service_role;
grant select, insert, update, delete on public.dd_software_build_runs to service_role;
alter table public.dd_software_build_work_queue enable row level security;
revoke all on public.dd_software_build_work_queue from public, anon, authenticated;
revoke all on public.dd_software_build_work_queue from service_role;
grant select, insert, update, delete on public.dd_software_build_work_queue to service_role;
alter table public.dd_automation_recipes enable row level security;
revoke all on public.dd_automation_recipes from public, anon, authenticated;
revoke all on public.dd_automation_recipes from service_role;
grant select, insert, update, delete on public.dd_automation_recipes to service_role;
alter table public.dd_automation_recipe_runs enable row level security;
revoke all on public.dd_automation_recipe_runs from public, anon, authenticated;
revoke all on public.dd_automation_recipe_runs from service_role;
grant select, insert, update, delete on public.dd_automation_recipe_runs to service_role;
alter table public.dd_capability_gap_queue enable row level security;
revoke all on public.dd_capability_gap_queue from public, anon, authenticated;
revoke all on public.dd_capability_gap_queue from service_role;
grant select, insert, update, delete on public.dd_capability_gap_queue to service_role;
alter table public.dd_code_repair_policy enable row level security;
revoke all on public.dd_code_repair_policy from public, anon, authenticated;
revoke all on public.dd_code_repair_policy from service_role;
grant select, insert, update, delete on public.dd_code_repair_policy to service_role;
alter table public.dd_owner_daily_briefs enable row level security;
revoke all on public.dd_owner_daily_briefs from public, anon, authenticated;
revoke all on public.dd_owner_daily_briefs from service_role;
grant select, insert, update, delete on public.dd_owner_daily_briefs to service_role;
alter table public.dd_provider_performance_snapshots enable row level security;
revoke all on public.dd_provider_performance_snapshots from public, anon, authenticated;
revoke all on public.dd_provider_performance_snapshots from service_role;
grant select, insert, update, delete on public.dd_provider_performance_snapshots to service_role;
alter table public.dd_research_authority_policy enable row level security;
revoke all on public.dd_research_authority_policy from public, anon, authenticated;
revoke all on public.dd_research_authority_policy from service_role;
grant select, insert, update, delete on public.dd_research_authority_policy to service_role;
alter table public.dd_service_discovery_candidates enable row level security;
revoke all on public.dd_service_discovery_candidates from public, anon, authenticated;
revoke all on public.dd_service_discovery_candidates from service_role;
grant select, insert, update, delete on public.dd_service_discovery_candidates to service_role;
alter table public.dd_service_discovery_runs enable row level security;
revoke all on public.dd_service_discovery_runs from public, anon, authenticated;
revoke all on public.dd_service_discovery_runs from service_role;
grant select, insert, update, delete on public.dd_service_discovery_runs to service_role;
alter table public.dd_service_support_readiness enable row level security;
revoke all on public.dd_service_support_readiness from public, anon, authenticated;
revoke all on public.dd_service_support_readiness from service_role;
grant select, insert, update, delete on public.dd_service_support_readiness to service_role;
