begin;

insert into public.dd_research_programs(program_key,program_name,domain,objective,status,release_blocked,green_rule,metadata)
values ('NICHE_FUNDING_INTELLIGENCE','Niche Funding & Grant Intelligence','FUNDING_CAPITAL_INTELLIGENCE','Continuously discover and revalidate narrow-fit grants, awards, capital programs and funding opportunities for DANI DECLARES and Shadow & Sol; verify social/newsletter claims against authoritative sources; preserve entity, geography, eligibility, amount, deadline and current-cycle provenance before owner review.','RESEARCHING',true,'Research only. A funding claim may reach REVIEW_READY only with current authoritative evidence for sponsor/program identity, applicant/entity eligibility, geography, award amount or range, current application status/deadline, and source provenance. Social posts and newsletters are discovery signals only. Never apply, spend, claim eligibility, contact a funder, or commingle DANI and Shadow & Sol without separate governed owner action.',jsonb_build_object('entities',jsonb_build_array('DANI_DECLARES','SHADOW_AND_SOL'),'geographies',jsonb_build_array('GEORGIA','SOUTH_CAROLINA','UNITED_STATES'),'strategy','NICHE_FIRST','source_policy','PRIMARY_OR_OFFICIAL_REQUIRED_FOR_PROMOTION','social_media_authority',false,'owner_approval_required_for_application',true,'cross_entity_commingling_authority',false,'channel_authority',jsonb_build_object('CH01','Resident Concierge','CH02','Property Management','CH03','Real Estate','CH04','Business','CH05','Government')))
on conflict(program_key) do update set program_name=excluded.program_name,domain=excluded.domain,objective=excluded.objective,status='RESEARCHING',release_blocked=true,green_rule=excluded.green_rule,metadata=coalesce(public.dd_research_programs.metadata,'{}'::jsonb)||excluded.metadata,updated_at=now();

insert into public.dd_research_work_queue(program_key,work_key,question,required_evidence,priority,status,next_action,owner_decision_required,metadata)
values
('NICHE_FUNDING_INTELLIGENCE','FUNDING:NICHE_DISCOVERY:DANI','Which narrow-fit current or upcoming grants, awards, capital programs and non-dilutive funding opportunities fit DANI DECLARES in Georgia, South Carolina or nationally, including women-owned, Black-woman-owned, mother-led/employer, facilities/property services, workforce, small-business equipment/capital and government-adjacent programs?','Current official sponsor/program source; exact applicant/entity eligibility; geography; award amount/range; application open/close dates or next-cycle date; restrictions; official application page; evidence date. Social/newsletter posts are discovery signals only.','P1','QUEUED','Discover and verify niche-first DANI funding against official/current sources; reject stale or mismatched claims rather than promoting them.',false,jsonb_build_object('entity_scope','DANI_DECLARES','funding_lane','NICHE_FIRST','application_authority',false,'social_claims_require_verification',true,'channel_map',jsonb_build_object('CH01','Resident Concierge','CH02','Property Management','CH03','Real Estate','CH04','Business','CH05','Government'))),
('NICHE_FUNDING_INTELLIGENCE','FUNDING:NICHE_DISCOVERY:SHADOW_SOL','Which narrow-fit current or upcoming grants, awards and capital programs fit Shadow & Sol in Georgia, South Carolina or nationally for land stewardship, agriculture/food systems, environmental education, community programming, field-school/workshops, facilities/land and mission access?','Current official sponsor/program source; nonprofit/for-profit/fiscal-sponsor eligibility as applicable; geography; award amount/range; restricted-use rules; application dates; land/capital eligibility; official application page; evidence date. Preserve arm-length separation from DANI.','P1','QUEUED','Discover and verify Shadow & Sol funding separately from DANI; preserve entity boundaries and restricted-fund rules.',false,jsonb_build_object('entity_scope','SHADOW_AND_SOL','funding_lane','MISSION_NICHE','application_authority',false,'cross_entity_commingling_authority',false,'social_claims_require_verification',true)),
('NICHE_FUNDING_INTELLIGENCE','FUNDING:REVERIFY:SOCIAL_CLAIMS:20261005','Revalidate the five grant claims observed in the Oct. 5 social-media reel: Halstead Grant, StreetShares Foundation grant, Kitty Fund, BOSS Impact Fund, and Good Food Fund. Determine whether each program currently exists, whether a current or next cycle is available, actual award amount, exact eligibility/geography, and fit for DANI DECLARES or Shadow & Sol. Also revalidate the surfaced EmpowHER fall-2026 lead.','Official/current sponsor or program evidence preferred. Record stale/discontinued/closed/geographically ineligible claims explicitly; do not preserve reel amounts as facts without verification.','P1','QUEUED','Treat the reel as a discovery signal and produce current verified/rejected funding evidence with next-cycle dates where supported.',false,jsonb_build_object('entity_scope','DANI_AND_SHADOW_SOL','signal_origin','SOCIAL_MEDIA_USER_SUPPLIED','observed_at','2026-10-05','application_authority',false,'claims',jsonb_build_array('HALSTEAD_GRANT','STREETSHARES_FOUNDATION','KITTY_FUND','BOSS_IMPACT_FUND','GOOD_FOOD_FUND','EMPOWHER'))),
('NICHE_FUNDING_INTELLIGENCE','FUNDING:VERIFY:SAM_NAICS','Verify which NAICS codes are actually registered for DANI DECLARES in SAM.gov before using NAICS overlap in grant, procurement, resilience or capital-fit scoring.','Current authoritative SAM.gov entity-registration evidence. Do not infer registered NAICS from internal declared focus or service catalog.','P0','QUEUED','Verify live SAM.gov NAICS registration and reconcile it to internal research without changing registration or claiming certifications.',false,jsonb_build_object('entity_scope','DANI_DECLARES','authority_required','SAM_GOV','registration_mutation_authority',false)),
('NICHE_FUNDING_INTELLIGENCE','FUNDING:LEGAL_SCOPE:SC_DISASTER_NOTARY','Before resilience/shelter-support/disaster-cleanup funding or marketing is promoted, verify Georgia/South Carolina service-scope and notary/jurisdiction constraints, especially emergency document/notary work across state lines.','Current authoritative state/legal/regulatory sources appropriate to each service. Preserve service work separately from notarial authority.','P0','QUEUED','Research jurisdiction/service constraints; do not market or claim cross-state notary authority from internal assumptions.',false,jsonb_build_object('entity_scope','DANI_DECLARES','resilience_cross_channel',true,'notary_scope_requires_separate_verification',true,'marketing_authority',false))
on conflict(work_key) do update set question=excluded.question,required_evidence=excluded.required_evidence,priority=excluded.priority,status=case when public.dd_research_work_queue.status='GREEN' then public.dd_research_work_queue.status else 'QUEUED' end,blocker=null,next_action=excluded.next_action,owner_decision_required=false,metadata=coalesce(public.dd_research_work_queue.metadata,'{}'::jsonb)||excluded.metadata,updated_at=now();

insert into public.dd_research_source_discovery_requests(request_key,program_key,gap_key,priority,request_status,discovery_question,source_requirements,metadata)
values
('FUNDING:DISCOVER:DANI:OFFICIAL','NICHE_FUNDING_INTELLIGENCE','DANI_NICHE_FUNDING_OFFICIAL_SOURCES','P1','OPEN','Find current official sources for narrow-fit DANI DECLARES grants and capital programs, prioritizing Georgia, South Carolina and national programs with specific ownership, employer, facilities/property-services, workforce, equipment/capital or government-market eligibility.',jsonb_build_object('authority_levels',jsonb_build_array('PRIMARY','OFFICIAL'),'current_cycle_required',true,'social_only_not_sufficient',true),jsonb_build_object('entity_scope','DANI_DECLARES')),
('FUNDING:DISCOVER:SHADOW_SOL:OFFICIAL','NICHE_FUNDING_INTELLIGENCE','SHADOW_SOL_NICHE_FUNDING_OFFICIAL_SOURCES','P1','OPEN','Find current official sources for Shadow & Sol mission funding in agriculture/food systems, land stewardship, environmental education, community programming, land/facilities and access.',jsonb_build_object('authority_levels',jsonb_build_array('PRIMARY','OFFICIAL'),'current_cycle_required',true,'restricted_fund_rules_required',true),jsonb_build_object('entity_scope','SHADOW_AND_SOL')),
('FUNDING:DISCOVER:SOCIAL_REEL:20261005','NICHE_FUNDING_INTELLIGENCE','SOCIAL_GRANT_CLAIM_REVALIDATION','P1','OPEN','Find authoritative current sources for Halstead Grant, StreetShares Foundation, Kitty Fund, BOSS Impact Fund, Good Food Fund and EmpowHER and determine current/next-cycle status and exact eligibility.',jsonb_build_object('authority_levels',jsonb_build_array('PRIMARY','OFFICIAL'),'reject_stale_claims',true,'capture_next_cycle',true),jsonb_build_object('signal_origin','SOCIAL_MEDIA_USER_SUPPLIED','observed_at','2026-10-05'))
on conflict(request_key) do update set request_status='OPEN',discovery_question=excluded.discovery_question,source_requirements=excluded.source_requirements,metadata=coalesce(public.dd_research_source_discovery_requests.metadata,'{}'::jsonb)||excluded.metadata,updated_at=now();

commit;
