create table if not exists public.dd_master_service_universe (
 id uuid primary key default gen_random_uuid(), division text not null, section text, capability text, service_family text, service_name text not null, task text, commercial_object_type text, canonical_sku text, scope text, exclusions text, dependencies text, add_ons text, condition_severity text, package_eligibility text, recurring_eligibility text, membership_eligibility text, retainer_eligibility text, ch01_rule text, ch02_rule text, ch03_rule text, ch04_rule text, ch05_rule text, ch06_rule text, market_treatment text, service_area_dispatch_zone text, customer_price text, commercial_ownership text, fulfillment_lane text, assigned_provider text, provider_qualifications text, internal_cost text, provider_payout text, margin_economics text, sop text, workflow text, qa text, documentation text, sla text, intake_requirements text, compliance_legal_boundaries text, customer_experience text, lifecycle_status text not null, version text, legacy_ids_aliases text, source_authority text not null, conflict_register text, cross_division_dependency_relationships text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(division,service_name,canonical_sku)
);
create index if not exists idx_master_service_universe_division on public.dd_master_service_universe(division);
create index if not exists idx_master_service_universe_lifecycle on public.dd_master_service_universe(lifecycle_status);
create index if not exists idx_master_service_universe_sku on public.dd_master_service_universe(canonical_sku);
insert into public.dd_master_service_universe (division,section,service_family,service_name,commercial_object_type,canonical_sku,customer_price,commercial_ownership,lifecycle_status,source_authority,legacy_ids_aliases,conflict_register)
select '01', split_part(s.service_family,' ',1), s.service_family, s.name, 'SERV', s.sku, case when s.base_price_cents is not null then '$'||to_char(s.base_price_cents/100.0,'FM999999990.00') else null end, 'DANI DECLARES LLC', case when s.commercial_status='CANONICAL_LOCKED' then 'CANONICAL_ACTIVE' else 'PENDING_RECONCILIATION' end, 'Current services registry', s.source_sku, case when s.source_status='PROPOSED' then 'Current operational record is present but underlying Division 01 reconciliation remains open.' else null end
from public.services s where s.service_family like '01%'
on conflict (division,service_name,canonical_sku) do update set updated_at=now();
insert into public.dd_master_service_universe (division,section,service_family,service_name,commercial_object_type,lifecycle_status,source_authority,conflict_register)
select '01', x.section, x.family, x.service_name, 'SERV','PENDING_RECONCILIATION','Master Operating Authority Synchronization / historical Division 01 evidence',x.conflict
from (values
('01-A','01-A Home Cleaning & Household Maintenance','Standard Maintenance Cleaning',null),('01-A','01-A Home Cleaning & Household Maintenance','Deep Structural Reset',null),('01-A','01-A Home Cleaning & Household Maintenance','Move-In / Move-Out Cleaning',null),('01-A','01-A Home Cleaning & Household Maintenance','Wall / Vertical Surface Detail',null),('01-A','01-A Home Cleaning & Household Maintenance','High-Dust / Ceiling / Overhead Detail',null),('01-A','01-A Home Cleaning & Household Maintenance','Laundry / Utility Area Detail',null),('01-A','01-A Home Cleaning & Household Maintenance','Pantry / Cabinet Interior',null),('01-A','01-A Home Cleaning & Household Maintenance','Odor Neutralization',null),('01-A','01-A Home Cleaning & Household Maintenance','Trash / Debris Removal',null),('01-A','01-A Home Cleaning & Household Maintenance','Bin Sanitation',null),('01-A','01-A Home Cleaning & Household Maintenance','Upholstery Care',null),('01-A','01-A Home Cleaning & Household Maintenance','Mattress / Bedding Refresh',null),('01-A','01-A Home Cleaning & Household Maintenance','Window / Glass Detail',null),('01-D','01-D Household Organization / Decluttering / Concierge','Household Organization',null),('01-D','01-D Household Organization / Decluttering / Concierge','Decluttering',null),('01-B','01-B Pet & Companion Support','Pet Care',null),('01-C','01-C Indoor Plant / Botanical Care','Plant Care',null),('01-E','01-E Home Watch / Household Support / Vacation Preparation','Home Watch',null),('01-E','01-E Home Watch / Household Support / Vacation Preparation','Household Concierge',null),('01-E','01-E Home Watch / Household Support / Vacation Preparation','Vacation Preparation',null),('01-F','01-F Move / Transition / Household Relocation Support','Move / Transition Support',null),('01-G+','01-G+ Seasonal / Holiday / Additional Household Support','Household Bundled Care',null)
) x(section,family,service_name,conflict)
where not exists (select 1 from public.dd_master_service_universe m where m.division='01' and lower(m.service_name)=lower(x.service_name));