insert into public.dd_sc_property_candidates
(candidate_key,address,listing_type,property_type,asking_price,available_sf,lot_acres,county,zoning_summary,school_zone_target,school_zone_status,live_work_status,dani_fit,strategic_tier,source_url,source_checked_at,blocker,notes)
values
('SC_636_HWY17','636 Highway 17, Piedmont, SC 29673','SALE','RESIDENTIAL_WITH_WORKSHOP',399900,1680,3.96,'Anderson','Residential property; business/home-occupation use requires verification','WREN_ANCHOR','MATCH','POSSIBLE_REQUIRES_APPROVAL','HIGH_INTEREST_HYBRID','HYBRID_LIVE_WORK','https://www.zillow.com/homedetails/636-Highway-17-Piedmont-SC-29673/10800803_zpid',now(),
'Verify Anderson County home occupation/business use, customer/provider traffic, storage, signage, parking, building/fire requirements, insurance/lender restrictions and whether DANI scope exceeds permitted residential accessory use.',
'Active 2026 listing; 3 bed/2 bath, 1,680 SF, 3.96 acres, separate barn with loft, workshop and tool shed; Wren school chain confirmed in current listing search. Approx. 3.4 straight-line miles from 110 Dill Dr anchor.')
on conflict(candidate_key) do update set asking_price=excluded.asking_price,available_sf=excluded.available_sf,lot_acres=excluded.lot_acres,county=excluded.county,school_zone_status=excluded.school_zone_status,live_work_status=excluded.live_work_status,dani_fit=excluded.dani_fit,strategic_tier=excluded.strategic_tier,source_checked_at=excluded.source_checked_at,blocker=excluded.blocker,notes=excluded.notes,updated_at=now();

insert into public.dd_research_work_queue(program_key,work_key,question,required_evidence,priority,status,next_action,owner_decision_required,metadata)
values
('ENTITY_ARCHITECTURE','EA_SC_636_HWY17_DILIGENCE','Can 636 Highway 17, Piedmont SC 29673 lawfully and practically serve as Danielle residence plus a limited or expanded DANI operating base without violating residential/home-occupation, building/fire, insurance, lender, tax or school-zone requirements?','Anderson County Development Standards/Building & Codes, parcel/land-use records, business-license requirements, insurer/lender terms, exact allowed home-occupation scope, current listing/inspection documents','P0','QUEUED','Run parcel-specific diligence. Separate permitted home occupation from any use requiring commercial conversion, special approval or separate flex lease.',true,'{"anchor_key":"DANI_SC_PIEDMONT_BASE","candidate_key":"SC_636_HWY17","cadence":"DAILY","cass_review":true,"accounting_impact":true,"parcel_specific_required":true}'::jsonb)
on conflict(work_key) do update set question=excluded.question,required_evidence=excluded.required_evidence,priority=excluded.priority,next_action=excluded.next_action,owner_decision_required=excluded.owner_decision_required,metadata=excluded.metadata,updated_at=now();

insert into public.dd_cass_finance_compliance_queue
(source_domain,source_key,review_type,title,accounting_question,legal_or_tax_dependency,financial_statement_area,entity_scope,priority,owner_decision_required)
values
('ENTITY_ARCHITECTURE','EA_SC_636_HWY17_DILIGENCE','HYBRID_PROPERTY_UNDERWRITING','636 Highway 17 hybrid live/work diligence','Compare residential acquisition cost and personal housing allocation against any legally supportable DANI business-use allocation, workshop/outbuilding use, operating-cost savings and separate-flex alternative. Do not treat the full property as a business asset or expense.','Home-occupation/permitted-use, mixed-use tax allocation, lender/insurance restrictions, business licensing and occupancy rules','Personal housing / business-use allocation / fixed assets / occupancy','DANI + private','P0',true)
on conflict(source_domain,source_key,review_type) do update set accounting_question=excluded.accounting_question,legal_or_tax_dependency=excluded.legal_or_tax_dependency,financial_statement_area=excluded.financial_statement_area,entity_scope=excluded.entity_scope,priority=excluded.priority,owner_decision_required=excluded.owner_decision_required,updated_at=now();
