
create or replace view public.dd_company_owner_attention_v1 as select id,priority,domain,reason,recommended_action,source_table,source_record_id,metadata,created_at from public.dd_owner_attention_queue where status='OPEN' order by case priority when 'P0' then 1 when 'P1' then 2 when 'P2' then 3 else 4 end,created_at;
create or replace view public.dd_contextual_support_actions_v1 as select id job_id,public_reference,job_title,job_status,scheduled_start,division_slug,case when job_status in('SCHEDULED','ASSIGNED','DISPATCHED') then array['VIEW_STATUS','PREPARE_FOR_SERVICE','CHANGE_ACCESS','REQUEST_RESCHEDULE','REQUEST_ADD_ON','GET_HELP'] when job_status='IN_PROGRESS' then array['VIEW_STATUS','GET_HELP','REPORT_SAFETY_OR_SCOPE_ISSUE'] when job_status in('COMPLETED','CLOSED') then array['VIEW_COMPLETION','REPORT_ISSUE','BILLING_HELP','BOOK_AGAIN','LEAVE_FEEDBACK'] else array['VIEW_STATUS','GET_HELP'] end available_actions,false automatic_refund_authority,false automatic_dispatch_change_authority from public.dd_jobs;
create or replace view public.dd_support_command_center_v1 as select c.id,c.case_number,c.audience,c.case_type,c.category,c.status,c.priority,c.job_id,c.canonical_sku,c.channel_code,c.division,c.subject,c.resolution_authority,c.sla_due_at,c.owner_approval_required,c.created_at,c.updated_at,j.public_reference job_reference,j.job_status,j.assigned_to,(c.sla_due_at<now() and c.status not in('RESOLVED','CLOSED')) sla_breached from public.dd_support_cases c left join public.dd_jobs j on j.id=c.job_id;
create or replace view public.dd_support_readiness_summary_v1 as select count(*) total_services,count(*) filter(where support_ready) support_ready,count(*) filter(where not preparation_defined) missing_preparation,count(*) filter(where not change_cancel_defined) missing_change_cancel,count(*) filter(where not support_topics_defined) missing_support_topics,count(*) filter(where not evidence_requirements_defined) missing_evidence,count(*) filter(where not recovery_rules_defined) missing_recovery,count(*) filter(where not escalation_rules_defined) missing_escalation,count(*) filter(where not compliance_boundary_defined) missing_compliance_boundary from public.dd_service_support_readiness;
create or replace view public.dd_operator_command_center_v1 as
select 'OWNER_ATTENTION'::text item_type,id::text item_id,domain,priority,reason title,status,created_at,null::timestamptz due_at,jsonb_build_object('recommended_action',recommended_action,'metadata',metadata) payload from public.dd_owner_attention_queue
union all select 'RESEARCH_WORK',id::text,program_key,priority,question,status,created_at,null::timestamptz,jsonb_build_object('blocker',blocker,'next_action',next_action,'metadata',metadata) from public.dd_research_work_queue
union all select 'SOFTWARE_BUILD',id::text,'SOFTWARE',priority,pass_name||' — '||coalesce(blocking_gap,work_key),status,created_at,null::timestamptz,jsonb_build_object('execution_mode',execution_mode,'work_type',work_type,'acceptance_criteria',acceptance_criteria,'required_build',required_build,'repository',repository) from public.dd_software_build_work_queue
union all select 'ASANA_TASK',id::text,'ASANA',case when due_at<now() and task_status<>'COMPLETED' then 'P0' else 'P2' end,task_name,task_status,synced_at,due_at,jsonb_build_object('external_task_id',external_task_id,'project_id',external_project_id,'assignee',assignee_name,'source_url',source_url) from public.dd_operator_dashboard_external_tasks;
create or replace function public.dd_triage_support_case(p_case_id uuid) returns jsonb language plpgsql security definer set search_path='public' as $$declare c dd_support_cases%rowtype; p text; own boolean; auth text; begin select * into c from dd_support_cases where id=p_case_id for update;if not found then raise exception 'support case not found';end if;p:=case when c.category in('SAFETY','DAMAGE','SECURITY','LEGAL_COMPLIANCE') then 'P0' when c.category in('NO_SHOW','PAYMENT_DISPUTE','QUALITY','INCOMPLETE_WORK','ACCESS_FAILURE') then 'P1' else 'P2' end;own:=c.category in('SAFETY','DAMAGE','SECURITY','LEGAL_COMPLIANCE','REFUND_REQUEST','PAYMENT_DISPUTE');auth:=case when own then 'OWNER_REVIEW' else 'OPS_REVIEW' end;update dd_support_cases set priority=p,owner_approval_required=own,resolution_authority=auth,sla_due_at=coalesce(sla_due_at,now()+case when p='P0' then interval '1 hour' when p='P1' then interval '4 hours' else interval '1 day' end),updated_at=now() where id=p_case_id;if own and not exists(select 1 from dd_owner_attention_queue where source_table='dd_support_cases' and source_record_id=p_case_id::text and status='OPEN') then insert into dd_owner_attention_queue(domain,source_table,source_record_id,reason,priority,status,recommended_action,metadata) values('SUPPORT','dd_support_cases',p_case_id::text,'Support case requires governed owner review',p,'OPEN','Review case, job/scope/evidence/payment context and choose an authorized resolution.',jsonb_build_object('case_number',c.case_number,'category',c.category,'job_id',c.job_id,'no_automatic_refund',true,'no_automatic_dispatch_change',true));end if;return jsonb_build_object('case_id',p_case_id,'priority',p,'owner_approval_required',own,'resolution_authority',auth,'external_side_effects',false);end$$;
