CREATE TABLE IF NOT EXISTS public.dd_service_channel_availability (service_id uuid NOT NULL REFERENCES public.services(id) ON DELETE CASCADE, channel_code text NOT NULL REFERENCES public.dd_commercial_channels(code), eligibility_status text NOT NULL DEFAULT 'ELIGIBLE', notes text, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY (service_id, channel_code));
CREATE TABLE IF NOT EXISTS public.dd_service_pricing_rules (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), service_id uuid NOT NULL REFERENCES public.services(id) ON DELETE CASCADE, channel_code text REFERENCES public.dd_commercial_channels(code), pricing_type text NOT NULL CHECK (pricing_type IN ('FIXED','STARTING_AT','VARIABLE_QUOTE','RETAINER','SOW_PROCUREMENT')), base_price_cents integer CHECK (base_price_cents IS NULL OR base_price_cents >= 0), currency text NOT NULL DEFAULT 'USD' CHECK (currency='USD'), billing_cycle text NOT NULL DEFAULT 'ONETIME' CHECK (billing_cycle IN ('ONETIME','HOURLY','DAILY','MONTHLY','RECURRING','PROJECT')), lock_status text NOT NULL DEFAULT 'PENDING' CHECK (lock_status IN ('LOCKED','BASELINE','PROPOSED','PENDING')), resident_discount_eligible boolean NOT NULL DEFAULT false, tax_class text, effective_date date, status text NOT NULL DEFAULT 'PENDING_RECONCILIATION' CHECK (status IN ('ACTIVE','PENDING_RECONCILIATION','RETIRED')), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS ux_dd_service_pricing_rules_service_channel ON public.dd_service_pricing_rules(service_id, channel_code) WHERE channel_code IS NOT NULL;
CREATE TABLE IF NOT EXISTS public.dd_service_requirements (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), service_id uuid NOT NULL REFERENCES public.services(id) ON DELETE CASCADE, requirement_type text NOT NULL CHECK (requirement_type IN ('CAPABILITY','CREDENTIAL','LICENSE','CERTIFICATION','INSURANCE','EQUIPMENT','VEHICLE','OTHER')), requirement_code text NOT NULL, required boolean NOT NULL DEFAULT true, minimum_level text, notes text, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(service_id, requirement_type, requirement_code));
ALTER TABLE public.dd_service_channel_availability ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dd_service_pricing_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dd_service_requirements ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.dd_service_channel_availability FROM anon, authenticated;
REVOKE ALL ON public.dd_service_pricing_rules FROM anon, authenticated;
REVOKE ALL ON public.dd_service_requirements FROM anon, authenticated;
TRUNCATE public.divisions RESTART IDENTITY CASCADE;
INSERT INTO public.divisions (name,slug,description,is_active,sort_order) VALUES
('Home, Pet, Plant & Household Support','home-pet-plant-household-support','Home cleaning, pet care, indoor plant care, household concierge and move/household support.',true,1),
('Property, Facilities & Field Operations','property-facilities-field-operations','Property and facilities maintenance, field services, inspections, work-order coordination and supplies.',true,2),
('Real Estate & Closing Support','real-estate-closing-support','Listing, showing, transaction, turnover and closing support for real-estate professionals and stakeholders.',true,3),
('Administrative & Business Operations','administrative-business-operations','Administrative, office, data, document and workflow operations support.',true,4),
('Notary & Document Services','notary-document-services','Notarial, loan-signing and authorized document field services.',true,5),
('Business Formation & Digital Infrastructure','business-formation-digital-infrastructure','Business formation support and digital/technical infrastructure setup.',true,6),
('Marketing, Content & Media Production','marketing-content-media-production','Marketing strategy, social/content, photography and video production.',true,7),
('Business Development & Growth','business-development-growth','Sales pipeline, partnerships, referrals and growth consulting.',true,8),
('Classes, Workshops & Training','classes-workshops-training','Classes, workshops, business training and skills/lifestyle education.',true,9),
('Experiences & Resident Programming','experiences-resident-programming','Event planning, resident programming and event production.',true,10),
('Creative Design & Production','creative-design-production','Graphic design, print, apparel, merchandise and custom fabrication.',true,11),
('Logistics, Courier & Asset Sourcing','logistics-courier-asset-sourcing','Courier, procurement, material sourcing, asset movement and field logistics.',true,12),
('Government & Institutional Procurement','government-institutional-procurement','Government/institutional readiness, contract administration and approved public-sector delivery.',true,13);
UPDATE public.dd_catalog_governance SET authority_version='DANI DECLARES Current Commercial Architecture v2026-08-27', phase='PHASE_1_CANONICAL_CATALOG_HYDRATION', status='CANONICAL_CATALOG_ONLY', pricing_status='PENDING_RECONCILIATION', effective_date='2026-08-27', rules = rules || jsonb_build_object('channels',ARRAY['CH01','CH02','CH03','CH04','CH05','CH06'],'divisions',13,'geography','GA','service_pricing_framework','dd_service_pricing_rules','channel_availability_framework','dd_service_channel_availability','service_requirements_framework','dd_service_requirements','worker_taxonomy',jsonb_build_object('type','capability_network','official_channels',false,'network_access_is_entitlement',true,'no_guaranteed_work',true,'job_access_requires_authorization',true)), updated_at=now();