
create or replace function public.dd_run_service_discovery_controller() returns uuid language plpgsql security definer set search_path='public' as $$declare r uuid:=gen_random_uuid(); n int:=0;s int:=0;begin select count(*) into s from dd_service_discovery_candidates where underwriting_status='RESEARCH_ONLY';insert into dd_research_work_queue(program_key,work_key,question,required_evidence,priority,status,blocker,next_action,owner_decision_required,metadata) select 'SERVICE_DISCOVERY','candidate:'||c.candidate_key,'Determine whether "'||c.service_name||'" is beneficial and safe for DANI DECLARES to add. Validate demand, duplication, licensing/regulatory boundaries, insurance, safety, provider capability, equipment, workflow, channel fit, economics and fulfillment.','Current market evidence; authoritative regulatory evidence where applicable; insurance/safety; provider capability; economics; scope/exclusions; channel fit.',case c.research_priority when 'HIGH' then 'P1' else 'P2' end,'QUEUED','ACTIVATION_PROHIBITED_UNTIL_ALL_GATES_PASS','Research candidate gates. Keep RESEARCH_ONLY while any gate is unresolved.',false,jsonb_build_object('candidate_id',c.id,'activation_prohibited',true) from dd_service_discovery_candidates c where c.underwriting_status='RESEARCH_ONLY' on conflict(program_key,work_key) do update set question=excluded.question,required_evidence=excluded.required_evidence,priority=excluded.priority,blocker=excluded.blocker,next_action=excluded.next_action,metadata=excluded.metadata,updated_at=now();get diagnostics n=row_count;update dd_service_discovery_candidates set release_eligible=false,activation_prohibited=true,updated_at=now() where underwriting_status<>'RELEASED';insert into dd_service_discovery_runs(id,status,candidates_scanned,research_items_created,blocked_from_activation,evidence,completed_at) values(r,'COMPLETED',s,n,(select count(*) from dd_service_discovery_candidates where activation_prohibited),jsonb_build_object('auto_activation',false,'owner_review_before_release',true),now());return r;end$$;
create or replace function public.dd_run_safe_automation_recipes() returns uuid language plpgsql security definer set search_path='public' as $$declare r uuid:=gen_random_uuid();n int:=0;t int:=0;begin
insert into dd_owner_attention_queue(domain,source_table,source_record_id,reason,priority,recommended_action,metadata) select 'SALES','dd_sales_queue',s.id::text,'Speed-to-lead SLA exceeded','P1','Review and respond through Sales.',jsonb_build_object('source',s.source,'age_minutes',round(extract(epoch from(now()-coalesce(s.source_occurred_at,s.created_at)))/60)) from dd_sales_queue s where coalesce(s.do_not_contact,false)=false and s.disposition='NOT_CONTACTED' and(s.phone is not null or s.email is not null) and coalesce(s.source_occurred_at,s.created_at)<now()-interval '30 minutes' on conflict do nothing;get diagnostics n=row_count;t:=t+n;
insert into dd_owner_attention_queue(domain,source_table,source_record_id,reason,priority,recommended_action,metadata) select 'OPERATIONS','dd_jobs',j.id::text,'Job SLA deadline exceeded','P0','Review assignment/status and recover the job.',jsonb_build_object('job_status',j.job_status,'sla_due_at',j.sla_due_at) from dd_jobs j where j.sla_due_at is not null and j.sla_due_at<now() and coalesce(j.job_status,'') not in('COMPLETED','CANCELLED','CLOSED') on conflict do nothing;get diagnostics n=row_count;t:=t+n;
insert into dd_owner_attention_queue(domain,source_table,source_record_id,reason,priority,recommended_action,metadata) select 'QA','dd_jobs',j.id::text,'Completed job has no job evidence','P0','Collect/verify required evidence before closeout.',jsonb_build_object('job_status',j.job_status) from dd_jobs j where j.job_status in('COMPLETED','CLOSED') and not exists(select 1 from dd_job_evidence e where e.job_id=j.id) on conflict do nothing;get diagnostics n=row_count;t:=t+n;
insert into dd_automation_recipe_runs(id,recipe_key,status,matched_count,actioned_count,evidence,completed_at) values(r,'safe_automation_sweep','COMPLETED',t,t,jsonb_build_object('mode','detect_and_queue','external_side_effects',false),now());update dd_automation_recipes set last_run_at=now() where is_active;return r;end$$;
insert into dd_automation_recipes(recipe_key,recipe_name,domain,trigger_type,execution_mode,risk_tier,owner_attention_on_match,cooldown_minutes,condition_spec,action_spec) values
('speed_to_lead_watch','Speed-to-lead watch','SALES','SCHEDULE','DETECT_ONLY','LOW',true,15,'{"age_minutes":30}','{"queue_owner_attention":true}'),
('capacity_watch','Provider capacity watch','OPERATIONS','SCHEDULE','DETECT_ONLY','LOW',true,60,'{"capacity":"reached"}','{"queue_owner_attention":true}'),
('provider_offer_expiry_watch','Provider offer expiry watch','OPERATIONS','SCHEDULE','DETECT_ONLY','LOW',true,15,'{"offer":"expired_unanswered"}','{"queue_owner_attention":true}'),
('provider_performance_snapshot','Provider performance snapshot','PROVIDER_OPERATIONS','SCHEDULE','DETECT_ONLY','LOW',false,1440,'{}','{"snapshot_only":true}')
on conflict(recipe_key) do update set recipe_name=excluded.recipe_name,domain=excluded.domain,trigger_type=excluded.trigger_type,execution_mode=excluded.execution_mode,risk_tier=excluded.risk_tier,is_active=true,owner_attention_on_match=excluded.owner_attention_on_match,cooldown_minutes=excluded.cooldown_minutes,condition_spec=excluded.condition_spec,action_spec=excluded.action_spec,updated_at=now();
insert into dd_research_authority_policy(domain,auto_research,auto_reconcile_low_risk,owner_required_actions,notes) values
('PRICING',true,false,array['PUBLISH_PRICE','CHANGE_CANONICAL_PRICE'],'Research may proceed autonomously; commercial publication remains governed.'),
('SERVICE_DISCOVERY',true,false,array['ACTIVATE_SERVICE','PUBLISH_SERVICE'],'Discovery remains research-only until release gates pass.'),
('PROVIDER_CAPACITY',true,false,array['AUTHORIZE_PROVIDER','ASSIGN_JOB'],'Capacity research may run; provider authorization and assignment remain governed.'),
('SOFTWARE',true,false,array['MERGE_HIGH_RISK','DIRECT_PRODUCTION_WRITE'],'Detection/build work requires evidence gates.')
on conflict(domain) do update set auto_research=excluded.auto_research,auto_reconcile_low_risk=excluded.auto_reconcile_low_risk,owner_required_actions=excluded.owner_required_actions,notes=excluded.notes,updated_at=now();
