export const DRIVE_READONLY_SCOPE='https://www.googleapis.com/auth/drive.readonly';
export function hasDriveReadonlyGrant(connection){const p=Array.isArray(connection?.permissions)?connection.permissions:[];return p.includes(DRIVE_READONLY_SCOPE);}
export function normalizeDriveFile(file,accountEmail){return{drive_file_id:file.id,file_name:file.name||file.id,drive_path:null,mime_type:file.mimeType||null,modified_at:file.modifiedTime||null,classification:'UNCLASSIFIED',authority_status:'EVIDENCE_ONLY',extraction_status:'QUEUED',conflict_status:'UNCHECKED',source_url:file.webViewLink||null,metadata:{source_system:'GOOGLE_DRIVE',account_email:accountEmail||null,version:file.version||null,md5_checksum:file.md5Checksum||null,size:file.size||null,parents:file.parents||[],trashed:Boolean(file.trashed),drive_id:file.driveId||null,owners:(file.owners||[]).map(x=>({display_name:x.displayName||null,email_address:x.emailAddress||null})),authority_status:'EVIDENCE_ONLY'}};}
export function driveSyncMode(connection){const token=connection?.metadata?.drive_change_page_token||null;const backfillComplete=Boolean(connection?.metadata?.drive_intelligence_backfill_complete);return token&&backfillComplete?{mode:'INCREMENTAL',pageToken:String(token)}:{mode:'BOUNDED_BACKFILL',pageToken:token?String(token):null};}
export function driveBackfillState(connection){const m=connection?.metadata||{};return{pageToken:m.drive_intelligence_backfill_page_token||null,complete:Boolean(m.drive_intelligence_backfill_complete)};}
export function completeDriveBackfillMetadata(existing={},changePageToken=null){return nextDriveSyncMetadata(existing,{drive_intelligence_backfill_page_token:null,drive_intelligence_backfill_complete:true,drive_change_page_token:changePageToken?String(changePageToken):(existing||{}).drive_change_page_token||null,drive_backfill_completed_at:new Date().toISOString()});}
export function nextDriveSyncMetadata(existing={},patch={}){return{...(existing||{}),...patch,drive_intelligence_sync_version:2};}
export function driveExtractionPlan(file){const mime=String(file?.mimeType||'').toLowerCase();if(mime==='application/vnd.google-apps.document')return{mode:'EXPORT_TEXT',mimeType:'text/plain'};if(mime==='application/vnd.google-apps.spreadsheet')return{mode:'EXPORT_TEXT',mimeType:'text/csv'};if(mime==='application/vnd.google-apps.presentation')return{mode:'EXPORT_TEXT',mimeType:'text/plain'};if(mime.startsWith('text/')||mime==='application/json'||mime==='application/xml')return{mode:'DOWNLOAD_TEXT',mimeType:mime};return{mode:'METADATA_ONLY',mimeType:mime||null};}
export function boundedDriveText(text,maxChars=262144){if(text==null)return null;const value=String(text);return value.length>maxChars?value.slice(0,maxChars):value;}
