import {createClient} from '@supabase/supabase-js';
import {decryptSecret,encryptSecret,ENVIRONMENT,logIntegrationEvent,requireStaff} from '../../_integrationOAuth.js';
import {hasDriveReadonlyGrant,normalizeDriveFile,driveSyncMode,nextDriveSyncMetadata} from './driveIntelligenceIngestion.js';
function adminClient(){const url=process.env.SUPABASE_URL||process.env.REACT_APP_SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error('Server Supabase configuration is missing.');return createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});}
async function refresh(supabase,c){const rt=decryptSecret(c.refresh_token_ciphertext);if(!rt)throw new Error('DRIVE_REFRESH_TOKEN_MISSING');const response=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'refresh_token',client_id:process.env.GOOGLE_CLIENT_ID||'',client_secret:process.env.GOOGLE_CLIENT_SECRET||'',refresh_token:rt})});const body=await response.json();if(!response.ok||!body.access_token)throw new Error(body.error_description||body.error||'DRIVE_TOKEN_REFRESH_FAILED');const encrypted=encryptSecret(body.access_token);await supabase.from('dd_integration_connections').update({access_token_ciphertext:encrypted,token_expires_at:body.expires_in?new Date(Date.now()+Number(body.expires_in)*1000).toISOString():null,updated_at:new Date().toISOString()}).eq('id',c.id);return body.access_token;}
async function driveJson(url,token){const response=await fetch(url,{headers:{Authorization:'Bearer '+token}});const body=await response.json();if(!response.ok){const e=new Error(body?.error?.message||'DRIVE_API_FAILED');e.status=response.status;throw e;}return body;}
async function syncConnection(supabase,c){if(!hasDriveReadonlyGrant(c))throw Object.assign(new Error('DRIVE_READONLY_RECONSENT_REQUIRED'),{status:409});let token=c.access_token_ciphertext?decryptSecret(c.access_token_ciphertext):null;if(!token||!c.token_expires_at||new Date(c.token_expires_at).getTime()<Date.now()+60000)token=await refresh(supabase,c);const email=String(c.token_metadata?.email||'').toLowerCase();const mode=driveSyncMode(c);let files=[],nextToken=mode.pageToken||null,modeUsed=mode.mode;
if(mode.mode==='INCREMENTAL'){const changes=await driveJson('https://www.googleapis.com/drive/v3/changes?pageSize=100&includeRemoved=true&fields=nextPageToken,newStartPageToken,changes(fileId,removed,file(id,name,mimeType,modifiedTime,version,md5Checksum,size,parents,trashed,driveId,owners(displayName,emailAddress),webViewLink))&pageToken='+encodeURIComponent(mode.pageToken),token);files=(changes.changes||[]).filter(x=>!x.removed&&x.file&&!x.file.trashed).map(x=>x.file);nextToken=changes.newStartPageToken||changes.nextPageToken||nextToken;}else{const list=await driveJson('https://www.googleapis.com/drive/v3/files?pageSize=100&q=trashed%3Dfalse&fields=nextPageToken,files(id,name,mimeType,modifiedTime,version,md5Checksum,size,parents,trashed,driveId,owners(displayName,emailAddress),webViewLink)',token);files=list.files||[];const start=await driveJson('https://www.googleapis.com/drive/v3/changes/startPageToken',token);nextToken=start.startPageToken||nextToken;}
let queued=0;for(const file of files){const row=normalizeDriveFile(file,email);const {error}=await supabase.from('dd_drive_research_intake').upsert({...row,updated_at:new Date().toISOString()},{onConflict:'drive_file_id'});if(error)throw error;queued++;}
const now=new Date().toISOString(),metadata=nextDriveSyncMetadata(c.metadata||{},{drive_change_page_token:nextToken,drive_last_sync_mode:modeUsed,drive_last_sync_at:now});const {error}=await supabase.from('dd_integration_connections').update({last_sync_at:now,last_error:null,metadata,updated_at:now}).eq('id',c.id);if(error)throw error;await logIntegrationEvent({supabase,adapterCode:'GOOGLE_DRIVE',connectionId:c.id,direction:'INBOUND',eventType:'DRIVE_INTELLIGENCE_SYNC',status:'PROCESSED',payload:{files_seen:files.length,intake_queued:queued,sync_mode:modeUsed}});return{filesSeen:files.length,queued,mode:modeUsed};}
export default async function handler(req,res){if(!['GET','POST'].includes(req.method))return res.status(405).json({success:false,error:'Method not allowed'});const supabase=adminClient();try{const cronAuthorized=process.env.CRON_SECRET&&req.headers.authorization==='Bearer '+process.env.CRON_SECRET;if(!cronAuthorized)await requireStaff(req);const {data,error}=await supabase.from('dd_integration_connections').select('*').eq('adapter_code','GOOGLE_DRIVE').eq('environment',ENVIRONMENT).eq('connection_status','CONNECTED');if(error)throw error;if(!data?.length)return res.status(200).json({success:true,connected:false,files_seen:0});let files=0,queued=0;for(const c of data){const r=await syncConnection(supabase,c);files+=r.filesSeen;queued+=r.queued;}return res.status(200).json({success:true,connected:true,files_seen:files,intake_queued:queued});}catch(error){return res.status(error.status||500).json({success:false,error:error.message||'DRIVE_INTELLIGENCE_SYNC_FAILED'});}}